### ISSUE TITLE
Route error then No hint path defined for [l5-swagger] error

### ISSUE THREAD

**Issue by alnutile** [DarkaOnLine/L5-Swagger#1]
I have a number of new L5 packages so the others work fine. I followed you instructions as well.

## Routes

Finally I copied your route info into mine and obviously routes worked. 

But I do see your routes.php included in the provider but when I went to /api-docs I got the standard not found error

https://www.dropbox.com/s/urs48l0xvpsqk47/Screenshot%202015-03-20%2006.40.28.png?dl=0

So I copied your routes into mine which led to the next error

## No hint path defined for [l5-swagger].

https://www.dropbox.com/s/hw4afo35kp1evhh/Screenshot%202015-03-20%2006.37.49.png?dl=0

This one I had to add this line to my routes.php

~~~
Route::get('api-docs', function() {
	View::addNamespace('l5-swagger', base_path('/resources/views/vendor/l5-swagger'));
	if (Config::get('l5-swagger.generateAlways')) {
		\Darkaonline\L5Swagger\Generator::generateDocs();
	}
~~~

Now the page loads though I still need to explore how it is working

https://www.dropbox.com/s/e18obt2jcswgwf6/Screenshot%202015-03-20%2006.42.02.png?dl=0

Thanks for your work on this btw!

**Comment by DarkaOnLine** [comment]
HI, @alnutile 

Sorry for inconvenience, but it was error in Installation instruction. Now I updated them.

You should register Provider not on `config/app.php` but in  `app/Providers/AppServiceProvider.php` like this and then publish asset:

```php
public function register()
{
        $this->app->bind(
            'Illuminate\Contracts\Auth\Registrar',
            'App\Services\Registrar'
        );

        //Register Swagger Provider
        $this->app->register('Darkaonline\L5Swagger\L5SwaggerServiceProvider');
}
```

**Comment by alnutile** [comment]
Thanks!

Al Nutile
http://alfrednutile.info/about
413.345.5103


On Fri, Mar 20, 2015 at 7:16 AM, Darius Matulionis <notifications@github.com
