### ISSUE TITLE
laravel 5.2 version

### ISSUE THREAD

**Issue by BioPhoton** [DarkaOnLine/L5-Swagger#10]
Would love to see a version for 5.2

**Comment by DarkaOnLine** [comment]
You should be able to install it on L5.2. Did you tried or get some errors ?

**Comment by odin88** [comment]
No support for 5.0 ?

**Comment by DarkaOnLine** [comment]
Foto Laravel 5 use 2.0 branch 

'composer require darkaonline/l5-swagger ~2.0'
