### ISSUE TITLE
Swagger-UI Resources Missing

### ISSUE THREAD

**Issue by s1rc** [DarkaOnLine/L5-Swagger#100]
- L5-Swagger Version: 5.5.2
- PHP Version (`php -v`): 7.1.8
- OS: macOS

### Description:
When trying to view API Docs, css and js assets are missing. Server returns 404. Do I need to add these into the vendor folder generated from artisan l5-swagger:publish

````
:8080/docs/asset/swagger-ui.css Failed to load resource: the server responded with a status of 404 (Not Found)
09:36:05.147 swagger-ui-bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
09:36:05.147 swagger-ui-standalone-preset.js Failed to load resource: the server responded with a status of 404 (Not Found)
09:36:05.435 documentation:75 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (documentation:75)
09:36:05.455 :8080/docs/asset/favicon-16x16.png Failed to load resource: the server responded with a status of 404 (Not Found)
09:36:05.457 :8080/docs/asset/favicon-32x32.png Failed to load resource: the server responded with a status of 404 (Not Found)
09:36:09.536 swagger-ui.css Failed to load resource: the server responded with a status of 404 (Not Found)
````

### Steps To Reproduce:

1. Setup L5-Swagger with composer
2. Run artisan l5-swagger:publish
3. Modify l5-swagger.php config file
4. Run artisan config:cache
5. Run artisan route:cache
6. Run artisan l5-swagger:generate

**Comment by DarkaOnLine** [comment]
It looks like a php build in server issue.

How are you running your php server?

Please try this: `php -S localhost:8080 -t public `

**Comment by s1rc** [comment]
`php -S localhost:8080 -t public` does not work, resources are still 404.
`php -S localhost:8080 public/index.php` does work for Swagger-ui, however now all the assets in the main application are 404.

**Comment by DarkaOnLine** [comment]
I am not using php server and don't know much about them. I recommend you to try [Laravel valet](https://laravel.com/docs/5.5/valet) - simple to install, works with a bunch of frameworks.

Closing this, cause it's not related to the package.

**Comment by sohaieb** [comment]
Hello, I have the solution, 
you have first to check updates with this command:
`composer update`
then publish the Swagger views with this command : 
`php artisan swagger-lume:publish`
and then create a new folder named **swagger-ui-assets** in laravel **public** folder, 
finaly put wanted css & js files from **{yourproject}/vendor/swagger-api/swagger-ui/dist** to **{yourproject}/public/swagger-ui-assets**.
that's all

**Comment by Daniil-Solovev** [comment]
In my case the problem was that I was dumping sql queries via the built-in dump() function in laravel. Actually, swagger should be displayed on a blank page, without debug mode, etc.

**Comment by thanhkhuatdac** [comment]
I have fixed that issue by steps:

just copied files from vendor folder and added in the specific path.

Copy all the files from : laravel-yourapp\vendor\swagger-api\swagger-ui\dist

Then paste all files in path: laravel-yourapp\public\docs\asset

**Comment by es2ws** [comment]
what @thanhkhuatdac suggested works great, but better way for servers and mac without copying is symlink:
`ln -s /path-to-your-laravel-app/vendor/swagger-api/swagger-ui/dist/ /path-to-your-laravel-app/public/docs/asset `
and also keep i mind that you need to have /path-to-your-laravel-app/public/docs already created

**Comment by WuzorGiftKnowledge** [comment]
> I have fixed that issue by steps:
> 
> just copied files from vendor folder and added in the specific path.
> 
> Copy all the files from : laravel-yourapp\vendor\swagger-api\swagger-ui\dist
> 
> Then paste all files in path: laravel-yourapp\public\docs\asset

This works fine on my localhost but when I deploy the app api/documentation returns 404 error

**Comment by VictorZZZZ** [comment]
After copying
` /path-to-your-laravel-app/vendor/swagger-api/swagger-ui/dist/ `
to 
`/path-to-your-laravel-app/public/docs/asset `

I get the new error:

> Refused to apply style from 'http://laravel-project.loc/docs/asset/swagger-ui.css?v=b47dcdb59251cf1254ee38395c18b5b9' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by Gossteer** [comment]
Maybe you use common settings for nginx:

```
    location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
        expires max;
        try_files $uri =404;
    }
```

Need add: 
```
    location ~ (^/docs/asset/.*) {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
        expires max;
        try_files $uri =404;
    }
```

Or wait - https://github.com/DarkaOnLine/L5-Swagger/pull/503
