### ISSUE TITLE
Required @SWG\Info() not found

### ISSUE THREAD

**Issue by robote** [DarkaOnLine/L5-Swagger#104]
- L5-Swagger Version: 5.5.23 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):7.1
- OS:

### Description:
Required @SWG\Info() not found

### Steps To Reproduce:
1.composer require "darkaonline/l5-swagger:5.5.*"
2.Run php artisan l5-swagger:publish 
3.Run php artisan l5-swagger:generate

result:

Regenerating docs
In Logger.php line 38:
  **Required @SWG\Info() not found**

can you help me? tks

**Comment by DarkaOnLine** [comment]
https://github.com/DarkaOnLine/L5-Swagger/issues?utf8=%E2%9C%93&q=SWG%5CInfo
