### ISSUE TITLE
docExpansion?

### ISSUE THREAD

**Issue by MetalRex101** [DarkaOnLine/L5-Swagger#105]
- L5-Swagger Version: 5.5.2 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.0.20
- OS: macOS Sierra

### Description:
Is there a way to set docExpansion property?

**Comment by DarkaOnLine** [comment]
Yes - run `php artisan l5-swagger:publish-views` and  edit `resources/views/vendor/l5-swagger/index.blade.php` by adding `docExpansion: full`  or `docExpansion: none`

**Comment by CrixuAMG** [comment]
@DarkaOnLine this command is no longer present, what is the current way of getting the views?

**Comment by DarkaOnLine** [comment]
```bash
php artisan vendor:publish --provider 'L5Swagger\L5SwaggerServiceProvider'
```

**Comment by CrixuAMG** [comment]
Thanks for the fast reply, that fixed it!

What would be the location to put the `docExpansion` in? I've tried putting it in the `SwaggerUIBundle` section, but that resulted in a blank page being shown.

**Comment by DarkaOnLine** [comment]
The option could be passed in one of the following ways:

- The `swagger-config.yaml` in the project root directory, if it exists, is baked into the application
- configuration object passed as an argument to Swagger-UI (`SwaggerUI({ ... })`)
- configuration document fetched from a specified `configUrl`
- configuration items passed as key/value pairs in the URL query string

Please see SwaggerUi documentation for more details: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md

**Comment by CrixuAMG** [comment]
Thanks again for the fast reply, I'll take a good look at the configuration documentation and try out some of the available options!
