### ISSUE TITLE
ClientId in swaggerUI

### ISSUE THREAD

**Issue by beschoenen** [DarkaOnLine/L5-Swagger#106]
I want to provide a predefined clientId for users to log in with, so they can test the documentation without reaching out to me about the clientId they should use.

I currently edited some of the files from the package to get it to work, but they're not optimal, so I was wonder what it would take for you to accept this as a feature?

My current edits:

config/l5-swagger.php
```php
'security' => [
        /*
        |--------------------------------------------------------------------------
        | Examples of Security definitions
        |--------------------------------------------------------------------------
        */
        'oauth' => [
            'type' => 'oauth2',
            'description' => 'Login with OAuth2',
            'flow' => 'implicit',
            'authorizationUrl' => config('app.url').'/oauth/authorize',
            'tokenUrl' => config('app.url').'/oauth/token',
            'clientId' => 9
        ],
    ],
```

I added the clientId attribute here.

```php
ui.initOAuth({
  clientId: "{!! config('l5-swagger.security.oauth.clientId') !!}",
  appName: "{{ config('app.name') }}"
});
```

I also added this piece of code to the index.blade.php file, so that SwaggerUI can get the actual clientId.

One of the things is that the config key used in the blade files is of course variable, so that won't work.

**Comment by DarkaOnLine** [comment]
If I understanding you correctly - all your edits are done in vendor files? Or did you published config and view files and made corrections?

**Comment by beschoenen** [comment]
Vendor files, but I'd like the make is so that I can make a PR here.

**Comment by beschoenen** [comment]
Or would you suggest just modifying a published version of the index.blade.php?

**Comment by DarkaOnLine** [comment]
PR is unnecessary here. You need to publish config with view and make your changes.

- run`l5-swagger:publish-config` , this will create a file in your project `config/l5-swagger.php `
- make your changes in `config/l5-swagger.php`
- run `l5-swagger:publish-views`, this will create a file in your project `resources/views/vendor/l5-swagger/index.blade.php` and make changes

That's it ;) 

P.S. Don't forget to add these files to your version control ;)

**Comment by beschoenen** [comment]
Ok, thank you.
