### ISSUE TITLE
can't set request header

### ISSUE THREAD

**Issue by vishalvolcone** [DarkaOnLine/L5-Swagger#107]
```
 *    security={"X-Scaled-Token": {}},
 *   @SWG\SecurityScheme(
 *         securityDefinition="X-Scaled-Token",
 *         type="apiKey",
 *         in="header",
 *         name="X-Scaled-Token"
 *     )
```
i set this code but i can't found X-Scaled-Token header in my middleware.
that's why authentication is not work for me.

**Comment by DarkaOnLine** [comment]
You can declare your security definitions in config: https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php#L118-L123

**Comment by Meera9** [comment]
@vishalvolcone  this is work for me - https://github.com/swagger-api/swagger-ui/issues/5646#issuecomment-1782597849
