### ISSUE TITLE
Is Lumen 5.2 supported?

### ISSUE THREAD

**Issue by jfoliveira** [DarkaOnLine/L5-Swagger#11]
Hi,
Is this package supposed to work with Lumen - specially 5.2?

After install the package and register the service provider, I got this error when running `php artisan`:
```
PHP Fatal error:  Call to undefined function Darkaonline\L5Swagger\config_path()
in /vendor/darkaonline/l5-swagger/src/L5SwaggerServiceProvider.php on line 34
```

I don't built APIs in Laravel, only in Lumen, as APIs usually don't need most of Laravel specific stuff - I guess that's what Lumen was built for.

Any advice on how to get it working with Lumen?
If this package doesn't aim to support Lumen that's fine. I would appreciate if you could point me to any other package that integrates Swagger with Lumen.

Thanks!

**Comment by DarkaOnLine** [comment]
Hi, @jfoliveira 

Take a look at this one: https://github.com/DarkaOnLine/SwaggerLume

**Comment by jfoliveira** [comment]
@DarkaOnLine Wow! That's great! Fair play to you! :+1: 
I'll check it out right now.
