### ISSUE TITLE
Unable to pass params in formData during post request

### ISSUE THREAD

**Issue by ankitjain28may** [DarkaOnLine/L5-Swagger#111]
- L5-Swagger Version: 5.5.* (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.1
- OS: Ubuntu 16.04 LTS

### Description:
I am unable to pass params in formData during post request, Its unable to data.

### Steps To Reproduce:
I am trying to send data through this given way but it shows null in the controller.

```
@SWG\Parameter(
     *       name="email",
     *       in="formData",
     *       description="Email of the company",
     *       required=true,
     *       type="string",
     *       @SWG\Items(type="string")
     *   ),
```

**Comment by DarkaOnLine** [comment]
Please see Swaggers documentation. It looks like this is not related to the package. Here is an example how to write post: https://github.com/zircote/swagger-php/blob/master/Examples/petstore.swagger.io/controllers/PetController.php#L130

**Comment by ankitjain28may** [comment]
@DarkaOnLine  Thanks, Problem is solved now.. My Apologies :smile:

**Comment by thhan** [comment]
@ankitjain28may can you please post your example?

**Comment by ankitjain28may** [comment]
@thhan Sure, Here it is--
```
* @SWG\Post(
     *   path="/api/company",
     *   summary="Register the company",
     *   tags={"Company"},
     *   description="Register the company",
     *   operationId="store",
     *   consumes={"multipart/form-data"},
     *   produces={"application/json"},
     * @SWG\Parameter(
     *         name="Authorization",
     *         in="header",
     *         required=true,
     *         type="string"
     *     ),
     * @SWG\Parameter(
     *       name="company_name",
     *       in="formData",
     *       description="Company Name",
     *       required=true,
     *       type="string",
     * @SWG\Items(type="string")
     *   ),
```

**Comment by ahsanmster** [comment]
isn't @SWG the older version? any example with `@OA\Post` ? @ankitjain28may
