### ISSUE TITLE
externalDocs is not available??

### ISSUE THREAD

**Issue by luisferparra** [DarkaOnLine/L5-Swagger#113]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):
- OS:

### Description:
Hi, congratulations for the package. It works great. But I cannot find how to insert the externalDocs into the final doc. Is there any way??

thanks

**Comment by DarkaOnLine** [comment]
What kind of external docs are you referring to? Do you want to merge some kind of external json file/string to generated one?

**Comment by luisferparra** [comment]
Thanks.

I want to include additional information about a documentation. I am not pretty sure if it is available for the version 2.0, but sure for the openApi 3.0. I've used it in the 2.0 version and it works.

Swagger documentation:
https://swagger.io/specification/#externalDocumentationObject

You must include:

externalDocs:
  description: Manual uso Api (cliente)
  url: https://dev.netsales.es/stat-server/swagger/manual/



It is like a external reference. You can see how it is displayed here:

http://ws-server.netsales.es/swagger/

Thanks

**Comment by DarkaOnLine** [comment]
I found that Swagger-php supports this: https://github.com/zircote/swagger-php/blob/master/Examples/petstore.swagger.io/tags.php#L7-L10

So you should be able to declare your external docs.

**Comment by luisferparra** [comment]
Thanks a Lot. It looks great.

**Comment by DarkaOnLine** [comment]
👍 Let me know if you succeded.

**Comment by luisferparra** [comment]
Hi
Yes it works perfectly. Inside the Tag as the documentation you sent me and Outside the tag a as global api information. Both works

 *   @SWG\ExternalDocumentation(
 *     description="Find out of this Api",
 *     url="http://swagger.io"
 *   )



 * @SWG\Tag(
 *   name="pet",
 *   description="Everything about your Pets",
 *   @SWG\ExternalDocumentation(
 *     description="Find out more about Pets",
 *     url="http://swagger.io"
 *   )
 * )

**Comment by DarkaOnLine** [comment]
Nice, glad you succeeded! 🎉

**Comment by DarkaOnLine** [comment]
OpenApi 3.0 is now supported https://github.com/DarkaOnLine/L5-Swagger/commit/99ec1c855577fe4cc4cd987f4625ae35ee39a297

How to: https://github.com/DarkaOnLine/L5-Swagger#using-openapi-30-specification
