### ISSUE TITLE
Swagger UI bundle Error - SyntaxError: expected expression, got '<' 

### ISSUE THREAD

**Issue by zcodevthoma** [DarkaOnLine/L5-Swagger#114]
- L5-Swagger Version:"darkaonline/swagger-lume": "5.5.*",
- PHP Version 7.0.4
- OS:

got the issue after composer update

Source map error: SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 2226814 of the JSON data
Resource URL: http:/IP/Trunk/Api/public/swagger-ui-assets/swagger-ui-standalone-preset.js?v=447271350
Source Map URL: swagger-ui-standalone-preset.js.map

**Comment by DarkaOnLine** [comment]
Where are you getting this error? In browser console?

**Comment by zcodevthoma** [comment]
yes, i got this in browser console

**Comment by DarkaOnLine** [comment]
You are using LUMEN not Laravel here and `swagger-lume` package not L5-Swagger :)

Please open the ticket in the correct repository. But I tested now fresh installation and everything works as it should.

Could you open your file `http:/IP/Trunk/Api/public/swagger-ui-assets/swagger-ui-standalone-preset.js? ` in the browser and see it's content?

**Comment by zcodevthoma** [comment]
sure i will open in lumen repo..

yes i checked the file in browser,
