### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by CrixuAMG** [DarkaOnLine/L5-Swagger#115]
When I tried upgrading to Laravel 5.6 I saw that L5-Swagger has a hard restraint on the Laravel version being installed. So my question is, when can we upgrade to Laravel 5.6? 
And would it be possible to get a more useful exception message when there is an error parsing the docblock? Such as 'Unexpected comma near ...'.

**Comment by sheidin** [comment]
Same issue here. 
Can't upgrade to 5.6 because of requirements

**Comment by DarkaOnLine** [comment]
Published new 5.6.0 release: https://github.com/DarkaOnLine/L5-Swagger/releases/tag/5.6.0
