### ISSUE TITLE
Is possible add a Theme into this repo ?

### ISSUE THREAD

**Issue by felipemarques** [DarkaOnLine/L5-Swagger#12]
HI @DarkaOnLine ,

I would like know, if i can make a pull request to this repo for add a bootstrap theme ?

Thanks!

**Comment by DarkaOnLine** [comment]
Hi

Yes of course. But I think it should be optional and the users should be able to change it in the config by changing the theme name. The theme should also have all possible config options like original has. 

Looking forward to see the results
