### ISSUE TITLE
Middleware issue with Laravel 5.6

### ISSUE THREAD

**Issue by ollakalla** [DarkaOnLine/L5-Swagger#122]
- L5-Swagger Version: 5.6.2
- PHP Version: 7.1.14
- OS: ubuntu

### Description:
i want to protect api path http://localhost:8000/api/documentation and make only authenticated user to access it, but when i make authentication and try to access the api path, i get redirect to homepage of website as i'm not authenticated, the \Auth::id() is empty i don't know why
### Steps To Reproduce:

i have added auth middleware to middleware section in config/l5-swagger.php
```
'middleware' => [
    'api' => ['auth'],
    'asset' => [],
    'docs' => [],
    'oauth2_callback' => [],
    ],
```
and run `php artisan config:cache ` to clear the cache, 
Then logged in and try to access  http://localhost:8000/api/documentation, but i have redirect to homepage.

**Comment by DarkaOnLine** [comment]
You should use 

```php
'api' => ['web', 'auth'],
```

**Comment by ShkAdnan** [comment]
'middleware' => [
                'api' => ['web' , 'auth'],
                'asset' => [],
                'docs' => [],
                'oauth2_callback' => [],
            ],
            
           Still redirecting to login page why?

**Comment by ShkAdnan** [comment]
my function

public function check(Request $request){
        
        //Validation
        $this->validate($request , [
            'email' => 'required|max:255',
            'password' => 'required|max:255'
        ]);
        
        $credentials = $request->only('email', 'password');

        if (Auth::attempt($credentials)) {
            $request->session()->regenerate();
            
            return redirect()->route('swagger');
        }
    }
