### ISSUE TITLE
Config and view files cannot be published

### ISSUE THREAD

**Issue by jualoppaz** [DarkaOnLine/L5-Swagger#125]
- L5-Swagger Version (`composer show | grep l5-swagger`): 5.6.2 
- PHP Version (`php -v`): 7.1.9
- OS: Windows 8.1

### Description:

I tried to publish the l5-swagger.php config and the view files with command  

> php artisan vendor:publish --provider 'L5Swagger\L5SwaggerServiceProvider'

but they are never published although "Publising complete" message is printed.

I can reproduce this issue with **Laravel 5.6.7** and **L5-Swagger 5.6.2**.

However, with previous versions like **Laravel 5.5.26** and **L5-Swagger 5.5.2** I had no problem.

I reviewed the writing permissions for config folder but it doesn't seem to be the reason.

By the moment I copied manually both files from the package to my project and I can customize the same things.

Any idea?

### Steps To Reproduce:

1. Install the package: php composer require "darkaonline/l5-swagger:5.6.*"
2. Publish the files: php artisan vendor:publish --provider 'L5Swagger\L5SwaggerServiceProvider'
3. Printed message: "Publishing complete."
4. No files are published: **l5-swagger.php** either **index.blade.php**

**Comment by DarkaOnLine** [comment]
@jualoppaz tried to reproduce your problem but with no luck :(

![provider-publish](https://user-images.githubusercontent.com/1171698/37018699-ffd3add8-211d-11e8-8212-240f26c31f98.png)

What do you see if you run `php artisan vendor:publish` command?

**Comment by jualoppaz** [comment]
Hi @DarkaOnLine ! Thank you for your answer.

I executed the command you mention and I saw an extrange behaviour:

![comando vendor-publish](https://user-images.githubusercontent.com/5088244/37019408-791859ba-2118-11e8-88bf-f93b9e7ec010.png)

If I execute the command 

> php artisan vendor:publish --provider 'L5Swagger\L5SwaggerServiceProvider'

no L5-Swagger files are published. As you can see "Publishing complete" is the unique printed message.

However, If I execute the command

> php artisan vendor:publish

and pick the option number 6, the L5-Swagger service provider, I can generate the config files and see the "Copied Directory [ ..." messages for **l5-swagger.php** and **index.blade.php**.

I didn't add the provider explicitly in **config/app.php** because the discovery feature might load it automatically.

Can this be an issue of Laravel?

**Comment by DarkaOnLine** [comment]
I see you are using window's. Can you try this:

`php artisan vendor:publish --provider 'L5Swagger\\L5SwaggerServiceProvider' `

**Comment by jualoppaz** [comment]
Hi again!

I guessed the solution. This problem can be solved modifying the --provider option like this:

> php artisan vendor:publish --provider="L5Swagger\\L5SwaggerServiceProvider"

Pay atention to equal sign and double quotes.

May be that syntax without equal does not work in Windows?

**Comment by DarkaOnLine** [comment]
Yes, this is Window.

**Comment by mgip** [comment]
php artisan vendor:publish --provider="L5Swagger\L5SwaggerServiceProvider" Works, but not for the ServiceProvider.

I need to publish the ServiceProvider for use gate() Method and prevent the access to UI like Laravel Horizon method.

The thing is that i need access to Session data on this process, and via Middleware is not working, then i will try to use the protected function gate() of L5SwaggerServiceProvider with Gate::define()...

I am going well ??

Anyone figure out this?

Thanks.
