### ISSUE TITLE
Tip: add some more info in Readme about how to annotate and generate

### ISSUE THREAD

**Issue by paulhuisman** [DarkaOnLine/L5-Swagger#126]
There are lots of questions about annotating and generating swagger documentation.

Maybe you can add a small bit in the readme about this.

I imagine 2-3 lines would be of great help to a lot of people.

**Comment by DarkaOnLine** [comment]
@paulhuisman PR's are always welcome.

How to use swagger annotations is out of this package scope, but if you can write several lines about it, please make a PR and I will consider it.

**Comment by paulhuisman** [comment]
OK!

**Comment by paulhuisman** [comment]
https://github.com/DarkaOnLine/L5-Swagger/pull/127
