### ISSUE TITLE
Ambiguous class resolution

### ISSUE THREAD

**Issue by herzcthu** [DarkaOnLine/L5-Swagger#128]
- L5-Swagger Version: 5.6.3
- PHP Version : PHP 7.1.4-1+deb.sury.org~xenial+1 (cli) (built: Apr 11 2017 22:12:32) ( NTS )

- OS: Ubuntu

### Description:
I'm getting this warning from composer after installing L5-Swagger in laravel lumen.
`Warning: Ambiguous class resolution, "Cron\MinutesField" was found in both "/var/www/zipcode/vendor/mtdowling/cron-expression/src/Cron/MinutesField.php" and "/var/www/zipcode/vendor/dragonmantank/cron-expression/src/Cron/MinutesField.php", the first will be used.
Warning: Ambiguous class resolution, "Cron\CronExpression" was found in both "/var/www/zipcode/vendor/mtdowling/cron-expression/src/Cron/CronExpression.php" and "/var/www/zipcode/vendor/dragonmantank/cron-expression/src/Cron/CronExpression.php", the first will be used.
Warning: Ambiguous class resolution, "Cron\HoursField" was found in both "/var/www/zipcode/vendor/mtdowling/cron-expression/src/Cron/HoursField.php" and "/var/www/zipcode/vendor/dragonmantank/cron-expression/src/Cron/HoursField.php", the first will be used.
Warning: Ambiguous class resolution, "Cron\DayOfMonthField" was found in both "/var/www/zipcode/vendor/mtdowling/cron-expression/src/Cron/DayOfMonthField.php" and "/var/www/zipcode/vendor/dragonmantank/cron-expression/src/Cron/DayOfMonthField.php", the first will be used.
Warning: Ambiguous class resolution, "Cron\FieldFactory" was found in both "/var/www/zipcode/vendor/mtdowling/cron-expression/src/Cron/FieldFactory.php" and "/var/www/zipcode/vendor/dragonmantank/cron-expression/src/Cron/FieldFactory.php", the first will be used.
Warning: Ambiguous class resolution, "Cron\AbstractField" was found in both "/var/www/zipcode/vendor/mtdowling/cron-expression/src/Cron/AbstractField.php" and "/var/www/zipcode/vendor/dragonmantank/cron-expression/src/Cron/AbstractField.php", the first will be used.
Warning: Ambiguous class resolution, "Cron\MonthField" was found in both "/var/www/zipcode/vendor/mtdowling/cron-expression/src/Cron/MonthField.php" and "/var/www/zipcode/vendor/dragonmantank/cron-expression/src/Cron/MonthField.php", the first will be used.
Warning: Ambiguous class resolution, "Cron\DayOfWeekField" was found in both "/var/www/zipcode/vendor/mtdowling/cron-expression/src/Cron/DayOfWeekField.php" and "/var/www/zipcode/vendor/dragonmantank/cron-expression/src/Cron/DayOfWeekField.php", the first will be used.
Warning: Ambiguous class resolution, "Cron\FieldInterface" was found in both "/var/www/zipcode/vendor/mtdowling/cron-expression/src/Cron/FieldInterface.php" and "/var/www/zipcode/vendor/dragonmantank/cron-expression/src/Cron/FieldInterface.php", the first will be used.`

### Steps To Reproduce:

use this composer config and install
```json
{
    "name": "laravel/lumen",
    "description": "The Laravel Lumen Framework.",
    "keywords": ["framework", "laravel", "lumen"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.1.3",
        "darkaonline/l5-swagger": "5.6.*",
        "laravel/lumen-framework": "5.6.*",
        "league/csv": "^9.1",
        "vlucas/phpdotenv": "~2.2"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "phpunit/phpunit": "~7.0",
        "mockery/mockery": "~1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/",
            "database/"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by DarkaOnLine** [comment]
Where is nothing related to the package in you error message. Problem is in other packages which are not even listed in you composer.json example...
