### ISSUE TITLE
Controller Specific Sections In UI

### ISSUE THREAD

**Issue by lbarbula** [DarkaOnLine/L5-Swagger#129]
- L5-Swagger Version:  5.4.0
- PHP Version: 7.1.7
- OS: macOS High Sierra

### Description:
I have a general question on how to delineate resources. I want each controller to have it's own section that can be expanded to show the methods contained therein. I feel like this is probably a config change for paths, but I can't seem to find any documentation. The closest that I found was the resource annotation which has been deprecated. Any help is greatly appreciated!

### Steps To Reproduce:
I have not been able to define any methods that are not simply under the default header. I have not been able to produce the desired behavior.

**Comment by DarkaOnLine** [comment]
You need to use TAGS, to group endpoints:

https://github.com/DarkaOnLine/L5-Swagger/blob/master/tests/storage/annotations/Swagger/Anotations.php#L33

**Comment by lbarbula** [comment]
Awesome, thank you!
