### ISSUE TITLE
Security definition and the header name have to be the same.

### ISSUE THREAD

**Issue by TheWildHorse** [DarkaOnLine/L5-Swagger#13]
Currently, when you open up the Swagger UI, the apiKey that gets added has to have the same securityDefinition name and header name for it to work. This is due to this line https://github.com/DarkaOnLine/L5-Swagger/blob/master/resources/views/index.blade.php#L72.

` window.authorizations.add('{{$apiKeyVar}}', new ApiKeyAuthorization('{{$apiKeyVar}}', key, "{{$apiKeyInject}}"));` 

The first place where {{$apiKeyVar}} is used, this place should hold the securityDefinition name (key of the securityDefinition in the swagger.json file), and the first argument of the ApiKeyAuthorization constructor should be the header that the key is sent in. The only way to insure it is to change the securityDefinition name to be the name of the header you are sending your key with.

This is confusing and should be fixed with an additional config parameter or at least documented. I will submit a pull request if you feel this should be fixed.

**Comment by DarkaOnLine** [comment]
Implemented on 3.0
