### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by mobeen7asif** [DarkaOnLine/L5-Swagger#131]
I want to create response model using this package 
Following is not working

   /**
     * @OAS\Property(
     *     description="user_name",
     *     title="user_name",
     * )
     *
     * @var string
     */

**Comment by DarkaOnLine** [comment]
It is working correctly. You forgot Schema:

```php
<?php

namespace App\Api\Models;

/**
 * @OAS\Schema(
 *     title="PaymentType",
 *     type="object"
 * )
 */
class PaymentType
{
    /**
     * @OAS\Property(format="integer")
     *
     * @var int
     */
    public $id;

    /**
     * @OAS\Property(format="string")
     *
     * @var string
     */
    public $name;
}
```

I am not sure, but I think `@OAS` should be uppercase also.
