### ISSUE TITLE
Getting Required @SWG\Info() not found when running php artisan l5-swagger:generate

### ISSUE THREAD

**Issue by iturcanu** [DarkaOnLine/L5-Swagger#132]
- L5-Swagger Version: 3.0
- PHP Version (`php -v`): 7.2.2
- OS: Ubuntu 16

### Description:
Getting Required @SWG\Info() not found when running php artisan l5-swagger:generate
at /vendor/zircote/swagger-php/src/Logger.php: 38
          $this->log = function ($entry, $type) {
                 if ($entry instanceof Exception) {
                 $entry = $entry->getMessage();
               }
             trigger_error($entry, $type);
            };
        }

**Comment by naffan2014** [comment]
how solved?

**Comment by DarkaOnLine** [comment]
https://github.com/DarkaOnLine/L5-Swagger/issues?utf8=%E2%9C%93&q=SWG%5CInfo

**Comment by ionTurcanu** [comment]
Hi,
I wasn't declaring the piece
/**
 * @SWG\Info(title="Project API", version="1")
 */

This needs to be declared once, in a controller you want
