### ISSUE TITLE
Documentation no https support

### ISSUE THREAD

**Issue by xiao345** [DarkaOnLine/L5-Swagger#133]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):
- OS:

### Description:
When I deploy my swagger document to product environment. The page is blocked. The console point out: 
```
Mixed Content: The page at 'https://api.xxx.com/api/documentation' was loaded over HTTPS, but requested an insecure stylesheet 'http://api.xxx.com/docs/asset/swagger-ui.css?v=51575f17702d3be464ebf20621381a0d'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by DarkaOnLine** [comment]
https is supported, I think you defined your APP_URL without https and this is why assets link is constructed without it.

**Comment by xiao345** [comment]
Sorry, is my problem.
