### ISSUE TITLE
Versioning Swagger Api

### ISSUE THREAD

**Issue by oyepez003** [DarkaOnLine/L5-Swagger#136]
Hi guys, I need to know how to define different versions in the Swagger Documentation from the same Project...

Is this possible?

Thanks.

**Comment by elightbo** [comment]
I'm wondering if this is possible as well.

**Comment by tsanjoto** [comment]
same here, is it possible to attach certain API to specific version? or have l5-swagger.php to have different api pages that links to different docs_json to achieve different api version?

**Comment by DarkaOnLine** [comment]
This will be implemented in #270
