### ISSUE TITLE
Missing assets on test environment on swagger page

### ISSUE THREAD

**Issue by paulhuisman** [DarkaOnLine/L5-Swagger#137]
- L5-Swagger Version: 5.6.3 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.1.16
- OS: Macos Sierra 10.12.6

### Description:
OK, there have been quite a bit of issues posted yet about this problem, but none of them offered a solution to me. 

On my local environment l5-swagger works great (on /api/documentation) but when i deploy the project to a test environment (nginx) i'm getting 404 errors on the assets (docs/asset/swagger-ui.css, docs/asset/swagger-ui-bundle.js etc.). I tried adjusting my nginx conf for assets but no luck..

How are these docs/asset files generated? If i know how maybe i can debug this better.

**Comment by DarkaOnLine** [comment]
This function forms asset url: https://github.com/DarkaOnLine/L5-Swagger/blob/master/src/helpers.php#L53

And controller action responsible for serving asset is here: https://github.com/DarkaOnLine/L5-Swagger/blob/master/src/Http/Controllers/SwaggerAssetController.php#L10

**Comment by paulhuisman** [comment]
Thx, will check it out.

**Comment by paulhuisman** [comment]
It seems my assets are available but the test environment:
```

ubuntu@ip-172-31-20-243:/var/www/ph-site/builds/Build.release-35.23-04-2018-15-32/vendor/swagger-api/swagger-ui/dist$ ls -alh
total 19M
drwxrwxr-x 2 bamboo bamboo 4.0K Mar  3 05:13 .
drwxrwxr-x 9 bamboo bamboo 4.0K Apr 23 14:47 ..
-rw-rw-r-- 1 bamboo bamboo  445 Mar  3 05:13 favicon-16x16.png
-rw-rw-r-- 1 bamboo bamboo 1.2K Mar  3 05:13 favicon-32x32.png
-rw-rw-r-- 1 bamboo bamboo 3.5K Mar  3 05:13 index.html
-rw-rw-r-- 1 bamboo bamboo 2.4K Mar  3 05:13 oauth2-redirect.html
-rw-rw-r-- 1 bamboo bamboo 1.5M Mar  3 05:13 swagger-ui-bundle.js
-rw-rw-r-- 1 bamboo bamboo  11M Mar  3 05:13 swagger-ui-bundle.js.map
-rw-rw-r-- 1 bamboo bamboo 150K Mar  3 05:13 swagger-ui.css
-rw-rw-r-- 1 bamboo bamboo   91 Mar  3 05:13 swagger-ui.css.map
-rw-rw-r-- 1 bamboo bamboo 354K Mar  3 05:13 swagger-ui.js
-rw-rw-r-- 1 bamboo bamboo 2.2M Mar  3 05:13 swagger-ui.js.map
-rw-rw-r-- 1 bamboo bamboo 431K Mar  3 05:13 swagger-ui-standalone-preset.js
-rw-rw-r-- 1 bamboo bamboo 3.0M Mar  3 05:13 swagger-ui-standalone-preset.js.map
```

However the 'symlink' from docs/assets doesn't seem to work.

**Comment by DarkaOnLine** [comment]
Could it be that nginx thinks that 'docs/assets' is a directory but not a route?

**Comment by paulhuisman** [comment]
Fixed, was a rule in the nginx conf concerning css/json that messed it up.
