### ISSUE TITLE
Disable swagger on prod

### ISSUE THREAD

**Issue by paulhuisman** [DarkaOnLine/L5-Swagger#139]
- L5-Swagger Version: 5.6.4 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.1
- OS: High Sierra

### Description:
Is it possible to disable swagger on production? Maybe based on a .env variable?

**Comment by DarkaOnLine** [comment]
By default l5-swagger is not generating swagger documentation file. So API documentation page should be blank. If you see documentation it means you are inculding api json file in your version control or  `L5_SWAGGER_GENERATE_ALWAYS` is set to TRUE.

Check your `.env` file for `L5_SWAGGER_GENERATE_ALWAYS` ir should be set to `FALSE` in production and also delete your `api-docs.json` file from version control and also from file system.

**Comment by paulhuisman** [comment]
Thx!

**Comment by sboo** [comment]
I have the same issue.  L5_SWAGGER_GENERATE_ALWAYS  but definitely set to false, but if storage/api-docs/api-docs.json is not preset at all, it will be generated. Only if I put an empty file there, the swagger-ui wil load but will complain that no api documentation is present.

**Comment by DarkaOnLine** [comment]
You can use midlewares to disable access to the swagger ui

**Comment by sboo** [comment]
Yeah that's what I figured to do indeed

**Comment by sadhakbj** [comment]
How can i completely remove the route as well. Displaying of the blank screen is not a solution for me. I want to display 404 page in case of production.

**Comment by thomasgit123** [comment]
in version 2.0,  It's still generating api-docs.json file when I disable autogenerate and remove api-docs.json file on production, 
how can I disable swagger router in production totally?

**Comment by tiaguinhor** [comment]
> in version 2.0, It's still generating api-docs.json file when I disable autogenerate and remove api-docs.json file on production,
> how can I disable swagger router in production totally?

The same as me, I'm using `"darkaonline/l5-swagger": "^6.0"` and OpenApi 3.0
