### ISSUE TITLE
Generate api-docs as yaml

### ISSUE THREAD

**Issue by unkndono** [DarkaOnLine/L5-Swagger#140]
- L5-Swagger Version: 5.6.*
- PHP Version: 7.2
- OS: Windows 10
- Swagger Version : OpenAPI 
### Description:
Actually, the generation process creates a  json file named api-docs.json

Is there a way to generate this as yaml ?
I got other tools that need to consume this file, but they only accept yaml format.

**Comment by DarkaOnLine** [comment]
Where was discussion here about yalm support: https://github.com/DarkaOnLine/L5-Swagger/issues/69 , but sadly no one contributed to it :(

If you are willing to try it would be grate.
