### ISSUE TITLE
Missing authorize button after L5-Swagger version update 

### ISSUE THREAD

**Issue by sheidin** [DarkaOnLine/L5-Swagger#141]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):7.2
- OS:

### Description:
Missing authorize button with new version update. 

### Steps To Reproduce:
Here is my security configurations: 
`'oauth2_security' => [ 
            'type' => 'oauth2', 
            'description' => 'Oauth2 security scheme.',
            'flow' => 'accessCode',
            'authorizationUrl' =>  env('APP_FULL_URL', '').'/oauth/authorize', 
            'tokenUrl' => env('APP_FULL_URL', '').'/oauth/token',
            'scopes' => [
                "default" => "Your default user permissions",
            ]
        ],
`
This issue came after version update. 
Any ideas? 

Thanks,
Ilya

**Comment by DarkaOnLine** [comment]
Which version are you using?
Is api-docs.json file generated/regenerated? Can you see authorization in it?

**Comment by sheidin** [comment]
Dear DarkaOnLine,

First of all thank you for your reply! 
I've used "5.5.4" and now I'm on "5.6.*".
As for the api-docs.json I do see my oauth2_security in securitySchemes

**Comment by DarkaOnLine** [comment]
I think your Auth2 flow is wrong (`'flow' => 'accessCode'`).  

`accessCode` is now renamed to: `authorizationCode`

https://swagger.io/docs/specification/authentication/oauth2/

**Comment by sheidin** [comment]
Not helped. 
But I've changed 'swagger_version' to '2.0' and now button returned. 

Thanks!
