### ISSUE TITLE
blank page is coming on access the /api/documentation

### ISSUE THREAD

**Issue by flik** [DarkaOnLine/L5-Swagger#142]
- L5-Swagger Version: 5.4.*  (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): PHP 7.2.3-1ubuntu1 
- OS: Linux Ubuntu

### Description:
I can create the document by: 
php artisan l5-swagger:generate
Regenerating docs

when I try to access it in browser blank page is coming.

### Steps To Reproduce:
generate the document by command:
php artisan l5-swagger:generate

check in browser:
http://exmple.com/api/documentation

**Comment by DarkaOnLine** [comment]
are you using apache or nginx?

**Comment by flik** [comment]
apache

**Comment by DarkaOnLine** [comment]
do you see any errors in browser console? It looks like your assets are not leaded.

**Comment by flik** [comment]
When I try to access any asset like css file. It is showing 404 error.  
http://xxxxx.com/docs/asset/favicon-16x16.png
http://xxxxx.com/docs/api-docs.json

both are showing 404 Not Found

**Comment by DarkaOnLine** [comment]
So something is blocking `/docs/*`  routes. Look at your other routes. This is your project specific problem :(

**Comment by flik** [comment]
I have checked the same code is working on windows system and when I deploy it on linux amazone then This issue is coming.

**Comment by DarkaOnLine** [comment]
It's either apache miss configuration or project related. Sorry but I can't help here without seeing anything :(

**Comment by flik** [comment]
nginx/1.13.9 is using on my server. Where I am getting issue.

**Comment by DarkaOnLine** [comment]
Look in these related issues to nginx:

https://github.com/DarkaOnLine/L5-Swagger/issues/137
https://github.com/DarkaOnLine/L5-Swagger/issues/75

**Comment by flik** [comment]
I have fixed the issue with these steps. here is detail link: https://stackoverflow.com/questions/51448899/swagger-does-not-publish-assets-files-in-laravel-5-6/52496448#52496448
