### ISSUE TITLE
auth:api protected routes are allowed to be called with no authentication from Swagger UI

### ISSUE THREAD

**Issue by mattkoch614** [DarkaOnLine/L5-Swagger#143]
- L5-Swagger Version: 5.6.4
- PHP Version 7.2
- OS: Ubuntu

### Description:
Swagger UI does not require enforce authentication for protected routes. The "Try it Out" button returns results, even when the route is protected in routes/api.php with ``->middleware('auth:api')`` I am currently using Laravel Passport for API authentication.

### Steps To Reproduce:

* Set up ``config/l5-swagger.php`` with ``passport`` authentication in the ``security`` key.
* Ensure the route you are accessing is protected with the ``auth:api`` middleware.
* Generate Swagger UI docs
* Attempt to access the controller method via Swagger UI with no authentication. Note the 200 response code.

**Comment by DarkaOnLine** [comment]
But this is not related to swagger. If your backend allows accessing url you should look into it, but not into swagger.

**Comment by dankinchen** [comment]
> * L5-Swagger Version: 5.6.4
> * PHP Version 7.2
> * OS: Ubuntu
> 
> ### Description:
> Swagger UI does not require enforce authentication for protected routes. The "Try it Out" button returns results, even when the route is protected in routes/api.php with `->middleware('auth:api')` I am currently using Laravel Passport for API authentication.
> 
> ### Steps To Reproduce:
> * Set up `config/l5-swagger.php` with `passport` authentication in the `security` key.
> * Ensure the route you are accessing is protected with the `auth:api` middleware.
> * Generate Swagger UI docs
> * Attempt to access the controller method via Swagger UI with no authentication. Note the 200 response code.

Did you ever figure this out? It does it to me as well.
