### ISSUE TITLE
Constants seem to cause an issue with `Try it now` section

### ISSUE THREAD

**Issue by elightbo** [DarkaOnLine/L5-Swagger#144]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`): 5.6.4
- PHP Version (`php -v`): 7.2.3
- OS: Ubuntu 16.04

### Description:
When using OAS 3, the server url is duplicated in the `Try it now` requests. For example:

Use the constant `SWAGGER_DOMAIN` in the constants section of `l5-swagger.php`.  When that constant is used in the `Server` section like:

```
 * @OAS\Server(
 *   url=SWAGGER_DOMAIN
 * )
```
The curl request generated for `Try it now` is something like `curl -X GET "http://my-api.localmy-api.local/api/users/" -H  "accept: */*" -H  "X-CSRF-TOKEN: "`

The url gets generated just fine for the server dropdown at the top of the page.

**Comment by DarkaOnLine** [comment]
That is the value of `SWAGGER_DOMAIN`

**Comment by elightbo** [comment]
In the example SWAGGER_DOMAIN was set to `my-api.local` rather than `http://my-api.local`. Once I switched to the full URL it all worked beautifully. Ooops :(
