### ISSUE TITLE
L5_SWAGGER_CONST_HOST used by the swagger ui input ? 

### ISSUE THREAD

**Issue by unkndono** [DarkaOnLine/L5-Swagger#145]
- L5-Swagger Version: 5.6.4
- PHP Version: 7.2.4
- OS: docker on windows 10 

### Description:
Hello there, 
Is there a way for you to set the $('input.download-url-input') of the swagger-ui on  L5_SWAGGER_CONST_HOST value (or another env) ? 

My problem is that i'm hosting a project in multiple docker containers on a [Rancher ](https://rancher.com/) + aws 
I got a api proxy ([Gravitee](https://gravitee.io/)) in front of this project. The swagger ui seems to retrieve the host from the container and not the proxy.  I potentially need to emulate this value

Can you guide me ? 
I saw that you have a 'proxy' key in the config file, could you explain how it works ?

**Comment by DarkaOnLine** [comment]
The URL is set here: https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php#L29

So you can change it as you wish. By using ENV variables or by hardcoding it.

**Comment by unkndono** [comment]
Yeah i found that, but is there a way to define a full url (in my case, another domain)
When i try, i get 'http://localhost:8080/http://testdomain/api-docs.json'  in the input value.

**Comment by DarkaOnLine** [comment]
full url is generated here: https://github.com/DarkaOnLine/L5-Swagger/blob/master/src/Http/Controllers/SwaggerController.php#L56

It uses `route()` function. So I think you have to define  APP_URL in your .env file as `http://testdomain` and it should work.

**Comment by unkndono** [comment]
i already dit it. but its seems laravel is using the host instead of APP_URL somewhere...

i'm going to investigate on this track
i'll keep you updated

**Comment by unkndono** [comment]
Unfortunatly, Laravel isn't using the value of APP_URL in case of a web request (it's only being used in command line).
I managed to force it in a service provider with :
`app('url')->forceRootUrl(env('APP_URL'));`

This way, my load-balanced input value use the correct value now
