### ISSUE TITLE
OAS 3: ErrorException  : Unexpected field "basePath" for @OAS\OpenApi(), expecting "openapi", "info", "servers", "paths", "components", "tags", "externalDocs", "x" 

### ISSUE THREAD

**Issue by xl32** [DarkaOnLine/L5-Swagger#147]
- L5-Swagger Version: 5.6.4 (`composer show | grep l5-swagger`)
- PHP Version: PHP 7.2.6 (cli) (built: May 22 2018 16:22:08) ( NTS )
- OS: Fedora 27

### Description:
I'm receiving exception on docs generation with OAS 3 and setting L5_SWAGGER_BASE_PATH in env:
OAS 3: ErrorException  : Unexpected field "basePath" for @OAS\OpenApi(), expecting "openapi", "info", "servers", "paths", "components", "tags", "externalDocs", "x" 

### Steps To Reproduce:
1. Set L5_SWAGGER_BASE_PATH=http://example.com/api/v1 in env;
2. Require "zircote/swagger-php": "3.*" in comsposer.json;
3. Generate docs and observe error.

Please also review my proposed fix in PR #146.

**Comment by DarkaOnLine** [comment]
resolved #146
