### ISSUE TITLE
usage with multiple API

### ISSUE THREAD

**Issue by crashmxx** [DarkaOnLine/L5-Swagger#149]
- L5-Swagger Version: 5.6.4
- PHP Version: 7.1.8
- OS: Debian 3.16.43-2+deb8u3

### Description:
Hello, 
thank your for this great library. 
Is there a way to have multiple json file for different api ?
Indeed on my project i have two api (one public and the other one private), i want to use swagger template to switch on the several api with a GET param, but for that i have to generate different json file for each api. Is there a way to do that ? 

thanks for help !
Cheers

**Comment by tsterker** [comment]
@DarkaOnLine Thanks for your thoughts! Maybe one could generalize this problem to supporting multiple API "versions" (however one defines a version).

Glancing at the code I was not able to think of a straight forward way to support
- generating different json files for different namespaces (e.g. `\App\Api\v1` vs. `\App\Api\v2`)
- viewing the documentation for these different versions

Do you have any pointers on that or are there any plans on natively supporting multiple versions?

**Comment by Rivsen** [comment]
I impl a version with separated config:

![image](https://user-images.githubusercontent.com/762701/43555136-08b423d8-962b-11e8-9abb-6a40523a02ab.png)

And every group has there routes:

![image](https://user-images.githubusercontent.com/762701/43555165-336e4914-962b-11e8-9c4c-6f4f9b53ed53.png)

**Comment by Rivsen** [comment]
@DarkaOnLine What do you think about the multiple api implementation in this way: every group could has own config or using global config.

**Comment by justasSendrauskas** [comment]
@DarkaOnLine Just wondering if you are planning to review/merge multiple versions?

**Comment by DarkaOnLine** [comment]
I had started a new branch for this, but now I am absolutely out of time :( If some can make this HUGE work I would definitely review/merge it.

**Comment by justasSendrauskas** [comment]
i see, and the work done by @Rivsen here https://github.com/DarkaOnLine/L5-Swagger/compare/master...rswork:5.4.x-multidoc is not what can be merged straight away?

**Comment by barryvdh** [comment]
Is there a solution for this already?

**Comment by barryvdh** [comment]
Wouldn't an easy solution be to have 1 endpoint, but supply multiple `urls`, based on the current authenticated route / logged in route? And then create multiple definitions based on a path or something?

**Comment by Rivsen** [comment]
I wrote one for laravel 5.4, but not finish compatible the newer version. I need help about this.

> Wouldn't an easy solution be to have 1 endpoint, but supply multiple `urls`, based on the current authenticated route / logged in route? And then create multiple definitions based on a path or something?

That's could not be easy, in my opinion, only doc ui page could using one by loading different doc's json file.

**Comment by Paula2001** [comment]
Howdy !! I want to contribute and add the multi api docs by directory reference and I reached your scanning function and I am stuck there so If you can give me any guidance just  to get through this part anyhow you can reach me on my email : polagorge@gmail.com or on my  phone number +201272575873 call me any time

**Comment by DarkaOnLine** [comment]
Multiple API is coming with #270
