### ISSUE TITLE
OS vs OAS

### ISSUE THREAD

**Issue by drmmr763** [DarkaOnLine/L5-Swagger#152]
- L5-Swagger Version: 5.6.5 (`composer show | grep l5-swagger`)
- SwaggerPHP Version: 3.x-dev 66a1662
- PHP Version (`php -v`): 7.2.6
- OS: OSX / Docker Ubuntu

### Description:
I've set up L5-Swagger per the documentation for Swagger 3.0. My .env for reference:

```
SWAGGER_VERSION=3.0
L5_SWAGGER_GENERATE_ALWAYS=true
L5_SWAGGER_BASE_PATH="http://localhost:8081"
```

I'm a little confused with the differences in documentation with the OA docblock tags vs the OAS docblock tags.

All the documentation on `swagger-php` for the 3.0 branch seems to reference OA:

https://github.com/zircote/swagger-php/blob/3.x/Examples/petstore-3.0/controllers/Pet.php#L18-L33

But in my experience that did not work at all; and in fact I was stuck for a while with this issue:
https://github.com/DarkaOnLine/L5-Swagger/issues?utf8=%E2%9C%93&q=SWG%5CInfo

I knew to use the `info` tag; but I was using the wrong prefix since I was using examples from [swagger-php](https://github.com/zircote/swagger-php/tree/3.x#usage), continually giving me the error about missing the info section. 

Eventually I've discovered that I can do something like this:

```
use Swagger\Annotations as OAS;

/**
 * Class EventApiController
 * @package App\Http\Controllers\Event
 */
class EventApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * @OAS\GET(
     *     path="/events/byDate"
     *     summary="Get a list of events on the specified date"
     *     operationId="listEventsByDate"
     *      @OAS\Parameter(
     *          name="date",
     *          required="true",
     *          in="query"
     *          description="The date to filter the events by."
     *      )
     * )
     *
     * @return \Illuminate\Http\Response
     */
    public function listEventsByDate()
    {
        //
    }
}
```

When I do this my IDE will nicely type-hint to me the proper annotations and all the annotations get parsed properly when I run `php artisan l5-swagger:generate`.

So my questions are:
* is the prefix somehow configurable? OA vs OAS?
* Is this an OpenAPI version thing? 2.0 to 3.0 ?
* Did I miss some important part of configuration or documentation that would have made this less painful for me?

Any tips or pointers on this topic would be greatly appreciated. Thanks!

**Comment by DarkaOnLine** [comment]
Hi,

> is the prefix somehow configurable? OA vs OAS?

No it is not configurable. For OpenApi 3.*, you must use OAS or OA, or like you discovered youd can define short hand as you wish like `use Swagger\Annotations as SH`, 
For <= 2.*, you must use SWG.

> Is this an OpenAPI version thing? 2.0 to 3.0 ?

Yes it is.

> Did I miss some important part of configuration or documentation that would have made this less painful for me?

Did you run command `composer require 'zircote/swagger-php:3.*'` ? This is must if you want to use OpenApi 3.* , but I thing you just forgot `use` statement and thats it :(

Did my answers helped?

**Comment by drmmr763** [comment]
Hi thanks so much for replying, I appreciate you taking the time!

> No it is not configurable. For OpenApi 3., you must use OAS or OA, or like you discovered youd can define short hand as you wish like use Swagger\Annotations as SH,
For <= 2., you must use SWG.

So far, if I try to use anything other than `OAS` I get an error. Here's some tests I just did:

```
# not working
use OpenApi;

/**
 * @OA\Info(
 *     description="This is a sample Petstore server.  You can find
out more about Swagger at
[http://swagger.io](http://swagger.io) or on
[irc.freenode.net, #swagger](http://swagger.io/irc/).",
 *     version="1.0.0",
 *     title="Swagger Petstore",
 *     termsOfService="http://swagger.io/terms/",
 *     @OA\Contact(
 *         email="apiteam@swagger.io"
 *     ),
 *     @OA\License(
 *         name="Apache 2.0",
 *         url="http://www.apache.org/licenses/LICENSE-2.0.html"
 *     )
 * )
 */
```

```
root@5597226c8bde:/home/app# php artisan l5-swagger:generate
Regenerating docs

   ErrorException  : Required @OAS\Info() not found
```

Even using OA as an alias it does not work for me:
```
# not working
use OpenApi as OA;

/**
 * @OA\Info(
 *     description="This is a sample Petstore server.  You can find
out more about Swagger at
[http://swagger.io](http://swagger.io) or on
[irc.freenode.net, #swagger](http://swagger.io/irc/).",
 *     version="1.0.0",
 *     title="Swagger Petstore",
 *     termsOfService="http://swagger.io/terms/",
 *     @OA\Contact(
 *         email="apiteam@swagger.io"
 *     ),
 *     @OA\License(
 *         name="Apache 2.0",
 *         url="http://www.apache.org/licenses/LICENSE-2.0.html"
 *     )
 * )
 */
```

```
root@5597226c8bde:/home/app# php artisan l5-swagger:generate
Regenerating docs

   ErrorException  : Required @OAS\Info() not found
```

It appears the only situation where it works is if I use OAS in the docblock. The alias is optional but it makes the typehinting work. 

```
# works
use OpenApi;

# use OpenApi as OAS also works and does typehinting

/**
 * @OAS\Info(
 *     description="This is a sample Petstore server.  You can find
out more about Swagger at
[http://swagger.io](http://swagger.io) or on
[irc.freenode.net, #swagger](http://swagger.io/irc/).",
 *     version="1.0.0",
 *     title="Swagger Petstore",
 *     termsOfService="http://swagger.io/terms/",
 *     @OAS\Contact(
 *         email="apiteam@swagger.io"
 *     ),
 *     @OAS\License(
 *         name="Apache 2.0",
 *         url="http://www.apache.org/licenses/LICENSE-2.0.html"
 *     )
 * )
 */
```

```
root@5597226c8bde:/home/app# php artisan l5-swagger:generate
Regenerating docs
```

===

I'm fine with using the alias and the OAS prefix, I was just fearing that I was somehow not using the 3.0 version or something, which I'm still worried could be the case.

> Did you run command composer require 'zircote/swagger-php:3.*' ? This is must if you want to use OpenApi 3.* , but I thing you just forgot use statement and thats it :(

I did indeed use the `swagger-php:3.*` version. Here's that portion of my composer.json:

```
"require": {
        "php": "^7.1.3",
        "backpack/base": "^0.9.5",
        "barryvdh/laravel-elfinder": "^0.3.12",
        "barryvdh/laravel-ide-helper": "^2.4",
        "darkaonline/l5-swagger": "5.6.*",
        "doctrine/dbal": "^2.7",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0",
        "owen-it/laravel-auditing": "^7.0",
        "spatie/laravel-permission": "^2.12",
        "zircote/swagger-php": "3.*"
    },
```

> Did my answers helped?
Yes! Thank you. I'm still not totally certain that I'm using OpenAPI 3.0 though. When my json does generate, it does seem to indicate 3.0, though. Is there any way I can confirm? Maybe I should `composer remove` and re-run the require commands to see if that changes anything?

**Comment by DarkaOnLine** [comment]
Your installation is OK and you are using OpenApi 3.0

I thought that class alias should work, my bad here, sorry. But in the latest swagger-php I see that you should be able to alias: https://github.com/zircote/swagger-php/commit/1504d4e7166b2b27980a00fe0605f68a9da7c035#diff-34fffd31113d8e929d097da78b3f5d58R47 . I need to look into this deeper.

**Comment by DarkaOnLine** [comment]
Alos it looks like in the future we will have to use `@OA` not a `@OAS` prefix :(

**Comment by DarkaOnLine** [comment]
Fixed https://github.com/DarkaOnLine/L5-Swagger/commit/691b393085015434bd43e4768812d5937564c145

**Comment by w594533** [comment]
I have the same problem
Here's my solution
For 5.6.x
`composer require "darkaonline/l5-swagger:5.6.*"`
`composer require 'zircote/swagger-php:2.*'`
`php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"`

config .env
`SWAGGER_VERSION=2.0`
