### ISSUE TITLE
Setting body params ContentType:Application/json

### ISSUE THREAD

**Issue by usmanhafeez147** [DarkaOnLine/L5-Swagger#153]
how to write syntax for Swagger form data as JSON format. I tried to find out solution couldn't resolve it.
I tried RequestBody but its not worked for me

` trigger_error("[Semantical Error] The annotation "@Swagger\Annotations\RequestBody\RequestBody" in \App\Http\Controllers\API\AuthController->login() in E:\wamp64\www\splitwise\app\Http\Controllers\API\AuthController.php on line 17 does not exist, or could not be auto-loaded.")`

**Comment by DarkaOnLine** [comment]
Please read the documentation on how to write annotations. This a great start point: https://github.com/zircote/swagger-php/tree/master/Examples

**Comment by ooiginla** [comment]
https://github.com/zircote/swagger-php/blob/master/Examples/example-object/example-object.php
