### ISSUE TITLE
Possible bug on 5.6.8? php artisan l5-swagger:generate fails. Call to undefined function OpenApi\scan()

### ISSUE THREAD

**Issue by kevincobain2000** [DarkaOnLine/L5-Swagger#159]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.1.19
- OS:Debian GNU/Linux 9 

### Description:

Hi, is this a possible bug as I am not able to generate l5 docs after vup from 5.6.7 -> 5.6.8

### Steps To Reproduce:

**5.6.8**

```
# php artisan l5-swagger:generate
Regenerating docs

   Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function OpenApi\scan()

  at /var/www/proj/vendor/darkaonline/l5-swagger/src/Generator.php:117
    113|      */
    114|     protected function scanFilesForDocumentation()
    115|     {
    116|         if ($this->isOpenApi()) {
  > 117|             $this->swagger = \OpenApi\scan(
    118|                 $this->appDir,
    119|                 ['exclude' => $this->excludedDirs]
    120|             );
    121|         }

  Exception trace:

  1   L5Swagger\Generator::scanFilesForDocumentation()
      /var/www/proj/vendor/darkaonline/l5-swagger/src/Generator.php:66

  2   L5Swagger\Generator::generateDocs()
      /var/www/proj/vendor/darkaonline/l5-swagger/src/Console/GenerateDocsCommand.php:32

  Please use the argument -v to see more details.
```

**5.6.7**

```
  - Updating darkaonline/l5-swagger (5.6.8 => 5.6.7): Loading from cache
```

All good

```
root@e7e0dc7da41f:/var/www/proj# php artisan l5-swagger:generate
Regenerating docs
```

**Comment by DarkaOnLine** [comment]
Are you using OpenApi or Swagger annotations? If OpenApi which version of swagger-php is installed.

Cc: @ejbogantes

**Comment by DarkaOnLine** [comment]
To use OpenApi annotations please follow instructions here https://github.com/OAI/OpenAPI-Specification

**Comment by kevincobain2000** [comment]
Thank you for the prompt response.

**Comment by tomcoonen** [comment]
Same issue here, the `@OAS` was changed to `@OA` which causes errors in a project here.
This should not have been done in a patch release, this is a major change..

**Comment by DarkaOnLine** [comment]
No, it is not major. Swagger-php for OpenApi is not released yet and annotations are in work. We are using OpenApi on our own risk for now.

**Comment by tomcoonen** [comment]
Ok my bad then! Thanks for the great work.

**Comment by AshrafHefny** [comment]
Same issue here? did anyone fix it?

**Comment by ejbogantes** [comment]
What annotations are you using, @OAS or @OA?

**Comment by kevincobain2000** [comment]
Hi, I am not sure. I have the following styled annotations in my code. I am sorry if that's not helpful

```
/**
 * @SWG\Swagger(
 *     basePath="/api",
 *     host=API_HOST,
 *     schemes=API_SCHEMES,
 *     produces={"application/json"},
 *     consumes={"application/json"},
 *          @SWG\Info(
 *              title="Laravel Swagger Demo",
 *              version="1.0",
 *              description="Swagger creates human-readable documentation for your APIs.",
 *          ),
```

Reference: https://github.com/jpcaparas/laravel-swagger-demo/blob/master/app/Http/Controllers/Api/Controller.php

**Comment by AshrafHefny** [comment]
@kevincobain2000, @ejbogantes  I was using @SWG annotation, I changed to @OA annotation and now it works.
But you should know that you'll change almost every @SWG annotation to new @OA annotation including (type, enum, maxItems, minItems, collectionFormat, ..., etc)

**Comment by AshrafHefny** [comment]
@ejbogantes I changed all annotations to OA, but after this documentation doesn't work as I expected, I got chrome console error `Uncaught (in promise) TypeError: Cannot read property 'keySeq' of undefined`!!

**Comment by ejbogantes** [comment]
@AshrafHefny  which version do you have installed? L5-swagger / Swagger PHP / Swagger UI

**Comment by AshrafHefny** [comment]
@ejbogantes  I'm using `darkaonline/l5-swagger V 5.6.*` , `zircote/swagger-php V 3`.* and `swagger-ui V 3.0`

**Comment by MrEko** [comment]
Same problem with
"darkaonline/l5-swagger": "5.5.*",
"zircote/swagger-php": "3.x-dev"

In Generator.php line 24:                                             
  Call to undefined function Swagger\scan()

Needs change to OpenApi\scan()

**Comment by ejbogantes** [comment]
You have to check the version for **darkaonline/l5-swagger** , it must be 5.6.8 in order to work with OA annotations.

**Comment by MrEko** [comment]
Should I use **darkaonline/l5-swagge 5.6.x** even with **laravel 5.5.x**?

**Comment by ejbogantes** [comment]
Yes, you should

**Comment by thanhnho1102** [comment]
Install `swagger-php 2.0` will fix it : 
"require": {
 "zircote/swagger-php": "~2.0",
}

**Comment by DarkaOnLine** [comment]
Hi, All

Need some help here :)

As from yesterday swagger-php 3.0 was officially released by default composers pulls 3.* version and not 2.*, so everyone who makes composer update will get 3.* and everything will break :( 

What would be your suggestions for this problem? 

- Drop OpenApi support for 5.5* and 5.6.* version and release 5.7 which will support OpenApi by default?
- Leave as it is and update the documentation to explicitly require `composer require zircote/swagger-php:2.* `  in your composer for Swagger Annotations support.
- Any other ...

Please help me with this!

**Comment by Jimbolino** [comment]
please fix support for 5.5.* since the 5.6.* branch requires a newer php version

**Comment by DarkaOnLine** [comment]
**5.5.9** and **5.6.9** will no longer support OpenApi

**5.7.*** - will support by default OpenApi and with a possibility to switch to `@SWG` (Swagger) annotations by requiring `zircote/swagger-php:2.* ` in your composer

**Comment by edgareler** [comment]
@AshrafHefny I got the same error of you `TypeError: Cannot read property 'keySeq' of undefined`, then I tried to update the lib to 5.7.0 and it didn't work, so I debugged the JS error and I found that one of my annotations was empty: `requestBody={}`. When I removed that, the Controller docs returned to expand properly.

**Comment by AshrafHefny** [comment]
@edgareler yes I notice this after checking the generated json file on sowgger live editor

**Comment by AshrafHefny** [comment]
@DarkaOnLine I think it's better to  release version 5.7 that supports OpenApi by default and ask people to upgrade to that version

**Comment by DarkaOnLine** [comment]
@AshrafHefny [as I pointed here](https://github.com/DarkaOnLine/L5-Swagger/issues/159#issuecomment-415325481) from now only 5.7.* will support OpenApi.

**Comment by webexpert4rv** [comment]
i have faced the same issue .@kevincobain2000 Have you solved this .Please help me.Thanks

**Comment by erusso87** [comment]
@thanhnho1102 Great! This work for me.
Do you know if is a temporary solucion or is just a Quick fix until **L5-swagger** is updated to use a newer version of swager-php ?

Thanks

**Comment by flik** [comment]
@kevincobain2000  I had the same issue. I resolved in this way: 
`./vendor/bin/swagger app/Http --output storage/api-docs`

It will generate the json file with the name swagger.json.
You need to rename it with the name **api-docs.json** and then access the url: 
http://localhost/angular-laravel/public/api/documentation

I have installed in composer json: 
```
 "require": {
        "php": "^7.1.3",
        "barryvdh/laravel-cors": "^0.11.0",
        "darkaonline/l5-swagger": "5.7.*",
        "fideloper/proxy": "^4.0",
        "folklore/graphql": "^1.1",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0",
        "zircote/swagger-php": "2.*"
    },
```

**Comment by toxmc** [comment]
When to upload 5.5.9 release to composer package? Now the newest package version is 5.5.8.3.

**Comment by burhankun** [comment]
Same problem here.
Laravel Framework 5.8.29

Steps to reproduce - Fresh Laravel:
Installation:
composer require "darkaonline/l5-swagger:5.8.*"
composer require 'zircote/swagger-php:2.*'

Publish:
php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"

ENV:
SWAGGER_VERSION=2.0

Generating Files:
php artisan l5-swagger:generate

Test:
Wiht OA und SWG Annoations.

Error:
   Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function Swagger\scan()

  at /var/www/vendor/darkaonline/l5-swagger/src/Generator.php:124
    120|             );
    121|         }
    122|
    123|         if (! $this->isOpenApi()) {
  > 124|             $this->swagger = \Swagger\scan(
    125|                 $this->appDir,
    126|                 ['exclude' => $this->excludedDirs]
    127|             );
    128|         }

**Comment by kirtiscale** [comment]
I get this error “Call to undefined function OpenApi\scan()”
