### ISSUE TITLE
HTML/CSS don't look right

### ISSUE THREAD

**Issue by bandtank** [DarkaOnLine/L5-Swagger#16]
I'm using L5.2 and L5-Swagger 3.0. I followed the instructions in the readme and the documentation loads, but it doesn't look right. I've used swagger in a rails project and I had similar issues, but I don't know how to solve the problem in Laravel.

Here's how it looks currently:
![capture](https://cloud.githubusercontent.com/assets/1170415/13879055/e6f40df4-ecda-11e5-8a04-58a239b02100.PNG)

I generated a JSON file manually with a few endpoints and, as you can see, it loads with the right values in the right places, but the formatting is messed up. What would be causing this?

**Comment by DarkaOnLine** [comment]
It is hard to say. But it looks like assets is not loaded (css/js). What are you seeing in console log ? Please check if url's of assets is generated correctly in your html source.

**Comment by bandtank** [comment]
Thanks for the fast response. I really appreciate it.

I checked the console in Chrome and no errors are shown, but there are a ton of objects being shown for some reason.

![capture](https://cloud.githubusercontent.com/assets/1170415/13879273/3905841e-ecdc-11e5-891b-0f9dfe1bcc24.PNG)

Where do I check the URLs? I looked around, but I'm not sure where the problem could be.

**Comment by DarkaOnLine** [comment]
Hmm. Strange. Looks like these log's are coming from Swagger-UI source. I need to investigate it. Which version of swagger you using for json file ?

**Comment by bandtank** [comment]
```
{
    "swagger": "2.0",
    "info": {
        "title": "PSE API",
        "description": "The Paragon Structural Engineering API",
        "version": "1.0.0"
    },
    "host": "api.pseglobal.com",
    "schemes": [
        "https"
    ],
    "basePath": "/v1",
    "produces": [
        "application/json"
    ],
    "paths": {
        "/users": {
            "get": {
                "summary": "Get a paginated list of user objects",
                "description": "This endpoint returns a paginated list of objects with details about one or more users.",
                "parameters": [
                    {
                        "name": "name",
```

**Comment by bandtank** [comment]
It looks like another person on the project forgot to commit something, so the files were in an unknown state. The situation seems to be resolved. Thanks for your help.
