### ISSUE TITLE
l5-swagger 5.7.0 requires laravel/framework: 5.6.*

### ISSUE THREAD

**Issue by DSpeichert** [DarkaOnLine/L5-Swagger#162]
- L5-Swagger Version:5.7.0
- PHP Version (`php -v`): N/A
- OS: N/A

### Description:
The 5.7.0 version of this package requires a laravel 5.6.* version. I believe it's meant to require 5.7.* instead.

### Steps To Reproduce:
N/A

**Comment by DarkaOnLine** [comment]
Yes!!! Thank you!!!
