### ISSUE TITLE
Call to undefined function Swagger\scan()

### ISSUE THREAD

**Issue by alizowghi** [DarkaOnLine/L5-Swagger#163]
- L5-Swagger Version: 5.5.8 (`composer show | grep l5-swagger`)
- PHP Version (`7.1.20`):
- OS: ubuntu16.04

### Description:
The problem is that in Generator.php below code is:

` $swagger = \Swagger\scan($appDir, ['exclude' => $excludeDirs]);`
https://github.com/DarkaOnLine/L5-Swagger/blob/5.5.x/src/Generator.php
But it must be this like version 5.6:

```
   if (version_compare(config('swagger-lume.swagger_version'), '3.0', '>=')) {
            $swagger = \OpenApi\scan($appDir, ['exclude' => $excludeDirs]);
   } else {
            $swagger = \Swagger\scan($appDir, ['exclude' => $excludeDirs]);
   }
```

### Steps To Reproduce:
php artisan l5-swagger:generate

**Comment by DarkaOnLine** [comment]
Are you using openApi or Swagger annotations ?

**Comment by mahbodsn** [comment]
This is my problem too.

**Comment by alizowghi** [comment]
@DarkaOnLine  openApi

**Comment by DarkaOnLine** [comment]
I dropped support for OpenApi on branch 5.5.x. If you need it please use 5.5.8 version.

**Comment by alizowghi** [comment]
@DarkaOnLine  
5.5.8 version doesn't support OpenApi too.
https://github.com/DarkaOnLine/L5-Swagger/blob/5.5.8/src/Generator.php

**Comment by Hesesses** [comment]
same problem here

**Comment by alizowghi** [comment]
Hi @Hesesses  
I forked from [](https://github.com/rswork/L5-Swagger/tree/5.4.x-multidoc) and solved some problems.

https://github.com/alizowghi/L5-Swagger/
version: 5.5.9

**Comment by DarkaOnLine** [comment]
I tagged [5.5.8.1](https://github.com/DarkaOnLine/L5-Swagger/releases/tag/5.5.8.1) with the fix

**Comment by DarkaOnLine** [comment]
Yes. If you want to use Swagger annotations with 5.7 you should manualy require swagger-php:2.*

**Comment by andrewdudu** [comment]
I still got the same Error, 

my version:
- "darkaonline/l5-swagger": "5.7.*"
- "zircote/swagger-php": "2.*"

i'm using Swagger annotation
