### ISSUE TITLE
5.5.8.1 is tagged to the wrong branch

### ISSUE THREAD

**Issue by Jimbolino** [DarkaOnLine/L5-Swagger#165]
I've had some issues when trying to install 5.5.8.1 
When comparing "branch 5.5.8.x" with "tag 5.5.8.1" i noticed that it required a new php and laravel verion so i think the tag is placed on the wrong version.

Also i noticed a small copy/paste error:
https://github.com/DarkaOnLine/L5-Swagger/blob/5.5.8.x/src/Generator.php#L25
i think "swagger-lume" should be "l5-swagger"

thnx again for the great work, and support for the older version :+1:

**Comment by DarkaOnLine** [comment]
Fixed in #166

**Comment by Jimbolino** [comment]
I still think something is wrong with the tags right?
https://github.com/DarkaOnLine/L5-Swagger/releases/tag/5.5.8.2
is on this commit:
https://github.com/DarkaOnLine/L5-Swagger/commit/e7a08390ade2d989ef458dfb0ca7ab009da020d2

but the 5.5.8.2 tag should be on this one:
https://github.com/DarkaOnLine/L5-Swagger/commit/ac8b7d197415344a75749016c84522fe56c24874

**Comment by DarkaOnLine** [comment]
Yes you are right. Released fix https://github.com/DarkaOnLine/L5-Swagger/releases/tag/5.5.8.3

Dam sorry guys...
