### ISSUE TITLE
config settings explanation

### ISSUE THREAD

**Issue by bandtank** [DarkaOnLine/L5-Swagger#17]
I don't understand the default config file due to a lack of documentation:

1. What are annotations and why is the base_path set to app?
2. What is base and why is it empty by default?
3. How do you change the name of the documentation file? It's called api-docs.json, but I need to create routes for different versions and the version number should be in the file name. I see the docs key, but the comment doesn't make much sense. What is a parsed swagger annotation and how is that different than a generated annotation and/or a manually generated file?

**Comment by DarkaOnLine** [comment]
1. Annotations is your comments/documentation of your API. For example [look heare](https://github.com/zircote/swagger-php/blob/master/Examples/petstore.swagger.io/ApiResponse.php). If you using only json file and not parsing it from php files you can ignore it.
2.  base param is not used anymore.
3. Using different files is not implemented. I need to think about it. Maybe you can make a PR ?  Parsed swagger annotations is the json file parsed from php comments. And yes it is the same as manual generated/written file.
