### ISSUE TITLE
Should be nice to generate the file if not existe?

### ISSUE THREAD

**Issue by erusso87** [DarkaOnLine/L5-Swagger#171]
https://github.com/DarkaOnLine/L5-Swagger/blob/e7a08390ade2d989ef458dfb0ca7ab009da020d2/src/Http/Controllers/SwaggerController.php#L25

```
if (! File::exists($filePath)) {
    Generator::generateDocs();
}
```

**Comment by DarkaOnLine** [comment]
Would be so great to have a PR for this ;)

**Comment by vega231** [comment]
I suggest to turn this off by default (or make it optional), every time someone enters invalid url address in swagger ui, the docs gets regenerated (even on prod environment!)

**Comment by erusso87** [comment]
That's a good point! Please, could you do a PR for this improvement?
