### ISSUE TITLE
blank page is coming on access api/documentation

### ISSUE THREAD

**Issue by flik** [DarkaOnLine/L5-Swagger#173]
- L5-Swagger Version: 5.7.* (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.1
- OS: Ubuntu 
Laravel version is 5.6.*

### Description:
I can generate document but when I try access url : http:abc.com/api/documentation blank page is coming. I checked logs and getting error:

 | 2018/09/24 08:03:10 [error] 14#14: *27 open() "/var/www/public/docs/asset/swagger-ui-standalone-preset.js" failed (2: No such file or directory), client: xxx.xx.x.x, server: cyrano.com, request: "GET /docs/asset/swagger-ui-standalone-preset.js?v=4d573bac98234b7b3ee8af5b610b34da HTTP/1.1", host: "cyrano.com", referrer: "http://cyrano.com/api/documentation"

### Steps To Reproduce:
install the swagger with:
1, 
composer require "darkaonline/l5-swagger:5.7.*"
2, 
composer require 'zircote/swagger-php:3.*'
3. 
 php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"

4.
 php artisan vendor:publish

**Comment by DarkaOnLine** [comment]
It looks like you are using nginx and you have server configuration issues. Please check #142 and other related issues.

**Comment by flik** [comment]
I have fixed the issue with these steps. here is detail link: https://stackoverflow.com/questions/51448899/swagger-does-not-publish-assets-files-in-laravel-5-6/52496448#52496448
