### ISSUE TITLE
Use of $ref throwing error.

### ISSUE THREAD

**Issue by sonoftheweb** [DarkaOnLine/L5-Swagger#174]
- L5-Swagger Version: 5.7.1
- PHP Version: 7.2.10
- OS: Ubuntu 18.04

### Description:
Attempting to reuse @Parameters in documentation but I keep getting the error **$ref "#/components/parameters/user_id_in_path_required" not found for @OA\Parameter()**

### Steps To Reproduce:
**In Controller.php**

/**
 * @OA\Parameter(
 *      parameter="user_id_in_path_required ",
 *      name="id",
 *      in="path",
 *      description="User ID",
 *      required=true,
 *      @OA\Schema(
 *          type="integer"
 *      )
 * )
 */

In TestController.php

/**
     *    @OA\Delete(
     *       path="/test/{id}",
     *       summary="Delete instance and data.",
     *       description="Delete instance and data.",
     *       operationId="deletetest",
     *       tags={"Test"},
     *       @OA\Parameter(ref="#/components/parameters/user_id_in_path_required"),
     *       @OA\Response(response=201, description="Deleted"),
     *       @OA\Response(response=401, description="Not Allowed"),
     *       @OA\Response(response=500, description="Error"),
     *       @OA\Response(response=404, description="Cannot find resource")
     *   )
     */

**Comment by bhattaxay** [comment]
Have you got any solution on above point? I stuck at the same point.

**Comment by ats05** [comment]
I think this issue need reopen.
