### ISSUE TITLE
Error getting data using Swagger

### ISSUE THREAD

**Issue by masehitam** [DarkaOnLine/L5-Swagger#177]
- L5-Swagger Version: 5.7.2 (`composer show | grep l5-swagger`)
- PHP Version: 7.1.19 (`php -v`):
- OS: OSX

### Description:
I'm sorry. I'm new using laravel and the question maybe silly.

I'm getting error excute get method on swagger, but success using postman
**postman**
GET http://127.0.0.1:8000/api/makanans
SUCCESS

**SWAGGER**
GET : http://127.0.0.1:8000/api/v1/makanans
RESPONSE 
CODE : 404
BODY : 
`{
  "message": "",
  "exception": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
  "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php",
  "line": 179,
  "trace": [
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 633,
      "function": "match",
      "class": "Illuminate\\Routing\\RouteCollection",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 622,
      "function": "findRoute",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 611,
      "function": "dispatchToRoute",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
      "line": 176,
      "function": "dispatch",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
      "line": 30,
      "function": "Illuminate\\Foundation\\Http\\{closure}",
      "class": "Illuminate\\Foundation\\Http\\Kernel",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/fideloper/proxy/src/TrustProxies.php",
      "line": 57,
      "function": "Illuminate\\Routing\\{closure}",
      "class": "Illuminate\\Routing\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 151,
      "function": "handle",
      "class": "Fideloper\\Proxy\\TrustProxies",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
      "line": 53,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
      "line": 31,
      "function": "Illuminate\\Routing\\{closure}",
      "class": "Illuminate\\Routing\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 151,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
      "line": 53,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
      "line": 31,
      "function": "Illuminate\\Routing\\{closure}",
      "class": "Illuminate\\Routing\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 151,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
      "line": 53,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
      "line": 27,
      "function": "Illuminate\\Routing\\{closure}",
      "class": "Illuminate\\Routing\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 151,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
      "line": 53,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
      "line": 62,
      "function": "Illuminate\\Routing\\{closure}",
      "class": "Illuminate\\Routing\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 151,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
      "line": 53,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 104,
      "function": "Illuminate\\Routing\\{closure}",
      "class": "Illuminate\\Routing\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
      "line": 151,
      "function": "then",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
      "line": 116,
      "function": "sendRequestThroughRouter",
      "class": "Illuminate\\Foundation\\Http\\Kernel",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/public/index.php",
      "line": 55,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Kernel",
      "type": "->"
    },
    {
      "file": "/Users/bsi-1/Documents/PHPProject/tutorial1/server.php",
      "line": 21,
      "function": "require_once"
    }
  ]
}`

**Comment by masehitam** [comment]
sorry, I think its because I havent add laravel/passport into my composer.json

**Comment by kev-landry** [comment]
If you have modified config/l5-swagger try to run a `php artisan config:cache`.
