### ISSUE TITLE
Feature suggestion: Automatically parse Laravel routes

### ISSUE THREAD

**Issue by hackel** [DarkaOnLine/L5-Swagger#178]
It would be great if this package could (optionally) automatically parse Laravel routes in order to generate an OpenAPI file on the fly.  The best example of this I have found is: https://github.com/mpociot/laravel-apidoc-generator

There is so much information already that isn't being used.  It should pull in as much from code, type-hinting, and doc-blocks as possible, using @OA tags only to supplement whatever isn't auto-detected.  This includes detecting the response model based on an Eloquent API Resource that is type-hinted.

It might be different enough to warrant spinning off as a separate project.  Let me know what you think.

**Comment by JeanLucEsser** [comment]
I do agree that this is missing, especially for auto generating the routes. It shouldn't be that complicated to implement, maybe by taking a look at https://github.com/mtrajano/laravel-swagger for ideas on how to do it.

**Comment by DarkaOnLine** [comment]
PR is always welcome. But this looks like a lot of work. It should be not only a parser for routes but also merge corresponding annotations for each method, for example, responses, exceptions etc.

**Comment by maxbaumhoegger-cnnctvstn** [comment]
Is there any update on this or an alternative way to avoid all these duplicate information such as route type, path, etc.?
