### ISSUE TITLE
Debian - publish not working :(

### ISSUE THREAD

**Issue by kamil-kielczewski** [DarkaOnLine/L5-Swagger#180]
- L5-Swagger Version: 5.7.2 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.2
- OS: Debian GNU/Linux 9 (stretch)

### Description:

I try many different approach like:

```
php artisan vendor:publish --provider="L5Swagger\L5SwaggerServiceProvider"
php artisan vendor:publish --provider 'L5Swagger\\L5SwaggerServiceProvider'
php artisan vendor:publish

```

but never see `l5-swagger.php` in `config` directory :(

### Steps To Reproduce:

Here is picture (of all, but i tried many times in different configurations): https://imgur.com/a/QIJTZUK

If you have installed docker, you can very easy reproduce error on MacOS in following way:

1. Create dockerfile with content:

```
# default  /var/www/html (mapped to .../code folder with projects)
FROM php:7.2-apache

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN apt-get update &&\
    apt-get install -y \
    git \
    libpng-dev \
    zlib1g-dev \
    libzip-dev \
    unzip &&\
    a2enmod rewrite
    
#    &&\ 
#    docker-php-ext-install pdo pdo_mysql zip gd &&\
#    a2enmod rewrite 

RUN docker-php-ext-install pdo 
RUN docker-php-ext-install pdo_mysql 
RUN docker-php-ext-install zip
RUN docker-php-ext-install gd 

# path for future composer global modules installation e.g. 
# composer global require "laravel/lumen-installer" 
# after this command "lumen" will be avilable
RUN echo "PATH=$PATH:/root/.composer/vendor/bin" >> /root/.bashrc

```
2. Create "run" file which can be executed with following body (where `/Volumes/work` is path to your folder with Laravel 5.7 fresh code):

```
set -e
cd -- "$(dirname "$0")"  # go to script dir - (for macos double clik run)
docker build -t php-cmd .
docker rm -f php-cmd
docker run -d --name php-cmd -v /Volumes/work:/work php-cmd
docker exec -it php-cmd bash -c "cd /work; bash"
cat
```

3. Execute `run` file and try to install and publish L5-Swagger

**Comment by kamil-kielczewski** [comment]
I see that when I add to AppServiceProvider@register located in app/Providers  following line:

`$this->app->register(\L5Swagger\L5SwaggerServiceProvider::class)`

then everything works

**Comment by yuanzhou3118** [comment]
> this does not work for me. https://cursos.paraoaltoeavante.com.br/api/documentation
> Show the blank page

same question, how do you do

**Comment by DarkaOnLine** [comment]
looks like resolved.
