### ISSUE TITLE
How to prevent access to api-docs.json

### ISSUE THREAD

**Issue by cyberfly** [DarkaOnLine/L5-Swagger#181]
- L5-Swagger Version: 3.2.2
- PHP Version (`php -v`): 7.2
- OS: Mac Sierra

### Description:

I want to prevent access to api-docs.json. It works to prevent api/documentation but cannot prevent direct access to the json file

### Steps To Reproduce:

 ```
'middleware' => [
            'api' => ['web', 'auth.basic'],
            'docs' => ['web', 'auth.basic'],
        ],
```

**Comment by DarkaOnLine** [comment]
You can yous `.htaccess` file to restrict access to all files in a directory where your json file is located.
