### ISSUE TITLE
Propose ordering for API documentation on Swagger UI

### ISSUE THREAD

**Issue by sonoftheweb** [DarkaOnLine/L5-Swagger#183]
- L5-Swagger Version: 5.7.2 
- PHP Version: 7.2.11
- OS: Ubuntu 18.04

### Description:
Propose ordering for API documentation on Swagger UI. When creating API docs, we should be able to add "order"=int where int is a number. This number should be used to order the API endpoints in Swagger UI as in my case, some actions needs to be made before some other actions can be tested. Pray tell if there is a way to already do this.

**Comment by DarkaOnLine** [comment]
You can write your own sort function. Please read in documentation (operationsSorter) : https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md

**Comment by peektoseen** [comment]
The tag order in the global tags section also controls the default sorting in Swagger UI.
How can I add global tags section with l5-swagger ?

**Comment by peektoseen** [comment]
> You can write your own sort function. Please read in documentation (operationsSorter) : https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md

Where this function need to be placed?  Only operationsSorter available for configuration in l5-swagger? Maybe tagsSorter also?

**Comment by xbrunosousa** [comment]
To future users, [see this](https://github.com/zircote/swagger-php/issues/478).
