### ISSUE TITLE
Property notation in Laravel Model

### ISSUE THREAD

**Issue by decaluwepatrick** [DarkaOnLine/L5-Swagger#184]
- L5-Swagger Version: 5.7.2 (`composer show | grep l5-swagger`)
- PHP Version 7.1.16 (`php -v`):
- OS:

### Description:

When using OA notation in a laravel model, I am overriding the accessor properties that were automatically created. In this example, $this->id will be null in calls on my user model. Is there a way to declare these without affecting your model?

### Steps To Reproduce:

Add property description to a property of a model 

class User extends Authenticatable
{

   /**
     * @OA\Property(
     *     format="int64",
     *     description="id of the user",
     *     title="name",
     * )
     *
     * @var integer
     */
      public $id;

      protected $fillable = [
        'id'
     ];
}

**Comment by DarkaOnLine** [comment]
Personally, I am using separate classes for my annotation models, and not the real Models and I think it is the best approach because your api response models will be different from your real models.
