### ISSUE TITLE
How to annotate the returned parameters?

### ISSUE THREAD

**Issue by robote** [DarkaOnLine/L5-Swagger#185]
- L5-Swagger Version: 5.5 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): php 7.1
- OS: 

### Description:
API return  some parameters ，not model  property，How to annotate the returned parameters?  thank you

**Comment by DarkaOnLine** [comment]
Please read swagger / OpenApi documentations - https://github.com/OAI/OpenAPI-Specification/tree/master/versions
