### ISSUE TITLE
"Call to undefined function Swagger\scan()" with l5-swagger 5.7.* and zircote/swagger-php 3.0

### ISSUE THREAD

**Issue by HimakarPV** [DarkaOnLine/L5-Swagger#186]
- L5-Swagger Version: 5.7.* (`composer show | grep l5-swagger`)
- PHP Version (`php -v.7.1.3`):
- OS:Windows
- Laravel version 5.6.*

### Description:
I updated l5-swagger to 5.7.* and zircote got updated to 3.0. I removed @SWG annotations and used openapi annotations. Using L5_SWAGGER_GENERATE_ALWAYS=true in .env file. When tried to run api/documentation on browser, it threw this error : Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined function Swagger\scan()

If I downgrade zircote to 2.* and use Swagger annotations then it worked fine, but I would like to know what is issue in using latest versions. Wont it work with openapi 3.0 ?

**Comment by DarkaOnLine** [comment]
It looks like you forgot to change SWAGGER_VERSION in your config file to 3.0 https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php#L181

**Comment by warlof** [comment]
Hi,

I got the same issue with version 5.5.* and zircote pinned to 2.*.
I'm using `@SWG` which should work with spec 2.0

https://i.imgur.com/Dgln5bO.png

**Comment by rahulsha01** [comment]
https://flareapp.io/share/17WgMJ7X

**Comment by zeetabit** [comment]
> Hi,
> 
> I got the same issue with version 5.5.* and zircote pinned to 2.*.
> I'm using `@SWG` which should work with spec 2.0
> 
> https://i.imgur.com/Dgln5bO.png

same thing!

**Comment by zeetabit** [comment]
> https://flareapp.io/share/17WgMJ7X

You should have install swagger 2.0 version package (not a 3.0)
