### ISSUE TITLE
Api/documentation showing blank page

### ISSUE THREAD

**Issue by trangunghoa** [DarkaOnLine/L5-Swagger#189]
- L5-Swagger Version: 5.7.2 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.1.2
- OS: Window run IIS 

### Description:
I deployed my code in the server using IIS and php 7.1.2( server is blocked internet)
It's working on my local but in server it's showing 404 page.
I checked `route:list` it doesn't show any swagger route. 
I tried to run `php aristan l5-swagger:generate` it's showing the message:
"There are no commands defined in the 'l5-swagger' namespace"
How can I fix it?
Thank you

**Comment by DarkaOnLine** [comment]
if you cant see commands it means you are not registered or installed the package.

**Comment by trangunghoa** [comment]
It's already installed on the package, and it's working well on my local( on MAC OS).
