### ISSUE TITLE
Upload multiple files

### ISSUE THREAD

**Issue by eserenna** [DarkaOnLine/L5-Swagger#190]
Is there a method to upload multiple files with l5-swagger?

**Comment by DarkaOnLine** [comment]
Multiple API documentation's you mean?

**Comment by eserenna** [comment]
No. Type file but for multiple files. Currently if i use type="files" it will only upload 1 file per parameter. Is there a way to upload an array of files in parameter

**Comment by DarkaOnLine** [comment]
This is SwaggerUI config you are referring to?

**Comment by eserenna** [comment]
I'm referring to the whole L5-swagger and its dependencies. Is it possible for the L5-swagger to upload an array of files in its parameter?

**Comment by DarkaOnLine** [comment]
Where are you setting this parameter? How are you uploading and what files?

**Comment by eserenna** [comment]
i saw from zircote/swagger-php

    *   @OA\RequestBody(
    *       @OA\MediaType(
    *           mediaType="multipart/form-data",
    *           @OA\Schema(
    *               @OA\Property(
    *                  property="full_image",
    *                  type="array",
    *                  @OA\Items(
    *                       type="string",
    *                       format="binary",
    *                  ),
    *               ),
    *           ),
    *       )
    *   ),

but it returns string(27) "[object File], [object File]"

**Comment by eserenna** [comment]
same output. 
string(27) "[object File],[object File]"

**Comment by DarkaOnLine** [comment]
According to swagger-php it should work: https://github.com/zircote/swagger-php/issues/525#issuecomment-425716714

**Comment by eserenna** [comment]
ya but read the comment below it

**Comment by YaakovDantas** [comment]
So @eserenna , did finished the issue ? I'm having the same problem
