### ISSUE TITLE
 @OA\PathItem()

### ISSUE THREAD

**Issue by cacpmw** [DarkaOnLine/L5-Swagger#191]
- L5-Swagger Version: 5.7.2 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.1.19
- OS: MACOS MOJAVE

### Description:
 I'm trying to generate documentation for an api and I get this error.
 ErrorException  : Required @OA\PathItem() not found

I wrote the following annotation on the Controller.php (app/http/controllers/)
```
/**
 * @OA\Info(
 *      version="1.0.0",
 *      title="L5 OpenApi",
 *      description="L5 Swagger OpenApi description"
 * )
 *
 */
```
### Steps To Reproduce:
`composer require "darkaonline/l5-swagger:5.7.*"`
 `php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"`
edit your config/l5-swagger.php configuration file. Locate the l5-swagger.routes.middleware section, and add the following middleware list to the api route:
```
'api' => [
  \App\Http\Middleware\EncryptCookies::class,
  \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
  \Illuminate\Session\Middleware\StartSession::class,
  \Illuminate\View\Middleware\ShareErrorsFromSession::class,
  \App\Http\Middleware\VerifyCsrfToken::class,
  \Illuminate\Routing\Middleware\SubstituteBindings::class,
  \Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,
  'auth',
]
```
`php artisan L5-swagger:generate
`

**Comment by DarkaOnLine** [comment]
@OA\PathItem() annotation is required. Please read Swageer/OpenApi the documentation.

**Comment by ravipxm** [comment]
@DarkaOnLine 

I have tried everything but this error still shows up. Could you please help me with this

**Comment by sudkumar** [comment]
@ravipxm Did you try adding one route definition. e.g.

After adding
```
/**
 * @OA\Info(
 *      version="1.0.0",
 *      title="L5 OpenApi",
 *      description="L5 Swagger OpenApi description"
 * )
 *
 */
```

Add one route definition. e.g.
```
/**
 * @OA\Get(
 *     path="/",
 *     description="Home page",
 *     @OA\Response(response="default", description="Welcome page")
 * )
 */
```

I was getting the same error and this solved it.

Hope this helps.

**Comment by mca93** [comment]
Hi @sudkumar,
This helped me.
@DarkaOnLine I've refered to you on the onether post. This helped me. Thanks

**Comment by norellanac** [comment]
![carbon](https://user-images.githubusercontent.com/17126622/153640462-d929357a-4136-4bc0-8b3b-a353d723ac82.png)

**Comment by portoinfo** [comment]
> @ravipxm Did you try adding one route definition. e.g.
> 
> After adding
> 
> ```
> /**
>  * @OA\Info(
>  *      version="1.0.0",
>  *      title="L5 OpenApi",
>  *      description="L5 Swagger OpenApi description"
>  * )
>  *
>  */
> ```
> 
> Add one route definition. e.g.
> 
> ```
> /**
>  * @OA\Get(
>  *     path="/",
>  *     description="Home page",
>  *     @OA\Response(response="default", description="Welcome page")
>  * )
>  */
> ```
> 
> I was getting the same error and this solved it.
> 
> Hope this helps.

This solution worked for me too! Thank you very much!

**Comment by parmonov98** [comment]
> * L5-Swagger Version: 5.7.2 (`composer show | grep l5-swagger`)
> * PHP Version (`php -v`): 7.1.19
> * OS: MACOS MOJAVE
> 
> ### Description:
> I'm trying to generate documentation for an api and I get this error. ErrorException : Required @OA\PathItem() not found
> 
> I wrote the following annotation on the Controller.php (app/http/controllers/)
> 
> ```
> /**
>  * @OA\Info(
>  *      version="1.0.0",
>  *      title="L5 OpenApi",
>  *      description="L5 Swagger OpenApi description"
>  * )
>  *
>  */
> ```
> 
> ### Steps To Reproduce:
> `composer require "darkaonline/l5-swagger:5.7.*"` `php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"` edit your config/l5-swagger.php configuration file. Locate the l5-swagger.routes.middleware section, and add the following middleware list to the api route:
> 
> ```
> 'api' => [
>   \App\Http\Middleware\EncryptCookies::class,
>   \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
>   \Illuminate\Session\Middleware\StartSession::class,
>   \Illuminate\View\Middleware\ShareErrorsFromSession::class,
>   \App\Http\Middleware\VerifyCsrfToken::class,
>   \Illuminate\Routing\Middleware\SubstituteBindings::class,
>   \Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,
>   'auth',
> ]
> ```
> 
> `php artisan L5-swagger:generate `
The same issue: 
Controller.php
```
<?php

/**
 * @OA\SecurityScheme(
 *     type="http",
 *     description="Login with email and password to get the authentication token",
 *     scheme="bearer",
 *     bearerFormat="JWT",
 *     securityScheme="bearerAuth",
 * )
 */

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

/**
 * @OA\Info(
 *   version="1.0.0",
 *   title="Toirjon Elektron tizimi API",
 *      title="Toirjon Elektron tizimi - API",
 *       description="based on L5 Swagger OpenApi",
 *       @OA\Contact(
 *           email="parmonov98@yandex.ru"
 *       ),
 * )
 */

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

```
OrderController.php
```
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreOrderRequest;
use App\Http\Requests\UpdateOrderRequest;
use App\Models\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{

    /**
     * @OA\Get(
     *   tags={"Orders"},
     *   path="/orders",
     *   @OA\Response(
     *       response="default",
     *       description="successful operation",
     *   )
     * )
     */
```

![image](https://user-images.githubusercontent.com/24564577/211240399-51b6fd88-19fd-4a7f-8ae4-76bea49641c0.png)

**Comment by gawsoftpl** [comment]
Try run
```sh
php artisan optimize:clear
```

**Comment by AnshumanBharatiya** [comment]
*
![WhatsApp Image 2023-10-31 at 8 40 18 AM](https://github.com/DarkaOnLine/L5-Swagger/assets/44137214/ccaa8ee8-2a93-40dc-bc05-415d5a3528fa)
 @OA\PathItem(
     * path="/api/register",
*),

add path like this menthod in your controller file in get for post method
