### ISSUE TITLE
Required @OA\Info() not found

### ISSUE THREAD

**Issue by eleven0220** [DarkaOnLine/L5-Swagger#197]
- L5-Swagger Version: "darkaonline/l5-swagger": "^5.8"
- PHP Version (`php -v`): PHP 7.2.15 (cli) (built: Feb  5 2019 22:54:26) ( ZTS MSVC15 (Visual C++ 2017) x64 )

- OS: windows

**Comment by DarkaOnLine** [comment]
@OA\Info() is required annotation you must include it in you annotations. Please read documentation
