### ISSUE TITLE
 multiple api routing branches oauth

### ISSUE THREAD

**Issue by piaohan** [DarkaOnLine/L5-Swagger#198]
- L5-Swagger Version: 5.7.* (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.2.11
- OS: windos

### Description:

I have multiple api routing branches, I want to be in config/l5-swagger.passprot.password when requesting. I can customize a parameter to request in oauth. I need help

![image](https://user-images.githubusercontent.com/12056081/53559479-2214fa00-3b85-11e9-8ae8-b587f010359a.png)

**Comment by piaohan** [comment]
@collegeman

**Comment by DarkaOnLine** [comment]
I think you can configure multiple authorizations in your config.

**Comment by piaohan** [comment]
@DarkaOnLine Hello, I have already set it in the configuration. Is my configuration error? I hope you can give pointers
My configuration is as follows:

1.postman：
![image](https://user-images.githubusercontent.com/12056081/53931742-6b0f0600-40d1-11e9-8426-c67908e75137.png)
2.config/l5-swagger:
![image](https://user-images.githubusercontent.com/12056081/53931768-8712a780-40d1-11e9-818a-3056d732e3a9.png)
3.html:
![image](https://user-images.githubusercontent.com/12056081/53931795-b1646500-40d1-11e9-8e4c-6229b6ac7096.png)

I understand that I need to add the options I need in the form, and this choice is in my configuration, and then the generated page is submitted together, I do not know if I understand the mistake? But after doing it according to my ideas, I found that I could not achieve my goal.
Can't choose, can't successfully get token。
