### ISSUE TITLE
Impossible to create the root directory "".In Local.php line 106

### ISSUE THREAD

**Issue by jusyjk** [DarkaOnLine/L5-Swagger#199]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):
- OS:

**Comment by DarkaOnLine** [comment]
What an informative issue!

**Comment by F-Yousri** [comment]
@jusyjk I had the same issue lately, and for me the problem was with caching configuration
try this:
- remove the published l5-swagger config file
- run php artisan config:cache
- try publishing the vendor again

hope this helps
