### ISSUE TITLE
Routes not taken into account

### ISSUE THREAD

**Issue by othmannasrou** [DarkaOnLine/L5-Swagger#2]
Hi,

Thanks for your work, I was looking for a way to use easily swagger-php with Laravel 5.

Unfortunately, it seems like the "routes.php" file is not taken into account :  the routes don't work unless I copy/paste the file's content directly in the main routes file : app/Http/routes.php

I can see in the service provider that the file is included in the register function but the app won't respond to the specified request : /api-docs and /docs

Any explanation for this ? Thanks !

**Comment by DarkaOnLine** [comment]
Hi,

Jus register services provider in AppServiceProvider.php not in config/app.php

I updated installation instructions today. 

If it will not work please let me know.

**Comment by othmannasrou** [comment]
Hi,

I've already done that, according to the new installation instructions. But still it doesn't work.

Could this be because the service provider is deferred ? Changing this doesn't make it either. The routes are still unavailable.

**Comment by DarkaOnLine** [comment]
Strange I tested everything on fresh installation today and it worked.  

I will try to find out what's wrong. 

Thanks again

**Comment by othmannasrou** [comment]
Hi,

I tried on another computer and it worked fine. There must be a problem with my configuration : I'll try to guess what is not working just in case, but I think the issue can be closed. Sorry for the bothering !

**Comment by DarkaOnLine** [comment]
Thanks for folow up saved me some debuging time :)
