### ISSUE TITLE
Basepath with 2 Folders

### ISSUE THREAD

**Issue by Kingmaddi** [DarkaOnLine/L5-Swagger#201]
Hi,

thank you for this nice Plugin.
Is it possible to generate the Swagger-Documentation with 2 different BasePath´s?

For example /routes and /app ?

Thank you for your help

**Comment by DarkaOnLine** [comment]
No :( only one path. But it should be simple update. Would you be interested to make PR for this feature?

**Comment by DarkaOnLine** [comment]
Implemented: https://github.com/DarkaOnLine/L5-Swagger/commit/8502b4dafacf73860f1ef122c4f77bb1399adb93
