### ISSUE TITLE
How to know when request is from Swagger UI?

### ISSUE THREAD

**Issue by KeitelDOG** [DarkaOnLine/L5-Swagger#202]
- L5-Swagger Version: 5.7.2
- PHP Version: 7.1.20
- OS: MacOS

### Description:
Sorry but it's not an error, but it's a feature that I want, or a work around to get it. But I definitely want to know when a request comes from Swagger UI so that I can for example :
- Add Swagger as source to statistics usage API
- Change Laravel Database Connections
- Etc.

I know Swagger UI is just HTML Forms, but maybe I could add some global HEADER with Swagger and Check it out on Laravel Middleware to customize configs. Or Maybe L5-Swagger could provide a Method callback that we could use providing a Class with that method in a Laravel fashion way.

### Steps To Reproduce:
Not an Error
You are free to close this issue if such a feature will not be available, and no work around is possible.

**Comment by DarkaOnLine** [comment]
It looks like you can implement this with swagger-ui plugins or presets. Sorry but this is out of this package scope.
