### ISSUE TITLE
JSON Viewer to format response

### ISSUE THREAD

**Issue by Joisar** [DarkaOnLine/L5-Swagger#203]
- L5-Swagger Version: 5.5 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.3
- OS: Windows and Mac

JSON Viewer along with this Swagger UI will be great combination for developers. 

On click of JSON response, we are opening JSON Viewer

![swaggerJsonView](https://user-images.githubusercontent.com/3830290/55408159-14380780-557d-11e9-8d94-66a6c41cdad9.gif)

Feel free to check out our demo:
https://catch.testflight.biz/api/documentation

Let us know your feedback and suggestions if we can contribute more on this.

Thanks!

**Comment by DarkaOnLine** [comment]
Looks nice, but it feels that this feature is out of scope for this package. Consider suggesting this to Swagger-ui repo.
