### ISSUE TITLE
Use manual MiddleWare

### ISSUE THREAD

**Issue by iazaran** [DarkaOnLine/L5-Swagger#204]
- L5-Swagger Version: 5.6.*
- PHP Version: 7.1.3
- Laravel Version: 5.6.39
- OS: Google Cloud Console

### Description:
I want to use my manual middleware in OpenAPI.
I let my users to send normal & encoded (by a formula & a secret key) Header Body via their websites.
And then I get normal Header Body by my website and use same formula & Secret Key to encode it again & then compare it with the encoded request from user. If I find equality, return true for the middleware.
This is main part of this simple formula:

```php
public function handle($request, Closure $next)
    {
        if (! $this->verifySignature($request)) {
            abort(401);
        }
        return $next($request);
    }

private function verifySignature($request)
    {
        $url = $request->fullUrl();
        $url = strtok($url, "?");
        $body = $request->getContent();
        $data = $body.$url;
        $hmac = base64_encode(hash_hmac('sha1', $data, APP_SECRET, true));
        return $request->header('X-Signature') == $hmac;
    }
```
So I receive error 401, that I defined it in middleware in all APIs.
I have this in the l5-swagger.php in config folder and don't useful. I want to insert APP_SECRET to it, not whole encoded content each time.

```php
'api_key_security_x_signature' => [
        'type' => 'apiKey',
        'description' => 'Calculated HMAC X-Signature value of your request body',
        'name' => 'X-Signature',
        'in' => 'header',
]
```
I want to let L5-Swagger use an APP_SECRET and use it like my users. Any idea?
Thanks all

**Comment by DarkaOnLine** [comment]
We have `constants` for this in the config

**Comment by iazaran** [comment]
@DarkaOnLine 
Thanks Darius,
I have no access to those codes now. Please close this topic and I'll report again, I guess that the solution is simple as you said.
