### ISSUE TITLE
`l5-swagger.paths.excludes` not working.

### ISSUE THREAD

**Issue by jwranga** [DarkaOnLine/L5-Swagger#208]
- L5-Swagger Version (`composer show | grep l5-swagger`): `5.8.0`
- PHP Version (`php -v`): `7.3.4-1+ubuntu18.04.1+deb.sury.org+3`
- OS: `Ubuntu 18.04.2 LTS`

### Description:
Paths specified in `l5-swagger.paths.excludes` are not considered when generating the API Doc.

Exluded paths still get included in the doc.

### Steps To Reproduce:

1. Put a path in `l5-swagger.paths.excludes` array.
2. Run `./artisan config:cache` to update cache.
3. Run `./artisan l5-swagger:generate` to generate API Doc.
4. Observe that annotations from the exluced paths are still included in the API Doc.

**Comment by azurinspire** [comment]
I think the comment in `l5-swagger.php` file is wrong, it says `Absolute path to directories that you would like to exclude from swagger generation`. I got exclude to work with relative path to annotations folder, which defaults to `app` as `'annotations' => base_path('app')`:

```php
<?php
//....
'excludes' => ['Http/Controllers/FolderToExclude'],
```

**Comment by elvismatus** [comment]
Solo para completar el comentario de @azurinspire. La ruta del fichero donde se debe agregar es exclude (en Laravel) es config/l5-swagger.php
