### ISSUE TITLE
nwidart/laravel-modules package capatible

### ISSUE THREAD

**Issue by mepoohsta** [DarkaOnLine/L5-Swagger#210]
- L5-Swagger Version: 5.7.*
- PHP Version (`php -v`): 7.1
- OS: ubuntu

### Description:

Not working if OA comment were added in [nwidart/laravel-modules](https://github.com/nWidart/laravel-modules) module 

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/9480365/59304482-069bae00-8ca1-11e9-8d4b-676f94ca81b2.png)

"Required @OA\\Info() not found"

**Comment by mepoohsta** [comment]
Nevermind, added 
![image](https://user-images.githubusercontent.com/9480365/59305419-e79e1b80-8ca2-11e9-8030-10d628ce245a.png)
in config file.

**Comment by vinnyfs89** [comment]
This way works for me:

![Screenshot from 2021-02-11 16-50-57](https://user-images.githubusercontent.com/3949238/107690811-5eb26100-6c89-11eb-99c1-e399a3313afc.png)

**Comment by chintan-mbarc** [comment]
@oviniciusfeitosa

Its working for me, Thanks
