### ISSUE TITLE
Parameters too much to load.

### ISSUE THREAD

**Issue by Yw-melo** [DarkaOnLine/L5-Swagger#215]
- L5-Swagger Version: 5.8
- PHP Version 7.2:
- OS: Mac os 10. chrome

### Description:
I have a API have about 16 parameters, and there is no response after a click that api in documentation page.And other APIs are ok. Any suggestions to me?

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/33000435/61941500-32ad8d00-afca-11e9-9f41-a45e0a174cdb.png)

**Comment by SkyCrew-g** [comment]
>  I think you can look here

https://github.com/swagger-api/swagger-codegen/issues/3966

**Comment by SkyCrew-g** [comment]
> * L5-Swagger Version: 5.8
> * PHP Version 7.2:
> * OS: Mac os 10. chrome
> 
> ### Description:
> I have a API have about 16 parameters, and there is no response after a click that api in documentation page.And other APIs are ok. Any suggestions to me?
> 
> ### Steps To Reproduce:
> ![image](https://user-images.githubusercontent.com/33000435/61941500-32ad8d00-afca-11e9-9f41-a45e0a174cdb.png)

https://github.com/swagger-api/swagger-codegen/issues/3966

**Comment by SkyCrew-g** [comment]
I think, you can check this here: https://github.com/swagger-api/swagger-codegen/issues/3966
