### ISSUE TITLE
Requested L5 Swagger asset file does not exists

### ISSUE THREAD

**Issue by DavyDeCoster** [DarkaOnLine/L5-Swagger#222]
- L5-Swagger Version: 5.8.2 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.3.9
- OS: Homestead 8.0.1

### Description:

After updating the package, I'm not able to navigate to the documentation. This due to the fact the files aren't found anymore.

See flare-link for stack trace: https://flareapp.io/share/yv5p1lmE#F51

### Steps To Reproduce:

Just update the package

**Comment by DarkaOnLine** [comment]
Please add this line to your config till the fix will be released: https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php#L109

**Comment by DarkaOnLine** [comment]
5.8.3 is released: https://github.com/DarkaOnLine/L5-Swagger/releases/tag/5.8.3
