### ISSUE TITLE
Descriptions are not generated for openapi

### ISSUE THREAD

**Issue by waffshappen** [DarkaOnLine/L5-Swagger#224]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
darkaonline/l5-swagger                6.0.1              Swagger integration to Laravel 5
- PHP Version (`php -v`):
PHP 7.3.9 (cli) (built: Aug 27 2019 22:52:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9, Copyright (c) 1999-2018, by Zend Technologies
- OS:
Fedora 30

### Description:
description= Fields are not translated into the generated openapi docs

### Steps To Reproduce:
![Step 1](https://user-images.githubusercontent.com/44290023/65520176-7c8df300-dee7-11e9-8d4b-c3a6e13e62dd.png)
![Step 2](https://user-images.githubusercontent.com/44290023/65520238-8dd6ff80-dee7-11e9-85c7-ef8bb25b21ad.png)

**Comment by DarkaOnLine** [comment]
You should address this issue to https://github.com/zircote/swagger-php cause this package using it for parsing annotations. Also please check swagger-php documentation on how description should be written.
