### ISSUE TITLE
Load YAML instead of Defining inside PHP

### ISSUE THREAD

**Issue by marcstreeter** [DarkaOnLine/L5-Swagger#225]
- L5-Swagger Version: 5.7.2
- PHP Version (`php -v`): 7
- OS: Alpine linux

### Description:
Currently doing something like 

```
    /**
     * @OA\Get(
     *      path="/myPath",
     *      someId="myId",
     *      tags={"My Path"},
     *      summary="Search my path",
     *      @OA\Parameter(
     *         in="query",
     *         name="foo",
     *         required=false,
     *         @OA\Schema(
     *             type="string",
     *             description="bar",
     *             enum={"spam", "eggs", "bacon"}
     *         )
     *      ),
     *      @OA\Response(
     *          response=200,
     *          description="OK",
     *          @OA\MediaType(
     *              mediaType="application/json",
     *              @OA\Schema(
     *                  schema="myResponseSchema",
     *                  allOf={
     *                      @OA\Schema(ref="#/components/schemas/myResponse"),
     *                      @OA\Schema(
     *                          type="object",
     *                          @OA\Property(
     *                              property="data",
     *                              type="array",
     *                              @OA\Items(
     *                                  type="object",
     *                                  @OA\Property(
     *                                      property="id",
     *                                      type="integer",
     *                                      description="The id of my response item"
     *                                  )
     *                              )
     *                          )
     *                      ),
     *                  }
     *              )
     *          )
     *       ),
     *     )
     *
     * Returns list of my responses
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse|\Symfony\Component\HttpFoundation\StreamedResponse
     */
    public function getMyResponse(Request $request)
```
I want to show the "connection" with the controller method but define it normally inside of a yaml file as well as get the other benefits (like turning off the swagger documentation for certain routes). I can't find a way in your documentation on how to load a yaml file instead of defining it all within PHP.
### Steps To Reproduce:
The above shows an example of what I'm doing. This may be the wrong place to ask this. Apologies.

**Comment by DarkaOnLine** [comment]
If I am correct - you want to use Open API definitions in separate `yaml` files. In this case this package is not for you. You can just pull swagger-ui and configure it to use your `yaml` files.

**Comment by marcstreeter** [comment]
Well, this package offers a lot more than declaring the swagger document in the code base, things that swagger doesn't offer alone.  I already have my yaml files separately working with the swagger-ui, but I really like what's offered here, and would like a way to take advantage without having to copy all of that into my laravel project. Rather I'd like to reference my yaml files and specify the L5-Swagger specific options (like middleware and disabling certain routes from being documented).

From what I get you don't yet offer that feature, would you consider a feature request?  Does it not line up with the goals of this project?

**Comment by DarkaOnLine** [comment]
In this case I would sugest you disable generation and put your `yaml` file manually in `api-docs/api-docs.yaml`, see: https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php#L59 and https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php#L75

I this case you will be responsible for putting the file in here and use other package features. 

If you can suggest or make a PR for a better solution - it always welcome and appreciated !!!
