### ISSUE TITLE
Changing storage_path() to base_path() for storing api-docs.json deletes entire project folder

### ISSUE THREAD

**Issue by turbo124** [DarkaOnLine/L5-Swagger#226]
- L5-Swagger Version: 6.0.1
- PHP Version:7.3.9
- OS:Ubuntu 18.04.2 LTS

### Description:
I am trying to save the output file to the root of the project directory to include the file in git, to achieve this I am changing the config storage_path('api-docs') to base_path() the next time the docs are generated the entire project is deleted.

### Steps To Reproduce:
Change from storage_path to base_path() in the config.. 
run php artisan l5-swagger:generate

**Comment by DarkaOnLine** [comment]
The script assumes that you have a dedicated folder for your doc's and this is why it removes all files in it. Just add new folder in your project root. Also, you can make a PR to support this possibility.
