### ISSUE TITLE
Requested L5 Swagger asset URL file does not exists

### ISSUE THREAD

**Issue by YaakovDantas** [DarkaOnLine/L5-Swagger#228]
L5-Swagger Version: 5.5.8.3 (composer show | grep l5-swagger)
PHP Version (php -v): 7.0
OS: Linux

Description:
After updating the package, I'm not able to navigate to the documentation. This due to the fact the files aren't found anymore.

See flare-link for stack trace: https://imgur.com/a/ELaohEj

Steps To Reproduce:
Just install the package.

**Comment by DarkaOnLine** [comment]
Can you debug more? It looks like you server config issues

**Comment by YaakovDantas** [comment]
My real path is: "/vbeta-servicos-central/api/documentation/".

**Comment by YaakovDantas** [comment]
There some way to set the URL by myself?

**Comment by DarkaOnLine** [comment]
can you check if request reaches `src/Http/Controllers/SwaggerAssetController.php` (just `dd()` something in it and check if it's reachable.)

**Comment by YaakovDantas** [comment]
It's only being reachable on the .png, on the other files, nothing happen

**Comment by DarkaOnLine** [comment]
It means your server blocks/forwards requests for `.js`, `.css` files to somewhere else.

**Comment by YaakovDantas** [comment]
What can I do ?

**Comment by YaakovDantas** [comment]
Check the img: https://imgur.com/MtHQHzC

**Comment by YaakovDantas** [comment]
If there is some way to set the real path, I think the problem would be solved

**Comment by DarkaOnLine** [comment]
Configure your server correctly. You have your api under different folders and paths are diferent for assets and documentation itself. You can trie moving ui files from package to `docs` in your project root like request is looking or play with config `routes.docs`

**Comment by YaakovDantas** [comment]
After putting the right path on the routes.docs, the response status of the static file is 200-OK, but the page is still white

**Comment by YaakovDantas** [comment]
Insetead of the css file it is comming this
```
<?php

/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylor@laravel.com>
 */

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| our application. We just need to utilize it! We'll simply require it
| into the script here so that we don't have to worry about manual
| loading any of our classes later on. It feels great to relax.
|
*/

require __DIR__.'/../vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Turn On The Lights
|--------------------------------------------------------------------------
|
| We need to illuminate PHP development, so let us turn on the lights.
| This bootstraps the framework and gets it ready for use, then it
| will load up this application so that we can run it and send
| the responses back to the browser and delight our users.
|
*/

$app = require_once __DIR__.'/../bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request
| through the kernel, and send the associated response back to
| the client's browser allowing them to enjoy the creative
| and wonderful application we have prepared for them.
|
*/

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);
```

**Comment by sgotre** [comment]
had a similar issue when upgrading. The old config was cached. 
Thus the swagger_ui_assets_path config is not set 

php artisan config:clear

**Comment by YaakovDantas** [comment]
And solved ?

**Comment by sgotre** [comment]
yes.. but is was my error: one should never cache config in a dev env

**Comment by YaakovDantas** [comment]
Its hard then, because on my localhost everything goes fine, but in the server only problems

**Comment by YaakovDantas** [comment]
I cant even reproduce the error on my local machine

**Comment by sgotre** [comment]
and maybe on your server the config is cached. thus the config might not get updated

**Comment by YaakovDantas** [comment]
https://api.cartoriovirtual.com/vbeta-servicos-central/api/documentation/

this is the problem now, someone must did change something, because it was back to 500 error request, any ideia?

**Comment by YaakovDantas** [comment]
I dont thing config clear, it would be a good solution

**Comment by sgotre** [comment]
the assets have a problem 
https://api.cartoriovirtual.com/vbeta-servicos-central/docs/asset/swagger-ui.css?v=5c0bf3ada2627c67a4dc8f58001155ec

because the directory is not found in   SwaggerAssetController.php

**Comment by YaakovDantas** [comment]
Yeah, but i can't set it right, I really dont know and doest have any access to the server to test directly

**Comment by YaakovDantas** [comment]
First I have to make the same error on my machine, any idea ?

**Comment by sgotre** [comment]
Sorry, can't give you that support here

**Comment by Gossteer** [comment]
Maybe you use common settings for nginx:

```
    location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
        expires max;
        try_files $uri =404;
    }
```

Need add: 
```
    location ~ (^/docs/asset/.*) {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
        expires max;
        try_files $uri =404;
    }
```

Or wait - https://github.com/DarkaOnLine/L5-Swagger/pull/503

**Comment by daiduong47** [comment]
You just need to set L5_SWAGGER_USE_ABSOLUTE_PATH=false instead of true.
That will solve your problem
