### ISSUE TITLE
How can i know where is error line code?

### ISSUE THREAD

**Issue by tantana5** [DarkaOnLine/L5-Swagger#229]
I use openApi 3.0, when i set wrong params some where, how can i know exactly the line of error code? Alway return below message:
The provided definition does not specify a valid version field.
Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).

**Comment by DarkaOnLine** [comment]
This is not in this package scope. You should check swagger-php docs if it is possible to view the line number, but in my experience, it is not :(
