### ISSUE TITLE
unable to try and check API in swagger getting 401 Error: Unauthorized

### ISSUE THREAD

**Issue by unaveen** [DarkaOnLine/L5-Swagger#231]
### Description:
when tried to run the api by swagger getting error as:
{
  "message": "These credentials do not match our records."
}

It's not working when input data are sent as a parameter.

### Steps To Reproduce:

Request URL is: http://localhost/minidmsapi/api/auth/login?email=info&password=password

Response headers: 
access-control-allow-headers: Content-Type, Authorization 
 access-control-allow-methods: GET, PUT, POST, DELETE, OPTIONS 
 access-control-allow-origin: * 
 cache-control: no-cache, private 
 connection: Keep-Alive 
 content-length: 57 
 content-type: application/json 
 date: Fri, 18 Oct 2019 07:54:53 GMT 
 keep-alive: timeout=5, max=100 
 server: Apache/2.4.33 (Win32) OpenSSL/1.1.0g PHP/7.2.4 
 x-powered-by: PHP/7.2.4 
 x-ratelimit-limit: 60 
 x-ratelimit-remaining: 59

**Comment by DarkaOnLine** [comment]
This is Laravel auth error and not he package related issue. You are trying to authenticate and not access the api docs here.
