### ISSUE TITLE
The @OA\Server annotation will be overwritten by L5_SWAGGER_BASE_PATH

### ISSUE THREAD

**Issue by ymhuang0808** [DarkaOnLine/L5-Swagger#235]
- L5-Swagger Version: 6.0.2
- PHP Version (`php -v`): 7.2.22
- OS: macOS

### Description:

The OpenAPI allows us to define the API servers. In L5-Swagger and Swagger-PHP, `@OA\Server`
 annotation can help us define the API servers. However, according to [the line of code](https://github.com/DarkaOnLine/L5-Swagger/blame/master/src/Generator.php#L143), when the `L5_SWAGGER_BASE_PATH` environment variable is set, the definitions of `@OA\Server` will be overwritten by `L5_SWAGGER_BASE_PATH`, instead of appending to another server. 

I was stuck for a while by the `L5_SWAGGER_BASE_PATH` environment variable. Until I cleared the `L5_SWAGGER_BASE_PATH`, my definitions of the `@OA\Server` was generated.

Maybe, I can send a PR to make the `L5_SWAGGER_BASE_PATH` work with `@OA\Server`.

### Steps To Reproduce:

* Write definitions of `@OA\Server` 
* Put `L5_SWAGGER_BASE_PATH` into environment variable
* Generate OpenAPI sepc: `php artisan l5-swagger:generate`
* The `servers` in OpenAPI is overwritten by `L5_SWAGGER_BASE_PATH`

**Comment by DarkaOnLine** [comment]
Hi, yes PR's are always welcome!

**Comment by ymhuang0808** [comment]
@DarkaOnLine Thanks. I will make a PR for solving the issue.

**Comment by DarkaOnLine** [comment]
Fixed in #239
