### ISSUE TITLE
getting error of Failed to load API definition.

### ISSUE THREAD

**Issue by sanjitkumarmishra** [DarkaOnLine/L5-Swagger#236]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):
- OS:

### Description:
Fetch error
Not Found docs/api-docs.json

**Comment by DarkaOnLine** [comment]
You need to generate docs first from your annotations. After that, this file will be available

**Comment by sanjitkumarmishra** [comment]
Can you please let me know how i need to generate doc file and how i will add annotations as i am new for laravel api docs

**Comment by DarkaOnLine** [comment]
https://github.com/DarkaOnLine/L5-Swagger#swaggeropenapi-annotations-and-generating-documentation

**Comment by Mloweedgar** [comment]
@DarkaOnLine for me, I have generated docs using php artisan l5-swagger:generate, but I still get Fetch error
Not Found docs/api-docs.json

**Comment by dallelgaham** [comment]
@Mloweedgar having the same issue. Even if i generate docs, i still get the not found docs/api-docs.json in production. 

Any solution ? please.

**Comment by trung-wiseberry** [comment]
Hi guys, anyone has solved this issue?

**Comment by AHS12** [comment]
I have also faced that problem And for me I used 
`L5_SWAGGER_GENERATE_ALWAYS=true` in env and didn't give write permission to the file(on production) that's why it locally worked but not in production.

`L5_SWAGGER_GENERATE_ALWAYS=false `
is the solution if you use this setting in .env.

**Comment by deyoucasel** [comment]
this issue is caused by the server settings, but i tryed to change the storage patch for the json and its imposible. i cant

**Comment by ArtemSudakov** [comment]
Решил через L5_SWAGGER_GENERATE_ALWAYS = false
