### ISSUE TITLE
Post requests are not working

### ISSUE THREAD

**Issue by mhayajneh** [DarkaOnLine/L5-Swagger#240]
- L5-Swagger Version: 5.8 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.3
- OS:Ubuntu

### Description:
My get requests are working fine but every post request is returning 200 but the body is swagger ui html 

This is my json post

` "\/api\/v1\/password\/create": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "",
                "description": "",
                "operationId": "ResetPassword",
                "consumes":"application/json",
                "produces":"application/json",
                "deprecated": false,
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                },
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "description": "",
                        "schema": {
                            "type": "object",
                            "required": [
                                "email"
                            ],
                            "properties": {
                                "email": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ]
            }
        }`

**Comment by mojimich2015** [comment]
Have the same problem
