### ISSUE TITLE
UI Not Rendering

### ISSUE THREAD

**Issue by marciowinicius** [DarkaOnLine/L5-Swagger#243]
- L5-Swagger Version: 5.7.2
- PHP Version: 7.1.3 
- OS: Windows/Docker/Alpine Linux

### Description:
After a composer update in the last week, my UI is not rendering

### Steps To Reproduce:

<!-
composer update
-->
![image](https://user-images.githubusercontent.com/14933271/70528149-477b5f00-1b2c-11ea-8ee9-7185ad165fee.png)

**Comment by pjhartin** [comment]
I am having the same issue, getting `Loading failed for the <script> with source` error in console for both js scripts, however, if I check the link the script is available.

**Comment by TarasBwt** [comment]
Check if you have custom middleware in your App\Http\Kernel class , or in routes/api ,that may modify request to json.

**Comment by marciowinicius** [comment]
Good @TarasBwt .
It was an custom middleware that always expects json to my API.
