### ISSUE TITLE
Working with nested objects

### ISSUE THREAD

**Issue by lexmagnus** [DarkaOnLine/L5-Swagger#247]
- L5-Swagger Version: 6.0.3 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.3.9

### Description:
I'm trying to create swagger annotations to describe a multidimensional array. for example, should be possible insert this array:
```
$request[ "fields"] = [
    "productTable" => ['name', 'code'],
]
```
this will be working like fields selections or custom fields. As I had some troubles to make a multidimensional array as input, now I'm trying to use objects.

### Steps To Reproduce:

using a example from the internet I had this annotation as parameter of @OA\Get()

```
@OA\Parameter(
     name="body",
     in="query",
     required=false,
     explode=true,
     @OA\Schema(
          collectionFormat="multi",
          required={"product_id"},
          @OA\Property(property="product_id",  type="string",  ),
          @OA\Property(
                property="products",
                type="array",
                @OA\Items(
                      type="object",
                      format="query",
                      @OA\Property(property="name", type="string", ),
                      @OA\Property(property="category", type="string",),
                ),
           ),
     ),
)
```

I got this as input:

```
{
  "product_id": "string",
  "products": [
    {
      "name": "string",
      "category": "string"
    }
  ]
}
```

the problem is when I execute it on swagger documentation I got this array:
```
[
   product_id:"string"
   products:"[object Object]"
]
```

I don't know if this is the best way to do what I want and why I'm getting "[object Object]" on request. Anyone can help me?

**EDIT**

the problem should be because I'm using a GET Request to pass a complex data by url (this code work fine if I'm using RequestBody from POST request). Now I'm thinking about changing the request format, maybe to strings. what do you think about that?

**Comment by ymhuang0808** [comment]
You should prettify the annotation and JSON. It makes the people understand your question easily.
The following syntax may work for you:

```
@OA\Items(
    @OA\Property(property="name", type="string"),
    @OA\Property(property="category", type="string")
)
```
