### ISSUE TITLE
Error with Swagger for laravel 6.5.0

### ISSUE THREAD

**Issue by fredtigersoft** [DarkaOnLine/L5-Swagger#249]
- L5-Swagger Version: #.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):
- OS:

**Comment by DarkaOnLine** [comment]
As an error explains it can't publish cause directory is not writable. You should check your permissions and where are you trying to create assets.

**Comment by fredtigersoft** [comment]
thx
