### ISSUE TITLE
Doesn't work with Laravel 5.1

### ISSUE THREAD

**Issue by mahbubkabir** [DarkaOnLine/L5-Swagger#25]
Seems like minimum requirement for this package is set to 5.2 where as in packagist is saying it's compatible with 5.1, will you be able to support  LR5.1

  Problem 1
    - darkaonline/l5-swagger 3.1.1 requires laravel/framework 5.2.* -> satisfiable by laravel/framework[5.2.x-dev, v5.2.0, v5.2.0-beta1, v5.2.1, v5.2.10, v5.2.11, v5.2.12, v5.2.13, v5.2.14, v5.2.15, v5.2.16, v5.2.17, v5.2.18, v5.2.19, v5.2.2, v5.2.20, v5.2.21, v5.2.22, v5.2.23, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.29, v5.2.3, v5.2.30, v5.2.31, v5.2.32, v5.2.33, v5.2.34, v5.2.35, v5.2.36, v5.2.37, v5.2.38, v5.2.39, v5.2.4, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9] but these conflict with your requirements or minimum-stability.
    - darkaonline/l5-swagger 3.1 requires laravel/framework 5.2.* -> satisfiable by laravel/framework[5.2.x-dev, v5.2.0, v5.2.0-beta1, v5.2.1, v5.2.10, v5.2.11, v5.2.12, v5.2.13, v5.2.14, v5.2.15, v5.2.16, v5.2.17, v5.2.18, v5.2.19, v5.2.2, v5.2.20, v5.2.21, v5.2.22, v5.2.23, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.29, v5.2.3, v5.2.30, v5.2.31, v5.2.32, v5.2.33, v5.2.34, v5.2.35, v5.2.36, v5.2.37, v5.2.38, v5.2.39, v5.2.4, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9] but these conflict with your requirements or minimum-stability.
    - darkaonline/l5-swagger 3.0.1 requires laravel/framework 5.2.* -> satisfiable by laravel/framework[5.2.x-dev, v5.2.0, v5.2.0-beta1, v5.2.1, v5.2.10, v5.2.11, v5.2.12, v5.2.13, v5.2.14, v5.2.15, v5.2.16, v5.2.17, v5.2.18, v5.2.19, v5.2.2, v5.2.20, v5.2.21, v5.2.22, v5.2.23, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.29, v5.2.3, v5.2.30, v5.2.31, v5.2.32, v5.2.33, v5.2.34, v5.2.35, v5.2.36, v5.2.37, v5.2.38, v5.2.39, v5.2.4, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9] but these conflict with your requirements or minimum-stability.
    - darkaonline/l5-swagger 3.0 requires laravel/framework 5.2.* -> satisfiable by laravel/framework[5.2.x-dev, v5.2.0, v5.2.0-beta1, v5.2.1, v5.2.10, v5.2.11, v5.2.12, v5.2.13, v5.2.14, v5.2.15, v5.2.16, v5.2.17, v5.2.18, v5.2.19, v5.2.2, v5.2.20, v5.2.21, v5.2.22, v5.2.23, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.29, v5.2.3, v5.2.30, v5.2.31, v5.2.32, v5.2.33, v5.2.34, v5.2.35, v5.2.36, v5.2.37, v5.2.38, v5.2.39, v5.2.4, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9] but these conflict with your requirements or minimum-stability.
    - Installation request for darkaonline/l5-swagger ~3.0 -> satisfiable by darkaonline/l5-swagger[3.0, 3.0.1, 3.1, 3.1.1].

**Comment by mahbubkabir** [comment]
I don't think you need to hard use Laravel 5.2, try changing here to 5.1 and everything else should work fine https://github.com/DarkaOnLine/L5-Swagger/blob/master/composer.json#L18

**Comment by DarkaOnLine** [comment]
@mahbubkabir 

Added `"laravel/framework": "5.1.*|5.2.*"`

Please check if everything is working correctly and let me know

**Comment by mahbubkabir** [comment]
@DarkaOnLine Thanks a lot for fixing this. But I would say it would be better to use "laravel/framework": ">=5.1.*" which will cover any versions from 5.1
