### ISSUE TITLE
Add the ability to change assets routes

### ISSUE THREAD

**Issue by akalongman** [DarkaOnLine/L5-Swagger#250]
Please add the ability to change css/js file routes. Because of Nginx, all files with css/js extension are handled by himself (which is on a separate server) and therefore swagger does not work (not able to include assets).

For example, laravel-debgubar includes javascript from route `https://laravel/_debugbar/assets/javascript?v=1569336942` and this working because of missing extension.

**Comment by DarkaOnLine** [comment]
You can overwrite the route by this example: https://github.com/DarkaOnLine/L5-Swagger/blob/master/src/routes.php#L19

**Comment by akalongman** [comment]
@DarkaOnLine as I understand it will not work. In the route 
```
$router->get(config('l5-swagger.routes.docs').'/asset/{asset}', [
        'as' => 'l5-swagger.asset',
        'middleware' => config('l5-swagger.routes.middleware.asset', []),
        'uses' => '\L5Swagger\Http\Controllers\SwaggerAssetController@index',
    ]);
```
I want to change `{asset}` part and remove `.js`/`.css` extensions

**Comment by DarkaOnLine** [comment]
You also can update `resources/views/index.blade.php` file if you publish it. Or you can change `l5_swagger_asset()` helper function to serve files as you needed. You have a lot of approaches here IMHO.
