### ISSUE TITLE
[QUESTION] Required @OA\Info() not found

### ISSUE THREAD

**Issue by stesvis** [DarkaOnLine/L5-Swagger#251]
I installed the package and I am getting:

> ErrorException  : Required @OA\Info() not found

Do ALL the methods need the api annotations in order to run successfully? I started to add annotations to SOME just to see if it worked, but it doesn't look like i can do that.

It would be nice if if was able to pick the APIs with the documentation and generate only those ones maybe?

Thanks

**Comment by tezrik** [comment]
@stesvis  why is it closed issue ?

**Comment by tezrik** [comment]
https://github.com/DarkaOnLine/L5-Swagger/wiki/Installation-&-Configuration#after-the-annotiations-have-been-added-you-can-run-php-artisan-l5-swaggergenerate-to-generate-the-documentation

**Comment by fadiahac** [comment]
For testing write this code to any of the controller's method-

`/**
 * @OA\Info(title="My First API", version="0.1")
 */`

Also, a sample API documentation as below-
`/**

     * @OA\Get(

     *  path="/v1/user/account/validate",

     *  operationId="accountValidate",

     *  summary="validates an account",

     *  @OA\Parameter(name="email",

     *    in="query",

     *    required=true,

     *    @OA\Schema(type="string")

     *  ),

     *  @OA\Response(response="200",

     *    description="Validation Response",

     *  )

     * )

     */`

then run `php artisan l5-swagger:generate`

**It will generate your API doc. **

**Comment by fadiahac** [comment]
For testing write this code to any of the controller's method-

/** @OA\Info(title="My First API", version="0.1") */


Also, a sample API documentation as below-
/**
     * @OA\Get(

     *  path="/v1/user/account/validate",

     *  operationId="accountValidate",

     *  summary="validates an account",

     *  @OA\Parameter(name="email",

     *    in="query",

     *    required=true,

     *    @OA\Schema(type="string")

     *  ),

     *  @OA\Response(response="200",

     *    description="Validation Response",

     *  )

     * )

     */

then run `php artisan l5-swagger:generate`

**It will generate your API doc.**

**Comment by hayjay** [comment]
If you are getting this error:

` ErrorException 

  Required @OA\Info() not found`

then add this code below to your Laravel's base controller to avoid repetition across every single controllers you create:

`/**
 * @OA\Info(
 *    title="Your super  ApplicationAPI",
 *    version="1.0.0",
 * )
 */`

So, at the end of the day, your Laravel base controller should look like this:
`<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

/**
 * @OA\Info(
 *    title="Your super  ApplicationAPI",
 *    version="1.0.0",
 * )
 */

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}
`
<img width="775" alt="Screenshot 2022-02-09 at 07 56 38" src="https://user-images.githubusercontent.com/23115829/153146397-a4d902d2-ab30-446a-b113-efadcfd2f1a0.png">

**Comment by bhattaxay** [comment]
I have done the samething, but still it's not generating the docs

**Comment by rizkhal** [comment]
Same problem here

bellow the swagger version i use on laravel 9
```
darkaonline/l5-swagger                 8.3.2
swagger-api/swagger-ui                 v4.11.0
zircote/swagger-php                    4.4.0
```

**Comment by rizkhal** [comment]
I solved it after move `version` before `title`

```
/**
 * @OA\Info(
 *     version="1.0",
 *     title="Sample API Documentation"
 * )
 */
```

**Comment by DerManoMann** [comment]
The example from @hayjay has an invalid trailing `,` after the version number.
The doctrine annotations library is sometimes picky with what it tolerates and what not. The order should not make any difference.

**Comment by rizkhal** [comment]
Oh yes my mistake, i don't see the `,`
Thanks sir
