### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function OpenApi\scan()

### ISSUE THREAD

**Issue by suvam1671** [DarkaOnLine/L5-Swagger#253]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.2
- OS: ubuntu

### Description:
I am using darkaonline/l5-swagger: 6 and composer require 'zircote/swagger-php:2.*' for Swagger annotation and my project in Laravel 6. Please help me quickly
The problem is that in Generator.php below code is:
Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function OpenApi\scan()

  at /data/dev106/cnp777-backend/vendor/darkaonline/l5-swagger/src/Generator.php:117
    113|      */
    114|     protected function scanFilesForDocumentation()
    115|     {
    116|         if ($this->isOpenApi()) {
  > 117|             $this->swagger = \OpenApi\scan(
    118|                 $this->annotationsDir,
    119|                 ['exclude' => $this->excludedDirs]
    120|             );
    121|         }

  Exception trace:

  1   L5Swagger\Generator::scanFilesForDocumentation()
      /data/dev106/cnp777-backend/vendor/darkaonline/l5-swagger/src/Generator.php:66

### Steps To Reproduce:
php artisan l5-swagger:generate

**Comment by DarkaOnLine** [comment]
Set `'swagger_version' => env('SWAGGER_VERSION', '2.0'),` in your config and run composer update

**Comment by suvam1671** [comment]
I set 'swagger_version' => env('SWAGGER_VERSION', '2.0'), on config, when I run in local it's working good but it's not working on development server.

Also, a new issue shown:-
L5Swagger\Exceptions\L5SwaggerException  : Documentation storage directory is not writable

 at /data/dev106/cnp777-backend/vendor/darkaonline/l5-swagger/src/Generator.php:80
   76|      */
   77|     protected function prepareDirectory()
   78|     {
   79|         if (File::exists($this->docDir) && ! is_writable($this->docDir)) {
 > 80|             throw new L5SwaggerException('Documentation storage directory is not writable');
   81|         }
   82|
   83|         // delete all existing documentation
   84|         if (File::exists($this->docDir)) {

**Comment by DarkaOnLine** [comment]
So maybe on server you have `SWAGGER_VERSION` different value in your `.env` file?

`Documentation storage directory is not writable` - I think the error is self-explanatory :)
