### ISSUE TITLE
The annotation "@OpenApi\Annotations\POST" does not exist, or could not be auto-loaded.

### ISSUE THREAD

**Issue by JustinRijsdijk** [DarkaOnLine/L5-Swagger#254]
- L5-Swagger Version: 5.8
- PHP Version (`php -v`): 7.3
- OS: CentOS7

### Description:
After cloning my repo with l5 swagger from github, and running composer install

Error:
Regenerating docs

   ErrorException  : [Semantical Error] The annotation "@OpenApi\Annotations\POST" in \App\Api\V1\Controllers\LoginController->login() in /var/www/GMS-API/app/Api/V1/Controllers/LoginController.php on line 15 does not exist, or could not be auto-loaded.

  at /var/www/GMS-API/vendor/zircote/swagger-php/src/Logger.php:39
    35|         $this->log = function ($entry, $type) {
    36|             if ($entry instanceof Exception) {
    37|                 $entry = $entry->getMessage();
    38|             }
  > 39|             trigger_error($entry, $type);
    40|         };
    41|     }
    42|
    43|     /**

  Exception trace:

  1   trigger_error("[Semantical Error] The annotation "@OpenApi\Annotations\POST" in \App\Api\V1\Controllers\LoginController->login() in /var/www/GMS-API/app/Api/V1/Controllers/LoginController.php on line 15 does not exist, or could not be auto-loaded.")
      /var/www/GMS-API/vendor/zircote/swagger-php/src/Logger.php:39

  2   OpenApi\Logger::OpenApi\{closure}("[Semantical Error] The annotation "@OpenApi\Annotations\POST" in \App\Api\V1\Controllers\LoginController->login() in /var/www/GMS-API/app/Api/V1/Controllers/LoginController.php on line 15 does not exist, or could not be auto-loaded.")
      /var/www/GMS-API/vendor/zircote/swagger-php/src/Logger.php:61

  Please use the argument -v to see more details.

**Comment by derekrprice** [comment]
I just started getting this error too after a clean rebuild.   Not sure why.

**Comment by derekrprice** [comment]
It appears to be failing for me on a case-sensitive file system but not on a case-insensitive one.  Could some file loader be failing to match a mis-cased file?

**Comment by derekrprice** [comment]
This was it.  zircote/swagger-php has Annotations in files named Post, Get, Delete, etc...  as tempting as it is to write "@OA/POST" and "@OA/GET", don't, unless all the file systems that you must run under are case insensitive.

**Comment by Jlonghi** [comment]
Can confirm have this exact issue. Changed GET to Get and it worked.

**Comment by Nowi5** [comment]
Yes, in the case for Linux you have to use Get and not GET, same for Post and not POST.
It would be great to have some annotations plugin e.g. for PhpStorm.
