### ISSUE TITLE
Installing darkaonline/l5-swagger:5.7.* failed on Laravel 5.7

### ISSUE THREAD

**Issue by mithredate** [DarkaOnLine/L5-Swagger#257]
- L5-Swagger Version: 5.7.*
- PHP Version 7.2.24:
- OS: ubuntu

### Description:
I can't install the package on Laravel 5.7.

### Steps To Reproduce:
composer require "darkaonline/l5-swagger:5.7.*"

Output:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/yaml (locked at v5.0.4) -> satisfiable by symfony/yaml[v5.0.4].
    - Conclusion: don't install darkaonline/l5-swagger 5.7.2
    - Conclusion: don't install darkaonline/l5-swagger 5.7.1
    - Can only install one of: laravel/framework[v5.7.28, 5.6.x-dev].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.7.28].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.7.28].
    - darkaonline/l5-swagger 5.7.0 requires laravel/framework 5.6.* -> satisfiable by laravel/framework[5.6.x-dev].
    - Installation request for darkaonline/l5-swagger 5.7.* -> satisfiable by darkaonline/l5-swagger[5.7.0, 5.7.1, 5.7.2].
    - Installation request for laravel/framework (locked at v5.7.28, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.28].

Installation failed, reverting ./composer.json to its original content.

**Comment by DarkaOnLine** [comment]
Merging this to #259 . Looks like the same issue.
