### ISSUE TITLE
How to add header parameter to every endpoint

### ISSUE THREAD

**Issue by Deifinger** [DarkaOnLine/L5-Swagger#260]
- L5-Swagger Version: 6.0.3 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.4
- OS: Use Docker image php:7.4-fpm-alpine

### Description:

I have a parameter, which one I want to add to every endpoint. It's "Accept-Language" in headers. How I can do it? Do some schema or maybe describe it with some other rules?

Now I have to duplicate @OA\Parameter in every endpoint description.

My code for now:
```
/**
     * @OA\Post(
     *     path="/v1/api/endpoint",
     *     summary="My summary here",
     *     operationId="endpointOperationId",
     *     tags={"Tag"},
     *     @OA\Parameter(
     *         name="Accept-Language",
     *         in="header",
     *         description="Set language parameter by RFC2616 <https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4>",
     *         @OA\Schema(
     *             type="string"
     *         )
     *     ),
     *     @OA\RequestBody(
     *         required=true,
     *         description="Endpoit request",
     *         @OA\JsonContent(ref="#/components/schemas/EndpointRequest")
     *     )
     *  )

```

**Comment by DarkaOnLine** [comment]
You need to dig into OpenApi documentation for this. At least you definitely should be able to have header component like you have `ref="#/components/schemas/EndpointRequest"`

Sorry but not much help from this package side :(

**Comment by zhovtyj** [comment]
@Deifinger Have you found an answer?

**Comment by Deifinger** [comment]
@zhovtyj The only way I found is generating OpenApi documentation by other tools/plugins.
