### ISSUE TITLE
[Question] Possibility to set domain and other route group options

### ISSUE THREAD

**Issue by ThaDaVos** [DarkaOnLine/L5-Swagger#261]
- L5-Swagger Version: 6.0.3 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.3.14
- OS: WSL 2 - Ubuntu 18

### Description:
Is it possible that the route definitions get updated so one can set the options for the route group? For-example the domain? Like it's possible in Laravel/Passport

I'm in progress of building a multi-tenant application, or better said, a oauth server with it's own views and use it with another domain to show an example client.

**Comment by DarkaOnLine** [comment]
Not sure if this is what you looking for but maybe constants could help you: https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php#L235

**Comment by ThaDaVos** [comment]
Not really, what I'm talking about is the `domain` option one can pass to `Route::group(['domain' => '{DOMAIN}'])`. This way one can set the domain on which the route is available

**Comment by ThaDaVos** [comment]
Or better said, can pass here: https://github.com/DarkaOnLine/L5-Swagger/blob/a7d8337a7c1de8961d754b6e4b9825afc2c50666/src/routes.php#L6

**Comment by ThaDaVos** [comment]
Maybe change to the following:
```php
Route::group(array_merge(['namespace' => 'L5Swagger'], config('L5-Swagger.routes.group_options', [])), function (Router $router) { 
```

**Comment by DarkaOnLine** [comment]
Sound good. Can you make a PR for this? 

I am thinking that `L5-Swagger.routes.group_options` the default value could be `['namespace' => 'L5Swagger']` so that we do not need to array_merge

**Comment by rodrigowbazevedo** [comment]
I want this too, I willing to send a PR.
