### ISSUE TITLE
HTTPS issue in production  environment

### ISSUE THREAD

**Issue by HarriesChen** [DarkaOnLine/L5-Swagger#262]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):
- OS:

### Description:

when request /api/documentation with HTTPS

but the asset is still load by HTTP , so it will failed when use http

the problem is cased by this function 
```
function l5_swagger_asset($asset)
    {
        $file = swagger_ui_dist_path($asset);

        if (! file_exists($file)) {
            throw new L5SwaggerException(sprintf('Requested L5 Swagger asset file (%s) does not exists', $asset));
        }

        return route('l5-swagger.asset', $asset).'?v='.md5_file($file);
    }
```

return value is always http 

I try to edit APP_URL but it dost not work 

So I have to forceScheme in the boot

```
 if (env('APP_ENV') !== 'local') {
      $url->forceScheme('https');
 }
```

is it a bug or there is something I need to config?

**Comment by DarkaOnLine** [comment]
`l5-swagger.asset` is a route and you are in control of it. So you should configure your routing/app properly to return `https`

**Comment by rickmills** [comment]
Might help if this gets documented somewhere as if you're using a load balanced setup then your application isn't set to use https, the load balancer is - adding a route forcing https in this situation would cause your entire codebase to stop working.
