### ISSUE TITLE
Security keyword for global API security is not supported

### ISSUE THREAD

**Issue by denis-kopelevich** [DarkaOnLine/L5-Swagger#266]
- L5-Swagger Version: 5.8.3

### Description:
Security can be setted up only per path like
``` @OA\Get(..., security={{"ApiKeyAuth": {}}},...)```
but OpenApi supports global security scheme setup. Please check documentation here: https://swagger.io/docs/specification/basic-structure/ (Authentication at the end of page) and https://swagger.io/docs/specification/authentication/ (Step 2. Applying security)

If i add this code
```
    "security": [
        {
            "ApiKeyAuth": []
        }
    ]
```
at the end of generated JSON, swagger-ui adds security to each path in API and using additional header, defined via Authorize button in UI.

I think ```@OA\Security``` annotation support should be added to l5-swagger.

**Comment by DarkaOnLine** [comment]
You should be able to use `security` config for this: https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php#L125

**Comment by denis-kopelevich** [comment]
As i understand, this security config only for defining security schemes and i can't apply defined security schemes to API globally. YAML of security schemes described here https://swagger.io/docs/specification/authentication/ in Step 1, but compatibility with Step 2 is needed.

> After you have defined the security schemes in the securitySchemes section, you can apply them to the whole API or individual operations by adding the security section on the root level or operation level, respectively.

Now i can apply security scheme only on operation level (to the method of API), but not on root level (to all urls of API).

```
    "security": [
        {
            "ApiKeyAuth": []
        }
    ]
```
If i paste this json on the root level of generated file (not for each path of generated file), then security scheme ApiKeyAuth applied to all paths in API.

**Comment by DarkaOnLine** [comment]
Oh, you are correct. We are now supporting only `securitySchemes` but not a global `security`. But this can be implemented in the same way as `securitySchemes`. Would you be willing to make a PR for this?

**Comment by DarkaOnLine** [comment]
@denis-kopelevich - this feature was implemented and now is in current RC: https://github.com/DarkaOnLine/L5-Swagger/releases/tag/8.x-rc
