### ISSUE TITLE
Generation of several schemes

### ISSUE THREAD

**Issue by yzen-dev** [DarkaOnLine/L5-Swagger#272]
Hi!
Can I specify different directories for generation, so that I get several schemes at the output?

**Comment by yzen-dev** [comment]
I see that there is already such a PL:
https://github.com/DarkaOnLine/L5-Swagger/pull/270

When are you planning to finalize and publish it?
I already thought that I’ll have to fork the project and modify it myself

**Comment by rodrigowbazevedo** [comment]
> I see that there is already such a PL:
> #270
> 
> When are you planning to finalize and publish it?
> I already thought that I’ll have to fork the project and modify it myself

I'm using this PR locally while it's not approved...

**Comment by DarkaOnLine** [comment]
#270 PR is almost ready, just need to polish a little bit and I will release RC version
