### ISSUE TITLE
php artisan l5-swagger:generate - ErrorException  : Required @OA\Info() not found

### ISSUE THREAD

**Issue by LorddXknowsy** [DarkaOnLine/L5-Swagger#273]
**root@7b96f87005a8:/application# php artisan l5-swagger:generate**
Regenerating docs

   ErrorException  : Required @OA\Info() not found

>    at /application/vendor/zircote/swagger-php/src/Logger.php:39
>     35|         $this->log = function ($entry, $type) {
>     36|             if ($entry instanceof Exception) {
>     37|                 $entry = $entry->getMessage();
>     38|             }
>   > 39|             trigger_error($entry, $type);
>     40|         };
>     41|     }
>     42| 
>     43|     /** 

  Exception trace:

  1   trigger_error("Required @OA\Info() not found")
      /application/vendor/zircote/swagger-php/src/Logger.php:39

  2   OpenApi\Logger::OpenApi\{closure}("Required @OA\Info() not found")
      /application/vendor/zircote/swagger-php/src/Logger.php:71

  Please use the argument -v to see more details.

 **I'm using Windows 10 OS, 
 This occurred to 'Swagger' framework, when it was implementing in Laravel 5.6.0v documentation**

**Comment by yzen-dev** [comment]
What is the problem of adding this annotation?
Add this to the main controller and that's it:
`/**
* @OA\Info(
*     title="My the best API",
*     version="1.0.0"
*/`

**Comment by DarkaOnLine** [comment]
From the example looks like you are missing `)` closing bracket :) But we have so much issue with this, please search. The answer to this is always bad annotation syntax.
