### ISSUE TITLE
Impossible to create the root directory - swagger with laravel

### ISSUE THREAD

**Issue by rasyid46** [DarkaOnLine/L5-Swagger#274]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php  7.2 `) laravel 6:
- OS:

### Steps To Reproduce:

 
php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"

 League\Flysystem\Exception  : Impossible to create the root directory "". 

Impossible to create the root directory - swagger with laravel 
 
 https://stackoverflow.com/questions/59133714/impossible-to-create-the-root-directory-swagger-with-laravel

**Comment by mksaeed** [comment]
Any Luck? facing the same issue in laravel 6

**Comment by DarkaOnLine** [comment]
This is Windows, I have no idea how permissions are handled/working. Maybe try to create directories by your self?

**Comment by mksaeed** [comment]
The issue was **config/l5-swagger.php** was not returning null to config('l5-swagger.paths.views')

run php artisan config:cache fixed the problem :)

**Comment by rasyid46** [comment]
> The issue was **config/l5-swagger.php** was not returning null to config('l5-swagger.paths.views')
> 
> run php artisan config:cache fixed the problem :)

thanky you already fixed
