### ISSUE TITLE
Cannot disable docs on production

### ISSUE THREAD

**Issue by PaddyLock** [DarkaOnLine/L5-Swagger#275]
- L5-Swagger Version: 6.0.3 (`composer show | grep l5-swagger`)
- PHP Version 7.2.24 (`php -v`):
- OS: Ubuntu 18

### Description:

I cannot stop the api docs from being auto generated on production

### Steps To Reproduce:

With reference to this issue #139 I cannot find a way to stop the api docs from being produced on production apart from creating a dummy empty json file.

I have L5_SWAGGER_GENERATE_ALWAYS=false in my .env on production

If I look at the code that generates the api docs when previewing them I see

`if (config('l5-swagger.generate_always') || ! File::exists($filePath)) {`

So, the docs will be produced even if L5_SWAGGER_GENERATE_ALWAYS=false as long as there is no json file present.

So what is the best way to prevent the api docs from being produced on production?
Can I switch off the documentation route for production only?
If it can be done with middleware, how please?

Thanks

**Comment by DarkaOnLine** [comment]
If you want to disable documentation entirely in production when yes - middleware is the way to go. 

Just register your middleware class here: https://github.com/DarkaOnLine/L5-Swagger/blob/6.x/config/l5-swagger.php#L47 which on production returns access denied and on dev allows to visit.

**Comment by PaddyLock** [comment]
I have now disabled the generation of the docs with middleware, but how do I also block the route entirely?

**Comment by cawa0505** [comment]
> I have now disabled the generation of the docs with middleware, but how do I also block the route entirely, so it shows a 404?

add middleware class to here:
https://github.com/DarkaOnLine/L5-Swagger/blob/6.x/config/l5-swagger.php#L45

like this
```
'middleware' => [
    'api' => [
        \App\Http\Middleware\NotFoundWhenProduction::class,
    ],
    ...
]
```

**Comment by PaddyLock** [comment]
thanks @cawa0505 but this was so long ago I can't find my middleware class now. What should NotFoundWhenProduction class look like please?

**Comment by github-cuongvm** [comment]
@PaddyLock 
continue from @cawa0505 
`namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Response;

class NotFoundWhenProduction
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $env = config('app.env');
        if($env == "production"){
            return $this->unauthorized();
        }
        return $next($request);
    }

    private function unauthorized($message = null){
        return response()->json([
            'code' => Response::HTTP_FORBIDDEN,
            'message' => $message ? $message : 'You are unauthorized to access this resource',
        ], Response::HTTP_FORBIDDEN);
    }
}`
