### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by K2ouMais** [DarkaOnLine/L5-Swagger#276]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):
- OS:

### Description:
Every request is made with ```Accept: */*``` and the ```X-CSRF-TOKEN```.

### Steps To Reproduce:

Every request...

Is there a way to set the Accept header and delete the empty X-CSRF-TOKEN header?

Thanks in advance

**Comment by DarkaOnLine** [comment]
You can control header in view file `resources/views/index.blade.php` (don't forget to export them)

https://github.com/DarkaOnLine/L5-Swagger/blob/7.x/resources/views/index.blade.php#L85

**Comment by allestaire** [comment]
Sadly, the newer version does not put tag name when publishing views
