### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by ravi2katre** [DarkaOnLine/L5-Swagger#278]
Using version ^7.0 for darkaonline/l5-swagger
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> php artisan package:discover --ansi

   TypeError

  Argument 1 passed to L5Swagger\Generator::__construct() must be of the type string, null given, called in C:\wamp64\www\GIT\laravel\vendor\darkaonline\l5-swagger\src\L5SwaggerServiceProvider.php on line 66

  at C:\wamp64\www\GIT\laravel\vendor\darkaonline\l5-swagger\src\Generator.php:62
    58|      * @var string
    59|      */
    60|     protected $swaggerVersion;
    61|
  > 62|     public function __construct(
    63|         string $annotationsDir,
    64|         string $docDir,
    65|         string $docsFile,
    66|         string $yamlDocsFile = '',

  1   C:\wamp64\www\GIT\laravel\vendor\darkaonline\l5-swagger\src\L5SwaggerServiceProvider.php:66
      L5Swagger\Generator::__construct("/api-docs.json", "/api-docs.yaml", [])

  2   C:\wamp64\www\GIT\laravel\vendor\laravel\framework\src\Illuminate\Container\Container.php:801
      L5Swagger\L5SwaggerServiceProvider::L5Swagger\{closure}(Object(Illuminate\Foundation\Application), [])

   Whoops\Exception\ErrorException

  Module 'openssl' already loaded

  at Unknown:0

**Comment by DarkaOnLine** [comment]
This is related to windows or caching. We had the same issues here #271

And possible fix: https://github.com/DarkaOnLine/L5-Swagger/issues/271#issuecomment-620162708
