### ISSUE TITLE
Undefined property error in swagger-php when generating docs

### ISSUE THREAD

**Issue by simon-4c** [DarkaOnLine/L5-Swagger#279]
- L5-Swagger Version: 7.0
- PHP Version (`php -v`): 7.4.6
- OS: Ubuntu 18.04

### Description:
`composer update` breaks api docs generation with 'Undefined property' error in `zircote/swagger-php`

### Steps To Reproduce:

`php artisan l5-swagger:generate`

Output is:

> Regenerating docs
> 
>    ErrorException
> 
>   Undefined property: OpenApi\Processors\MergeJsonContent::$_context
> 
>   at vendor/zircote/swagger-php/src/Processors/MergeJsonContent.php:30
>     26|         foreach ($annotations as $jsonContent) {
>     27|             $parent = $jsonContent->_context->nested;
>     28|             if (!($parent instanceof Response) && !($parent instanceof RequestBody) && !($parent instanceof Parameter)) {
>     29|                 if ($parent) {
>   > 30|                     Logger::notice('Unexpected '.$jsonContent->identity() .' in ' . $parent->identity() . ' in ' . $this->_context);
>     31|                 } else {
>     32|                     Logger::notice('Unexpected '.$jsonContent->identity() .' must be nested');
>     33|                 }
>     34|                 continue;
> 
>       +20 vendor frames
>   21  artisan:37
>       Illuminate\Foundation\Console\Kernel::handle()

**Comment by DarkaOnLine** [comment]
So this is related to parsing your annotations. This means you have badly constructed your annotations or `zircote/swagger-php` has an issue. Without seeing annotations not much I can help here :(

**Comment by simon-4c** [comment]
Hi
Unfortunately I'm not able to publish the annotations as they're in commercial code.
However, the annotations have been stable for a while and I had no problem until I did a `composer update` this week. I now get the above error. It may well be an issue in `zircote/swagger-php` but the error is somewhat less than helpful.

**Comment by simon-4c** [comment]
Update: it appears this is a change to `zircote/swagger-php` in the way it handles malformed annotations. You're right - there was a problem with a reference to `@OA\JsonContent` inside a '@OA\MediaType` which it had been happily accepting before. I temporarily changed the failing line to show me the problem items. I guess they must have tightened up the checks but then the error handler fails to work properly, so a bug in `zircote/swagger-php` and *also* a bug in my annotations!
