### ISSUE TITLE
Can't read swagger JSON

### ISSUE THREAD

**Issue by ollakalla** [DarkaOnLine/L5-Swagger#28]
i follow your documentation 
and after i publish everything
i go to the path http://localhost:8090/api/documentation and i have this error
`Can't read swagger JSON from http://localhost:8090/docs/api-docs.json`
what i suppose to do ?

**Comment by DarkaOnLine** [comment]
Did you  created docs directory `storage_path('api-docs')` and did you generated them using artisan command or updated your config to generate them always ?

**Comment by ollakalla** [comment]
I have created now folder "api-docs" inside _storage_ folder
and run
`php artisan l5-swagger:publish`
and i still have this error
> Can't read swagger JSON from http://localhost:8090/docs/api-docs.json

**Comment by ollakalla** [comment]
it is working now after i run
`php artisan l5-swagger:generate`

**Comment by ollakalla** [comment]
it is working now after i run
`php artisan l5-swagger:generate`

**Comment by DarkaOnLine** [comment]
Glad you figured it out. 

By the way, you can set L5_SWAGGER_GENERATE_ALWAYS=true in your config file, so that json file will be regenerated on every request. Just disable it in production environment ;)

**Comment by vishalmandora** [comment]
I followed all the steps as per your documentation but still i'm getting error (Laravel Version 5.3 & Swagger Version 3.0)

It works fine when i issue following command "**php artisan serve**"
![screen shot 2017-04-15 at 10 38 18 am](https://cloud.githubusercontent.com/assets/22556281/25060968/23701994-21c8-11e7-9bb2-ce4bfd21190c.png)

But It gives error when i issue following command "**php -S 192.168.11.80:8585 -t public**"
![screen shot 2017-04-15 at 10 38 02 am](https://cloud.githubusercontent.com/assets/22556281/25060960/e1995ae4-21c7-11e7-97a6-ecd47b713eb0.png)

**Comment by DarkaOnLine** [comment]
What error do you see visiting json file directly or
 192.168.11.80:8585/docs/api-docs.json

**Comment by vishalmandora** [comment]
Getting this error
![screen shot 2017-04-15 at 11 26 03 am](https://cloud.githubusercontent.com/assets/22556281/25061196/60bfd2a2-21ce-11e7-9fb6-81041e06d07a.png)

**Comment by DarkaOnLine** [comment]
It looks like your stand alone php server is not generating .json file. Can you see your documentation .json file in desired directory when you start your php server ? Does `L5_SWAGGER_GENERATE_ALWAYS` is set to TRUE ?

Like you can see this problem is not associated with package it self because it is working on `php artisan serve`

**Comment by Lauriy** [comment]
Had this problem due to using PHP built-in web server and not artisan serve.

**Comment by ankitjain28may** [comment]
I am getting the same issue, is it fixed ?

**Comment by rahulsha01** [comment]
Hello Team,
I am not able to generate swagger key i am getting blow error. please help me out...

Regenerating docs

   Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function Swagger\scan()

  at E:\Rahul\shopingWebsite\UMart\vendor\darkaonline\l5-swagger\src\Generator.php:124
    120|             );
    121|         }
    122| 
    123|         if (! $this->isOpenApi()) {
  > 124|             $this->swagger = \Swagger\scan(
    125|                 $this->annotationsDir,
    126|                 ['exclude' => $this->excludedDirs]
    127|             );
    128|         }

  Exception trace:

  1   L5Swagger\Generator::scanFilesForDocumentation()
      E:\Rahul\shopingWebsite\UMart\vendor\darkaonline\l5-swagger\src\Generator.php:66

  2   L5Swagger\Generator::generateDocs()
      E:\Rahul\shopingWebsite\UMart\vendor\darkaonline\l5-swagger\src\Console\GenerateDocsCommand.php:32

  Please use the argument -v to see more details.

e:\Rahul\shopingWebsite\UMart>php artisan l5-swagger:generate
Regenerating docs

   Symfony\Component\Debug\Exception\FatalThrowableError  : Call to a member function saveAs() on null

  at E:\Rahul\shopingWebsite\UMart\vendor\darkaonline\l5-swagger\src\Generator.php:164
    160|      * @return Generator
    161|      */
    162|     protected function saveJson()
    163|     {
  > 164|         $this->swagger->saveAs($this->docsFile);
    165| 
    166|         $security = new SecurityDefinitions();
    167|         $security->generate($this->docsFile);
    168|

**Comment by haiderShamil** [comment]
i follow your documentation
and after i run oho artisan serve
i go to the path http://localhost:8090/api/documentation and i have this error

Fetch errorNot Found http://127.0.0.1:8000/docs/api-docs.json
 
what i suppose to do ?

**Comment by smtlab** [comment]
Yes please I have the same error I see the `php artisan l5-swagger:generate` command generates json file in `storage/api-docs.json`

But the swagger-ui is trying to access the file from the location public/docs/api-docs.json

Do I manually need to link `storage/api-docs.josn` to `public/docs/api-docs.json`?

**Comment by ahmed-al-bermawy** [comment]
> Yes please I have the same error I see the `php artisan l5-swagger:generate` command generates json file in `storage/api-docs/api-docs.json`
> 
> But the swagger-ui is trying to access the file from the location public/docs/api-docs.json
> 
> Do I manually need to link `storage/api-docs/api-docs.josn` to `public/docs/api-docs.json`? or am i missing some config settings?
> 
> And I see the doc generation path is set as below by default in the config
> `'docs' => storage_path('api-docs')`
> 
> And the UI is trying to access it from public location how this is going to work?
> 
> ```
>         /*
>         |--------------------------------------------------------------------------
>         | Route for accessing parsed swagger annotations.
>         |--------------------------------------------------------------------------
>         */
> 
>         'docs' => 'docs',
> ```

you don't have to link it manually

you just need to set the routes API for me 
``` 
'routes' => [
        /*
        |--------------------------------------------------------------------------
        | Route for accessing api documentation interface
        |--------------------------------------------------------------------------
        */

        'api' => 'backend/api/documentation',
```
so i access it from URL with this link 

http://localhost:8000/backend/api/documentation

also, you need to check the middleware 
for me it is 

```
        'middleware' => [
            'api' => ['web', 'auth'],
            'asset' => [],
            'docs' => ['web', 'auth'],
            'oauth2_callback' => [],
        ],
```

**Comment by smtlab** [comment]
@ahmed-al-bermawy I missed the middleware part :)
