### ISSUE TITLE
Call to undefined function OpenApi\scan()

### ISSUE THREAD

**Issue by codesnippetnepal** [DarkaOnLine/L5-Swagger#280]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): ^7.2.5
- OS:

### Description:
i am trying to use SWG notation in laravel 7  but its not working 

### Steps To Reproduce:
composer require "darkaonline/l5-swagger:7.*"
composer require 'zircote/swagger-php:2.*'

now when i generate php artisan l5-swagger:generate  and use @SWG notation instead of openapi notation this error comes up
Call to undefined function OpenApi\scan() 

document says even in laravel 7 it supports SWG but 
error is as below 
vendor\darkaonline\l5-swagger\src\Generator.php:145

142|     protected function scanFilesForDocumentation(): self
    143|     {
    144|         if ($this->isOpenApi()) {
  > 145|             $this->swagger = \OpenApi\scan(
    146|                 $this->annotationsDir,
    147|                 ['exclude' => $this->excludedDirs]
    148|             );
    149|         }

i just wanna use @SWG notation in laravel 7 cuz ur openapi is really too much work and also not clear documentation

**Comment by DarkaOnLine** [comment]
It's hard to help with no information at all :(

**Comment by codesnippetnepal** [comment]
question update plz need help

**Comment by DarkaOnLine** [comment]
You need to set version to 2.0: https://github.com/DarkaOnLine/L5-Swagger/blob/7.x/config/l5-swagger.php#L191

This is described in the readme: https://github.com/DarkaOnLine/L5-Swagger/tree/7.x#i-am-still-using-swagger-swg-annotation

**Comment by codesnippetnepal** [comment]
finally thx its woking and also this page is missing 
https://github.com/DarkaOnLine/L5-Swagger/blob/master/tests/storage/annotations/Swagger/Anotations.php
