### ISSUE TITLE
404 /docs/api-docs.json

### ISSUE THREAD

**Issue by davidreyg** [DarkaOnLine/L5-Swagger#281]
- L5-Swagger Version:7.0
- PHP Version: 7.4
- Laravel Version: 7.x
- OS: Ubuntu 20.04

### Description:
1. My docs route : http:xxxxx/docs/api-docs.json responses with an 404 error, like if there's no route for the requested path;
2. I tried to debug SwaggerController to know where the error comes from. Going deep I found it (well I think).
3. The image in below shows the exact error...

 - dd($this->generator)
![Screenshot](https://user-images.githubusercontent.com/19297294/83152106-091a3200-a0c3-11ea-9b7c-2495cd6d45cc.png)

 - dd($this->generator AFTER )

![code](https://user-images.githubusercontent.com/19297294/83153089-2996bc00-a0c4-11ea-9d63-c507b4ded634.png)

4. SO I don't know whats happening here pls HELP ME.

Thanks! :3

**Comment by Zer0x00** [comment]
If you are using apache2 you have to enable the rewrite module:
sudo a2enmod rewrite

**Comment by davidreyg** [comment]
Just to say thank you @Zer0x00  It works!
