### ISSUE TITLE
Is it possible to get a new tag for version 6?

### ISSUE THREAD

**Issue by timquincey** [DarkaOnLine/L5-Swagger#284]
- L5-Swagger Version: 6.0.3
- PHP Version 7.4

### Description:
If version 6 is still supported?

There is changes within version 6 (use Illuminate\Support\Facades\File;) which are not in the tag.

**Comment by DarkaOnLine** [comment]
Hi, which changes are not included? Can you pinpoint the commit?

**Comment by DarkaOnLine** [comment]
Are you referring to this one: https://github.com/DarkaOnLine/L5-Swagger/pull/241

**Comment by timquincey** [comment]
Apologies I should have mentioned, yes that is the one

**Comment by DarkaOnLine** [comment]
Tagged a new version: https://github.com/DarkaOnLine/L5-Swagger/releases/tag/6.0.4
