### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by codesnippetnepal** [DarkaOnLine/L5-Swagger#285]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.2.5
- OS: Windows 10

### Description:
Whenever i push to my digital ocean server or even when i make local changes and generate swagger in laravel 7 . i am using @SWG for laravel annotation . it is showing this error on swagger response.but its is working fine in postman. but having issue with swagger. and issue is automatically solved after few hour and when i push again or make change and generate swagger same error shows

**Comment by DarkaOnLine** [comment]
This is specific to your server and sorry but I can't help with this :(
