### ISSUE TITLE
Can't install on laravel 7

### ISSUE THREAD

**Issue by ben-sheep** [DarkaOnLine/L5-Swagger#286]
- L5-Swagger Version: 7.0
- PHP Version: 7.4.1
- Laravel Version: 7.16.1

### Description:
`composer require "darkaonline/l5-swagger"`
 returns the following error after installing, while generating the composer.lock file

```
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   TypeError

  Argument 2 passed to L5Swagger\Generator::__construct() must be of the type string, null given, called in APP_PATH\vendor\darkaonline\l5-swagger\src\L5SwaggerServiceProvider.php on line 66

  at APP_PATH\vendor\darkaonline\l5-swagger\src\Generator.php:62
     58▕      * @var string
     59▕      */
     60▕     protected $swaggerVersion;
     61▕
  ➜  62▕     public function __construct(
     63▕         $annotationsDir,
     64▕         string $docDir,
     65▕         string $docsFile,
     66▕         string $yamlDocsFile,

  1  APP_PATH\vendor\darkaonline\l5-swagger\src\L5SwaggerServiceProvider.php:66
      L5Swagger\Generator::__construct("/api-docs.json", "/api-docs.yaml", [])

  2   APP_PATH\vendor\laravel\framework\src\Illuminate\Container\Container.php:801
      L5Swagger\L5SwaggerServiceProvider::L5Swagger\{closure}(Object(Illuminate\Foundation\Application), [])
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

```

### Update:
I believe it seems to be because the config file is required for installing, although I'm not certain
### Fix:
In the comment below

**Comment by ben-sheep** [comment]
Solved:
I just manually copied the config file l5-swagger.php into my config folder, then did `config:cache` to cache it and it solved the issue, since now when whatever it was that was running that required the config now has access to it.

**Comment by JonathanPort** [comment]
Hi, I did the above but still have the issue described above. Any ideas? 

It seems like the config() function within the service provider is returning null. I tried placing in the config but still is returning null.

**Comment by ben-sheep** [comment]
> Hi, I did the above but still have the issue described above. Any ideas?
> 
> It seems like the config() function within the service provider is returning null. I tried placing in the config but still is returning null.

Try:
   1. `composer update`
   2. then make sure the full config file is there
   3. `php artisan config:cache`
   4.`composer require "darkaonline/l5-swagger"`
If that doesn't work I've no idea, it really is just a band aid fix

**Comment by pawan-singleinterface** [comment]
Hi, I have done above steps, still same issue occurs

**Comment by DarkaOnLine** [comment]
In your trace, I see that `APP_PATH` is not parsed. So this looks like an issue with your configuration

**Comment by ben-sheep** [comment]
> In your trace, I see that `APP_PATH` is not parsed. So this looks like an issue with your configuration

Oh sorry it wasn't clear, I replaced the real path in the trace to my application with `APP_PATH`, it is a real path liken C:\Program Files\...\vendor\

**Comment by DarkaOnLine** [comment]
So argument 2 comes from `config('l5-swagger.paths.docs')` so you should check your configuration file if the path is correctly resolved. Also you can try to delete config cache.

**Comment by DarkaOnLine** [comment]
Oh, but you solved this already :D So I can close this :D

**Comment by AlexSunlight** [comment]
shit
