### ISSUE TITLE
Required @OA\Info() not found in v7.0

### ISSUE THREAD

**Issue by morcano** [DarkaOnLine/L5-Swagger#288]
- L5-Swagger Version: **7.0** 
- PHP Version: **7.4.6**
- OS: **Linux Alpine**
- Laravel: **7.x**

### Description:

When I'm trying to generate new doc file it fails with error:

> Required @OA\Info() not found

Btw, my composer.json:

> "darkaonline/l5-swagger": "^7.0",
> "zircote/swagger-php": "3.*"

With `"zircote/swagger-php:~2.0"` it fails with another error:

> Call to undefined function OpenApi\scan()

**Comment by DarkaOnLine** [comment]
`@OA\Info()` is required annotation. Please check other issues - this is a common problem.
