### ISSUE TITLE
Update version of Swagger UI

### ISSUE THREAD

**Issue by g011um** [DarkaOnLine/L5-Swagger#29]
Would it be possible to update the version of Swagger UI being used by L5-Swagger?

I have an issue with tag sorting (see https://github.com/swagger-api/swagger-ui/issues/1475) which was addressed in Swagger UI 2.1.5 (I think).  It seems the version being used by L5-Swagger is 2.1.4.

Swagger UI 2.2.1 seems to be a fairly major release, so I'm not sure how that affects your code.  Not much is mentioned on the release page for 2.1.5 and 2.2.0 (https://github.com/swagger-api/swagger-ui/releases) so I assume they are fairly minor bug fix releases.  I think either of those slightly newer version would fix my issue.

**Comment by DarkaOnLine** [comment]
I will look at it.  But you can always publishe assets by calling a command  l5-swagger:publish-assets and then replace Swagger UI libraries

**Comment by g011um** [comment]
That's likely what I'll do.  Thought I'd flag it here as an issue, in case you were putting together a To-Do list for future releases.

Thanks!

**Comment by DarkaOnLine** [comment]
Updated to 2.1.5
