### ISSUE TITLE
Multiple @OA\Response() with the same response="200"

### ISSUE THREAD

**Issue by DorelBesliu** [DarkaOnLine/L5-Swagger#292]
- L5-Swagger Version: 6.0.3 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.3.6
- OS: Linux 4.14.165-102.185.amzn1.x86_64

### Description:
That issue occurs only on server side.
local.ERROR: ErrorException: Multiple @OA\Response() with the same response="200": \App\Http\Controllers\Student\EventsController->update() in /var/www/html/app/Http/Controllers/Student/EventsController.php on line 136 \App\Http\Controllers\Student\EventsController->store() in /var/www/html/app/Http/Controllers/Student/EventsController.php on line 51 in /var/www/html/vendor/zircote/swagger-php/src/Logger.php:39
I tried api-docs generated on local in https://editor.swagger.io and that works very well. How that can be resolved?

### Steps To Reproduce:
I can not reproduce that on local machine

**Comment by luqmanrom** [comment]
@DorelBesliu Can you share how did you solve this?

**Comment by DorelBesliu** [comment]
> @DorelBesliu Can you share how did you solve this?

You have to remove repetititve response 
![image](https://user-images.githubusercontent.com/10742131/92354544-34151880-f0eb-11ea-8479-186403b3ec96.png)

**Comment by buildsomethingdifferent** [comment]
I'm also facing this issue on server side. any update on this guys ?
