### ISSUE TITLE
Why set up a blacklist?

### ISSUE THREAD

**Issue by YogiLai** [DarkaOnLine/L5-Swagger#294]
- L5-Swagger Version: 7.0 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):7.3.18
- OS: wsl + ubuntu16.04.1

### Description:

![image](https://user-images.githubusercontent.com/7279541/87399822-8bff3980-c5ea-11ea-98f2-2a0893738525.png)

**Comment by YogiLai** [comment]
My solution：
file: resources\views\vendor\l5-swagger\index.blade.php
![image](https://user-images.githubusercontent.com/7279541/87400580-979f3000-c5eb-11ea-9f21-7e58059975c6.png)

**Comment by DarkaOnLine** [comment]
What is the issue here? What are you trying to solve? Please be more specific.

**Comment by YogiLai** [comment]
> What is the issue here? What are you trying to solve? Please be more specific.
I don’t understand why I can’t use the header to send Accept, and I need.

**Comment by s-chizhik** [comment]
@DarkaOnLine Hi! I faced a similar problem. I have different variants for `Accept` header in my API. For example, `application/json` for fetching JSON response, or `application/x-yaml` response for fetching YAML response, or even `application/xml`. Also, I've declared this header as parameter

```PHP
 /**
 * @OA\Parameter(
 *     name="Accept",
 *     in="header",
 *     description="Type of returning result",
 *     required=true,
 *     example="application/json",
 *     @OA\Schema(type="string")
 * ),
 */
```

But swagger trims this header and not passes to an HTTP request.

**Comment by s-chizhik** [comment]
@YogiLai I've got an answer.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#fixed-fields-10

**Comment by s-chizhik** [comment]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#fixed-fields-10
@YogiLai due to this spec, these fields shall be ignored.

**Comment by YogiLai** [comment]
@s-chizhik  Thank you!
