### ISSUE TITLE
oauth2 + passport Bearer in header is different

### ISSUE THREAD

**Issue by romakvikvinia** [DarkaOnLine/L5-Swagger#295]
what i done wrong ?   

when i send request in network tab shows different token ,but  when i try  curl command in terminal it's work

Annotation in Controller

  /**
     * @OA\GET(
     *     path="/api/v1/invoice",
     *     tags={"Invoice"},
     *     summary="Retunrs Invoices",
     *     description="",
     *     operationId="index",
     *     security={{"passport": {"*"}}},
     *     @OA\Response(
     *         response=200,
     *         description="successful operation", 
     *         @OA\MediaType(
     *           mediaType="application/json",
     *               @OA\Schema(
     *                   type="array",
     *                   @OA\Items(
     *                      ref="#/components/schemas/Invoice"
     *                  )
     *              )
     *          ),
     *     )
     *     
     *  
     * )
     */

l5-swagger.php

uncommented

  /* Open API 3.0 support*/
        'passport' => [ // Unique name of security
            'type' => 'oauth2', // The type of the security scheme. Valid values are "basic", "apiKey" or "oauth2".
            'description' => 'Laravel passport oauth2 security.',
            'in' => 'header',
            'scheme' => 'https',
            'flows' => [
                "password" => [
                    "authorizationUrl" => config('app.url') . '/oauth/authorize',
                    "tokenUrl" => config('app.url') . '/oauth/token',
                    "refreshUrl" => config('app.url') . '/token/refresh',
                    "scopes" => []
                ],
            ],
        ],

<img width="685" alt="rsz_1screen_shot_2020-07-13_at_112505_am" src="https://user-images.githubusercontent.com/22936432/87401269-facc9a80-c5ca-11ea-8415-10e962a51fec.png">

**Comment by DarkaOnLine** [comment]
Please check this thread, maybe you will find your answer here: https://github.com/DarkaOnLine/L5-Swagger/issues/57
