### ISSUE TITLE
Uncaught ReferenceError: SwaggerUIBundle is not defined at window.onload Laravel

### ISSUE THREAD

**Issue by jeff-cmyk** [DarkaOnLine/L5-Swagger#297]
- L5-Swagger Version: #.#.# (`darkaonline/l5-swagger:7.*`)
- PHP Version (`>=7.1.3`):
- zircote/swagger-php: "~2.0|3.*"
- swagger-api/swagger-ui: "^3.0"
- OS: Live Upload (Linux)

### Description: 
Uncaught ReferenceError: SwaggerUIBundle is not defined at window.onload Laravel

On local working fine but when upload on the live site then swagger-ui issues showing with SwaggerUIBundle not found

I have installed mangullay zircote/swagger-php & swagger-api/swagger-ui

**Comment by sdhou** [comment]
I also encountered the same problem. I don’t know how to solve it.

**Comment by charliecen** [comment]
I also encountered the same problem. I don’t know how to solve it.

**Comment by DarkaOnLine** [comment]
Please check if `swagger-ui-bundle.js` is loaded. It is usually the case then the server is wrong configured and `js` files are not loaded

**Comment by cyber-collab** [comment]
Hello, please, you can help with this error, "**Uncaught ReferenceError: SwaggerUIBundle is not defined**", it error on dev server, by url "/api/documentation", but i don`t understand why this not working 
Here screenshot 
![изображение](https://github.com/DarkaOnLine/L5-Swagger/assets/85900493/ef8a6af7-16a4-4133-91db-1e0c2af0c2cb)
Please, help me.

**Comment by sanad-phif** [comment]
i have same issue @cyber-collab cyber-collab 
i need help

**Comment by oluseyianani** [comment]
I have the same issue. Does anyone know how to resolve it?

I'm using Laravel v11, PHP v8.2

```
"php": "^8.2",
"darkaonline/l5-swagger": "^8.6",
"laravel/framework": "^11.9",
"swagger-api/swagger-ui": "^5.17",
"zircote/swagger-php": "^4.10"
```

**Comment by cyber-collab** [comment]
Hello, I think it depends on the web server settings, because I tried it on a clean nginx with a base, and everything worked, maybe file rights are missing

**Comment by srcKod** [comment]
I have the same issue on local i use xampp and after hours of trying to resolve it i found that there is a conflict with another package "binarytorch/larecipe" which prevents the script from loading as expected. when i remove larecipe package it works.
