### ISSUE TITLE
How to upload a base64 file vie swagger-php in the JsonContent

### ISSUE THREAD

**Issue by jeff-cmyk** [DarkaOnLine/L5-Swagger#298]
- L5-Swagger Version: #.#.# (`7.0`)
- PHP Version (`>=7.2.5`):
- OS: Window

### Description:
I want to upload a fine in json array one array will have own file already have to make a array in laravel but when add a file 
in the array then not show in the body and have no error when generate from the terminal

You can seet my code
`/**
* @OA\Post(
*      path="/products/save",
*      tags={"Product"},
*      summary="Post bulk products",
*      description="Return bulk products",
*      @OA\RequestBody(
*       required=true,
*       description="Bulk products Body",
*       @OA\JsonContent(
* 			@OA\Property(
*      			property="products",
*      		    @OA\Items(
*                  @OA\Property(property="first_name", type="string"),
*                  @OA\Property(property="last_name", type="string"),
*                  @OA\Property(property="email", type="string"),
*                  @OA\Property(property="phone", type="string"),
*                  @OA\Property(property="file", type="file",format="file")
*         		),
* 			)
*       )
*     ),
* )
*/`

Plz give me the solution so that can complete this

**Comment by rodrigowbazevedo** [comment]
I don't think swagger has this feature to convert to base64, and I don't think you should, it's better to upload using `multipart/form-data`
