### ISSUE TITLE
Unable to load route, it hangs in the loading phase.

### ISSUE THREAD

**Issue by hcyildirim** [DarkaOnLine/L5-Swagger#301]
- L5-Swagger Version: 7.0 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.4.2
- OS: MacOS Catalina 10.15.0
- Laravel: 7.0

### Description:

It seems like I'm unable to `try it out` my routes. I don't know how to explain that but here is my screenshot. It (oddly) hangs in the loading phase. 

![image](https://user-images.githubusercontent.com/10330468/88227632-8ce13c80-cc76-11ea-98c1-0ae43a69dcb1.png)

My `categories` annotation:

```
/**
     * @OA\Get(
     *      path="/categories",
     *      operationId="getCategoriesList",
     *      tags={"Categories"},
     *      summary="Get list categories",
     *      description="Returns list of categories",
     *      security={ {"passport": {} }},
     *      @OA\Response(
     *          response=200,
     *          description="Successful operation",
     *       ),
     *      @OA\Response(
     *          response=401,
     *          description="Unauthenticated",
     *      )
     *     )
     */
```

### Steps To Reproduce:

1- Install l5-swagger version 7.0
2- Go to your host. (localhost:8000/api/documentation)
3- Select one of your routes and expand.
4- Hangs like the above.

**Comment by CarlosHLavezo** [comment]
I'm the same problem!

**Comment by tanerkay** [comment]
Similar issue here after a recent update to composer packages I think.

Behaviour here is slightly different, clicking any route expands it briefly, the loading spinner shows up for a fraction of a second, then the node disappears.

- L5-Swagger Version: 7.0
- PHP Version: 7.4.3
- Laravel: 7.21

**Comment by tanerkay** [comment]
Upstream. See https://github.com/swagger-api/swagger-ui/issues/6249

**Comment by hcyildirim** [comment]
Thanks! @tanerkay
