### ISSUE TITLE
how show or enable displayRequestDuration

### ISSUE THREAD

**Issue by cirelramostrabajo** [DarkaOnLine/L5-Swagger#302]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
composer show | grep l5-swagger
- PHP Version (`php -v`):
PHP 7.2.31 (cli) (built: Jun 11 2020 21:59:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.31, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.6, Copyright (c) 2002-2020, by Derick Rethans

- OS:
Linux

### Description:
i wan show display request duration, i try this
![image](https://user-images.githubusercontent.com/62561243/88323550-036a5280-cce8-11ea-96a4-2aa98c1a2c15.png)

**Comment by DarkaOnLine** [comment]
You have to provide config URL to your `swagger-config.yaml` file but not the option here
