### ISSUE TITLE
actions.js:453 TypeError: Cannot set property 'X-CSRF-TOKEN' of undefined

### ISSUE THREAD

**Issue by gromov-io** [DarkaOnLine/L5-Swagger#304]
- L5-Swagger Version: 1.10.10 (`composer show | grep l5-swagger`)
- PHP Version (`php -7.4`):
- OS: ubuntu 19+

### Description:

actions.js:453 TypeError: Cannot set property 'X-CSRF-TOKEN' of undefined
![image](https://user-images.githubusercontent.com/46241127/90385169-618e1980-e08b-11ea-99a6-7c71b3b18881.png)

**Comment by masksshow** [comment]
I confirm. Same.

**Comment by YuginKysloff** [comment]
I have same problem. Can anybody help me!

**Comment by masksshow** [comment]
I fixed it.
Look closely at the @OA \ Items blocks
They must be filled.

**Comment by masksshow** [comment]
Same: Uncaught TypeError: Cannot read property 'getScrollToKey' of undefined

**Comment by shrirangjoshi94** [comment]
I am also getting the same issue.

**Comment by taist24** [comment]
Same for me

**Comment by ricco381** [comment]
А меня тоже такая ошибка, как это исправить??

**Comment by mfrancois** [comment]
Hi @gromov-io ,
You can temporary fix it. Export the view resources resources/views/index.blade.php https://github.com/DarkaOnLine/L5-Swagger/blob/b64efe3e05c339b64d19653b200900da4ed4edb5/resources/views/index.blade.php#L84

And change the function at line 84 by this function :

`    
requestInterceptor: function(req) {
      req.headers['X-CSRF-TOKEN'] = '{{ csrf_token() }}';
      return req;
},
`

Cheers.

**Comment by ricco381** [comment]
> Hi @gromov-io ,
> You can temporary fix it. Export the view resources resources/views/index.blade.php
> 
> https://github.com/DarkaOnLine/L5-Swagger/blob/b64efe3e05c339b64d19653b200900da4ed4edb5/resources/views/index.blade.php#L84
> 
> And change the function at line 84 by this function :
> 
> ```js
> requestInterceptor: function(req) {
>       req.headers['X-CSRF-TOKEN'] = '{{ csrf_token() }}';
>       return req;
> },
> ```
> 
> Cheers.

How to turn it off?

**Comment by mfrancois** [comment]
@ricco381,

Use publish command `php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"`

The file will be publish on our resources :

`Copied Directory [/vendor/darkaonline/l5-swagger/resources/views] To [/resources/views/vendor/l5-swagger]`

Go to `/resources/views/vendor/l5-swagger/index.blade.php` change the function like you want.

Regards

**Comment by DarkaOnLine** [comment]
This is already solved for `8.x`, `7.x` and `6.x` versions

**Comment by sumit-sharma** [comment]
While I pull updated file which contains on **line 84**  of **/resources/views/vendor/l5-swagger**
```
 requestInterceptor: function() {
      this.headers['X-CSRF-TOKEN'] = '{{ csrf_token() }}';
      return this;
    },
```
does not work so I updated as per @ricco381  on **line 84** 
```
requestInterceptor: function(req) {
      req.headers['X-CSRF-TOKEN'] = '{{ csrf_token() }}';
      return req;
    },

```

**Comment by jccpdev** [comment]
@DarkaOnLine is there any chance this will get updated on the 5.7.* tag? or are you guys not supporting it anymore?

**Comment by DarkaOnLine** [comment]
@jccpdev I created 2 more releases:

- https://github.com/DarkaOnLine/L5-Swagger/releases/tag/5.7.3
- https://github.com/DarkaOnLine/L5-Swagger/releases/tag/5.8.5

**Comment by yushine** [comment]
> @jccpdev I created 2 more releases:
> 
> * https://github.com/DarkaOnLine/L5-Swagger/releases/tag/5.7.3
> * https://github.com/DarkaOnLine/L5-Swagger/releases/tag/5.8.5

5.8.5 still has the same issue:

``` TypeError: Cannot set property 'X-CSRF-TOKEN' of undefined ```

**Comment by futuremeng** [comment]
remember to set config in the .env:
L5_SWAGGER_GENERATE_ALWAYS=true
L5_SWAGGER_CONST_HOST=api.domain.com
