### ISSUE TITLE
How we write the API specification in other files instead of the controllers?

### ISSUE THREAD

**Issue by shrirangjoshi94** [DarkaOnLine/L5-Swagger#309]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):
- OS:

### Description:

Can we write the API specification in another file instead of the controllers to make the controller less bulky?

eg: Can we write the below code in a separate file and link it to the controller?

  @OA\Post(
  path="/api/login",
  summary="Sign in",
  description="Login by email, password",
  tags={"auth"},
  @OA\RequestBody(
     required=true,
     description="Pass user credentials",
     @OA\JsonContent(
        required={"email","password"},
        @OA\Property(property="email", type="string", format="email", example="user1@mail.com"),
        @OA\Property(property="password", type="string", format="password", example="PassWord12345"),
     ),
  ),
  @OA\Response(
     response=422,
     description="Wrong credentials response",
     @OA\JsonContent(
       @OA\Property(property="message", type="string", example="Sorry, wrong email address or password. Please try again")
        )
     )
 )

**Comment by DarkaOnLine** [comment]
You can write annotation in any file you want. You can have a separate `docs` folder with the same structure as your project and have only annotations in your PHP files. If you like you can even have everything in one file :)
