### ISSUE TITLE
Support for Dingo API ?

### ISSUE THREAD

**Issue by aluferraz** [DarkaOnLine/L5-Swagger#31]
Hi,

I'm trying to use L5-Swagger with dingo api package:

https://github.com/dingo/api

But whenever I run php artisan l5-swagger:generate, the results are not printed in /api/documentation path..

Any plans for supporting Dingo API ? Any ideas on how to get it to work ?

Thanks a lot !

**Comment by DarkaOnLine** [comment]
It is two different types of api documentation.  If you what to use both you have to write a notations  in two different ways for each method, one Dingo style other swagger

**Comment by aluferraz** [comment]
Hi There,

Actually I'm using the swagger annotations, and the JSON file is generated with the documentation.  But, the problem is that I cannot see the docs with Swagger UI using the path "/api/documentation".

**Comment by Broutard** [comment]
no problem here with dingo !
