### ISSUE TITLE
TryIt not working: Could not render n, see the console.

### ISSUE THREAD

**Issue by 4myr** [DarkaOnLine/L5-Swagger#310]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
darkaonline/l5-swagger             7.0       Swagger integration to Laravel 5
- PHP Version (`php -v`): 7.3.21-1+ubuntu20.04.1+deb.sury.org+1 (cli) 
- OS: ubuntu 20

### Description:
When i click on execute in try it option, i get this error in response:
**Could not render n, see the console.**

also i get this errors in console:
```
TypeError: this.headers is undefined
    requestInterceptor documentation:94
    t actions.js:433
```
```
TypeError: c is null
    value live-response.jsx:56
    render root-injects.jsx:92
```

### Steps To Reproduce:
i install package by  _composer require darkaonline/l5-swagger_
also i tried _npm install swagger-ui_ and _composer require zircote/swagger-php_

**Comment by DarkaOnLine** [comment]
The fix is already released: https://github.com/DarkaOnLine/L5-Swagger/releases/tag/7.0.1

**Comment by 4myr** [comment]
i installed this version using composer require "darkaonline/l5-swagger:7.0.1"

composer show | grep l5-swagger
darkaonline/l5-swagger             7.0.1     Swagger integration to Laravel 5

but same error

**Comment by DarkaOnLine** [comment]
Have you published/changed your `index.blade.php` file: https://github.com/DarkaOnLine/L5-Swagger/pull/307/files

**Comment by github-cuongvm** [comment]
@DarkaOnLine 
Thank boss.
bug in  "darkaonline/l5-swagger": "6.0.5" fixed!!!

**Comment by ybert** [comment]
This bug is still in version 6.0.5. I can't update to 7.x as it requires 7.x of Laravel which is not the LTS support version.
@DarkaOnLine Can you update  version 6.x to make this fix available for Laravel LTS version?
