### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getScrollToKey' of undefined

### ISSUE THREAD

**Issue by Stenfrank** [DarkaOnLine/L5-Swagger#311]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`): darkaonline/l5-swagger               7.0.1              Swagger integration to Laravel 5
- PHP Version (`php -v`): 7.4.8
- OS: Fedora 32 Workstation

### Description:
This issue prevents models from being expanded.

### Steps To Reproduce:
Try to expand the subschemas, or the enum of the status property.

The problem is also related to the library [swagger-api/swagger-ui](https://github.com/swagger-api/swagger-ui/issues/6305).

**Comment by Stenfrank** [comment]
#312

**Comment by ricco381** [comment]
How can I fix this problem?

**Comment by Stenfrank** [comment]
> How can I fix this problem?

Is already solving

https://github.com/swagger-api/swagger-ui/issues/6305
