### ISSUE TITLE
Unable to publish resources

### ISSUE THREAD

**Issue by osingh152** [DarkaOnLine/L5-Swagger#316]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):
- OS: Windows 10

### Description:

![image](https://user-images.githubusercontent.com/29159715/90886586-4d6e5300-e3d0-11ea-9632-bf59ad253ac9.png)

**Comment by DarkaOnLine** [comment]
Please provide more information: which L5-swagger version you are using, but in general, this should work, unless something is wrong with composer.json or your configuration
