### ISSUE TITLE
"vendor/darkaonline/l5-swagger/resources/views/index.blade.php" changes does not apply to "resources/views/vendor/l5-swagger/index.blade.php"

### ISSUE THREAD

**Issue by kamyarmeshkabadi** [DarkaOnLine/L5-Swagger#317]
- L5-Swagger Version: 6.0.5 (`composer show | grep l5-swagger`)
- PHP Version: 7.4.9 (`php -v`):
- OS: Ubuntu 18

### Description:
After upgrading to version 6.0.5, a bug appears because "vendor/darkaonline/l5-swagger/resources/views/index.blade.php" changes does not apply to "resources/views/vendor/l5-swagger/index.blade.php" even after running "php artisan l5-swagger:generate" command. You have to change it manually.

**Comment by DarkaOnLine** [comment]
`php artisan l5-swagger:generate` only generates `json` spec file. You have to run `php artisan vendor:publish --provider="L5Swagger\L5SwaggerServiceProvider"` to publish new views or change it manualy
