### ISSUE TITLE
Sanctum - API Token Authentication

### ISSUE THREAD

**Issue by agustin-arroyo** [DarkaOnLine/L5-Swagger#318]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):
- OS:
- 

Great Package. Thanks.

### Description:

**### Sanctum API Token Authentication was release with Laravel 7.x and works great.** 

### Steps To Reproduce:

I am using Laravel 7 Sanctum Bearer Token authentication. I can't find how to configure the SecurityScheme for it. 

I am able to set the SecurityScheme on Controller.php, but once in Swagger when I enter the token I still get Unauthenticated.

Hope you can give me some guidelines.

This is what I have  at Controller.php
 * @OA\SecurityScheme(
 *     type="http",
 *     description="Authentication Bearer Token",
 *     name="Authentication Bearer Token",
 *     in="header",
 *     scheme="bearer",
 *     bearerFormat="JWT",
 *     securityScheme="apiAuth",
 * )

**Comment by DarkaOnLine** [comment]
Sorry I have never worked with Sanctum :( Maybe someone from the community will be able to help you with this

**Comment by HowardF** [comment]
Following seems to work for me...in l5-swagger,php

```
`   'securityDefinitions' => [
            'securitySchemes' => [
                /*
                 * Examples of Security schemes
                */

                'api_key_security_example' => [ // Unique name of security
                    'type' => 'apiKey', // The type of the security scheme. Valid values are "basic", "apiKey" or "oauth2".
                    'description' => 'A short description for security scheme',
                    'name' => 'Authorization', // The name of the header or query parameter to be used.
                    'in' => 'header', // The location of the API key. Valid values are "query" or "header".
                ],
              
            ],
            'security' => [
                /*
                 * Examples of Securities
                */
                [

                    'api_key_security_example' => [       
                    ],
                ],
            ],
        ],`
```

**Comment by alexv96** [comment]
I don't know if you still need the help, but I implemented it this way since I am working with Sanctum for authentication.

in the l5-swagger.php put
```
'bearer_token' => [ // Unique name of security
                    'type' => 'apiKey', // Valid values are "basic", "apiKey" or "oauth2".
                    'description' => 'Enter token in format (Bearer <token>)',
                    'name' => 'Authorization', // The name of the header or query parameter to be used.
                    'in' => 'header', // The location of the API key. Valid values are "query" or "header".
                ],
```

Before the controller class:
```
/**
 * @OA\Info(title="API TICKETS", version="1.0")
 * 
 * @OA\Server(url="http://hello.world")
 * 
 * @OAS\SecurityScheme(
 *      securityScheme="bearer_token",
 *      type="http",
 *      scheme="bearer"
 * )
 */

class ReportController extends Controller
```

Before each function
```
    /**
     *  @OA\Get(
     *      path="ROUTE API",
     *      summary="Title",
     *      security={{"bearer_token":{}}},
     *      @OA\Response(
     *          response=200,
     *          description="Donec sollicitudin molestie malesuada."
     *      ),
     *      @OA\Response(
     *          response="default",
     *          description="An error has occurred."
     *      )
     *  )
     */
```

**Comment by hairmenu** [comment]
Just a few more notes:
It worked for me however i had hard time to figure the following
-> 'bearer_token' is up to you but 'name' => 'Authorization' is not, it is built in Sanctum code to look for this word to be in the header
-> when you are using the generated documentation, you will set up the authorizations by pasting a personal access token. It has to be `Bearer your-token-goes-here` as shown

Hope it would help some of us
![Screen Shot 2020-11-10 at 9 00 16 PM](https://user-images.githubusercontent.com/7205835/98756101-e5f4ed80-2397-11eb-987d-dcb860d6c35e.png)

**Comment by CloudyCity** [comment]
@hairmenu @alexv96 @HowardF Thanks for your sharing. 

But i have a problem at first step. I get a `CSRF token mismatch` error in login request. 
Seem like you guys don't have this problem or already solved it.

![image](https://user-images.githubusercontent.com/17662451/100694783-b18ab500-33ca-11eb-82c0-d55c20c6b766.png)

 **Any suggestions will be a huge help**.

**Comment by hypernics** [comment]
In the l5-swagger.php put in defaults / securityDefinitions / securitySchemes
```
                'sanctum' => [
                    'type' => 'http',
                    'description' => 'Laravel Sanctum token authentication',
                    'scheme' => 'bearer',
                    'bearerFormat' => 'JWT'
                ],
```
Then use Sanctum security in each function
```
    /**
     * @OA\Get (
     * path="/url",
     * summary="summary",
     * description="description",
     * security={ {"sanctum": {} }},
     */
```

**Comment by johndearroy** [comment]
I have added the `@OA\SecurityScheme` into my main controller where i have `@OA\Info` just like below:
```
     * @OA\SecurityScheme(
     *      securityScheme="bearerAuth",   // you can name it whatever you want, but not forget to use the same in your request
     *      type="http",
     *      scheme="bearer"
     * )
```

And in your request don't forget to add security like below:
```
     * @OA\Get(
     *      .....................
     *      security={{"bearerAuth":{}}},    // see i have used the same name here
     *      @OA\Response(
     *          response=200,
     *          ...........................
     *       ),
     *     @OA\Response(
     *          response=500,
     *          description="Server error"
     *       )
     *     )
```

**Comment by Sainath470** [comment]
like how can I use this to take the Jwt token through the parameters for authorization?

**Comment by lloricode** [comment]
Hi do you have any sample using PHP attributes?

**Comment by jessetmia** [comment]
> Hi do you have any sample using PHP attributes?

    ```PHP

    #[OA\Get(
        path: "api/path",
        tags: ["Test"],
        summary: "&nbsp;",
        description: "&nbsp;",
        security: [["sanctum" => []]],
        responses: [
            new OA\Response(response: 200, description: 'AOK'),
            new OA\Response(response: 401, description: 'Not allowed'),
        ]
    )]
```

In case anyone else wants an example of attributes moving forward. Tested on my local and am able to properly auth using sanctum. A lot of details for the attributes can be found here: https://github.com/zircote/swagger-php/tree/master/src/Attributes and here: https://zircote.github.io/swagger-php/reference/attributes.html
