### ISSUE TITLE
@SWG (SWAGGER annotations) support.

### ISSUE THREAD

**Issue by php-writerman** [DarkaOnLine/L5-Swagger#324]
- L5-Swagger Version: 8.0
- PHP Version: 7.4
- OS: Linux

### Description:

Is it possible to add support for Swagger annotations?

**Comment by DarkaOnLine** [comment]
Sorry but no. We intentionally dropped support of Swagger (OAS 2.0) because it is outdated and if possible we encourage to migrate to OAS 3.0
