### ISSUE TITLE
Laravel 5.3 new routes folder structure not in ./app/

### ISSUE THREAD

**Issue by metaclassing** [DarkaOnLine/L5-Swagger#33]
Hi, In L5.3 the routes are no longer in ./app/Http/... but a new ./routes folder. I have some documentation in those routes that do not get picked up now and I was wondering what the best approach was to address this. Would it be better to turn the list of scanned folders into an array? ['app','routes'] and loop through? Or is there some other thing im missing? I really like the convenience of route cohabitation with SWG properties. Thanks!

**Comment by grepollo** [comment]
Also you it has it has require restriction to only support 5.1 and 5.2, cannot install on 5.3

**Comment by DarkaOnLine** [comment]
You can do it. Just replace `'annotations' => base_path('app')` whith `'annotations' => [base_path('app'), '/other/path']` and it will work
