### ISSUE TITLE
How to disable try-it-out for routes, using supportedSubmitMethods config?

### ISSUE THREAD

**Issue by SimonMacIntyre** [DarkaOnLine/L5-Swagger#332]
- L5-Swagger Version: 6.0.5
- PHP Version: 7.3
- OS: Linux

### Description:
Is there a way to disable 'try it out' on specific routes? I cannot figure out how to apply the config "supportedSubmitMethods" to this package.

**Comment by danrovito** [comment]
Did you figure this out?

**Comment by SimonMacIntyre** [comment]
> Did you figure this out?

Unfortunately not. We ended up just specifying a dev server in the live environment's swagger docs, so that things like `DELETE` or `POST` endpoints would act on data from dev servers.
