### ISSUE TITLE
How to remove/customize topbar in UI?

### ISSUE THREAD

**Issue by i-priyanshuverma** [DarkaOnLine/L5-Swagger#335]
- L5-Swagger Version: 5.8.* (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.3.23
- OS:Ubuntu-20.0.4

**Comment by wattsie** [comment]
For future reference, anyone looking to quickly remove UI header (topbar), found a quick solution.

Simply change the "layout" to use "BaseLayout"
```
layout: "BaseLayout",
```
