### ISSUE TITLE
Extract the Swagger UI wrapper?

### ISSUE THREAD

**Issue by osteel** [DarkaOnLine/L5-Swagger#336]
- L5-Swagger Version: any
- PHP Version: any
- OS: any

### Description:

This is actually more of a question than an issue per se.

I work with OpenAPI on a Laravel project, but I don't use annotations (I maintain the OpenAPI documentation by editing the YAML file directly).

I initially wanted to use this package but there doesn't seem to be any way to use it without annotations. I essentially only need Swagger UI, and I like the way you've wrapped it in Laravel, which I've more or less replicated for that project I'm working on.

It's all working fine, but that made me wonder: would you consider extracting that wrapper to its own package?

That package could be used as a dependency for this one (L5 Swagger), which people could continue using if they want to leverage annotations; on the other hand, people like me who just want to use the Swagger UI wrapper could only pull that new package instead.

Another option would be to make the use of annotations optional in L5 Swagger, but extracting the Swagger UI wrapper seems like a cleaner way.

What do you think?

For reference, here is an article about [API Design-First vs Code First](https://stoplight.io/blog/api-design-first-vs-code-first/).

### Steps To Reproduce:

N/A

**Comment by DarkaOnLine** [comment]
Just a quick thought - have you tried just put your [YAML](https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php#L26) file into the [docs](https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php#L70) directory and disable [L5_SWAGGER_GENERATE_ALWAYS](https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php#L159) - it should just work

**Comment by osteel** [comment]
@DarkaOnLine hi, thanks for the quick reply – will give this a try and let you know

**Comment by osteel** [comment]
@DarkaOnLine that seems to do the trick, the only thing is that it tries to load `api-docs.json` by default, which fails as this file doesn't exist. Can the behaviour be changed somewhere so that it loads the YAML file by default instead? I can't seem to find that in the `l5-swagger.php` config file.

Thanks!

**Comment by DarkaOnLine** [comment]
Hmm good catch. Can you try change file name here https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php#L21 to `your-file-name.yaml`?

**Comment by osteel** [comment]
@DarkaOnLine yep that works, bit hacky though. Looks like the code will [pick up the JSON doc by default](https://github.com/DarkaOnLine/L5-Swagger/blob/master/src/Http/Controllers/SwaggerController.php#L108) no matter what.

Might make sense to add a configurable default path in there too
