### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by Mirkin-source** [DarkaOnLine/L5-Swagger#339]
- L5-Swagger Version: 8.0.2 
- PHP Version: 7.4.12
- OS: Ubuntu

### Description:
When opening the documutation i've got the error: Trying to access array offset on value of type null
It highlighted: 
```
` if ($proxy = $config['proxy']) {

            if (! is_array($proxy)) {

                $proxy = [$proxy];

            }

            Request::setTrustedProxies($proxy, Request::HEADER_X_FORWARDED_ALL);

        }`

```

**Comment by DarkaOnLine** [comment]
Looks like you config is not published or invalid.

**Comment by Mirkin-source** [comment]
My config is published and I used config from the repository without a change..

**Comment by kedarv** [comment]
Also have this issue, my config is published. was working on 7.x
