### ISSUE TITLE
Base Path Config Setting Not Being Used

### ISSUE THREAD

**Issue by dragoonis** [DarkaOnLine/L5-Swagger#34]
Hi @DarkaOnLine,

It would appear that your config setting 'base' is not actually used in your code. Can you check this for us? We're trying to upgrade to your swagger library but need to customise the base url with `/v1.2` or a`/v1.5` as our software matures.

Can you advise how to achieve this?

https://github.com/DarkaOnLine/L5-Swagger/blob/f5e6f32b0abcfbf97d582d0edb40345c07d31cf9/config/l5-swagger.php#L141

Many thanks,
Paul

**Comment by DarkaOnLine** [comment]
You can set your base path in Swagger annotations like this:

```php
/**
 * @SWG\Swagger(
 *     basePath="/api/v1",
 *     schemes={"http"}
 *     @SWG\Info(
 *         version="1.0.0"
 *     )
 * )
 */
```
