### ISSUE TITLE
[Question] How to customize the UI, put company logo + icon

### ISSUE THREAD

**Issue by Messhias** [DarkaOnLine/L5-Swagger#340]
- L5-Swagger Version: any
- PHP Version (`php -v`): any
- OS: any

### Description:

I've been trying to customise my UI but since the CSS + JS is auto generated it's been quite harder to do it.

I just would like change some color + company's logo.

Obs.: by the way would be nice also update the readme.md section to explain more about the library, it's quite vague and we have to research in a lot external link and fonts to start create something useful.

### Steps To Reproduce:

Thank you,

**Comment by Messhias** [comment]
Hello @DarkaOnLine, there's some update about that? 

Thank you.

**Comment by DarkaOnLine** [comment]
You can export `index.php` - `php artisan l5-swagger:publish-assets` and modify the file as you like. Include new css as a file or inline. In this way, you can have the company styling
