### ISSUE TITLE
[Question]How to specify the Controller folder into which the annotations are to be loaded.

### ISSUE THREAD

**Issue by kurosukee** [DarkaOnLine/L5-Swagger#341]
- L5-Swagger Version: 8.0.2 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.4
- OS: Docker 19.03.13 within Mac OS Catalina 10.15.7 

### Description:

I want to be able to specify the Controller folder where the annotations are loaded.
Please tell me about it.

### Steps To Reproduce:

1. Make the directory configuration as shown below.
2. I want to load the controllers annotation in the api directory.

Ex) Folder structure
````
- project_root
    - app
        - Controllers
    - api <-- Extended on own
        - Controllers
````

**Comment by buildwide** [comment]
I do like this:
In config l5-swagger.php
```
'documentations' => [
        'default' => [
            'paths' => [
                 /**
                 * two name two file
                 */
                'docs_json' => 'api-console.json',
                //'docs_json' => 'api-admin.json',
                /**
                 * common models two controller to two file
                 */
                'annotations' => [
                    base_path('app/Http/Controllers/Console'),
                    //base_path('app/Http/Controllers/Admin'),
                    base_path('app/Models'),
                ],
            ],
        ],
    ],
```

then in L5Swagger\Http\Controllers\SwaggerController function api
```
        $jsonFile = $config['paths']['docs_json'] ?? 'api-docs.json';
        if ($request->input('json_file')) {
            $jsonFile = $request->input('json_file');
        }

        $urlToDocs = route('l5-swagger.' . $documentation . '.docs', $jsonFile);
```

after that all
I can visit 
/api/documentation?json_file=api-admin.json
or
/api/documentation?json_file=api-console.json
to diffrent doc

**Comment by aya-nishiyama** [comment]
Thanks for your suggestion.
That worked. thx!

**Comment by kurosukee** [comment]
Thanks for your suggestion.
That worked. thx!
