### ISSUE TITLE
Quation about anotations

### ISSUE THREAD

**Issue by luciano-nascimento** [DarkaOnLine/L5-Swagger#342]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`) 8.0.2
- PHP Version (`php -v`): 7.4
- OS: linux

### Description:
Is it possible to create anotations out side of controller ? I mean, create notations inside isolated file ?

**Comment by DarkaOnLine** [comment]
Yes, you can create annotations in any PHP file. You can look here for example https://github.com/DarkaOnLine/L5-Swagger/blob/master/tests/storage/annotations/OpenApi/Anotations.php
