### ISSUE TITLE
Published new release: https://github.com/DarkaOnLine/L5-Swagger/releases/tag/8.0.2

### ISSUE THREAD

**Issue by avenCN** [DarkaOnLine/L5-Swagger#345]
Published new release: https://github.com/DarkaOnLine/L5-Swagger/releases/tag/8.0.2

_Originally posted by @DarkaOnLine in https://github.com/DarkaOnLine/L5-Swagger/issues/322#issuecomment-689309573_

Here used php 8.0 show message:

Problem 1
    - darkaonline/l5-swagger 8.0.2 requires php ^7.2 -> your PHP version (8.0.0) does not satisfy that requirement.
    - darkaonline/l5-swagger 8.0.1 requires php ^7.2 -> your PHP version (8.0.0) does not satisfy that requirement.
    - darkaonline/l5-swagger 8.0.0 requires php ^7.2 -> your PHP version (8.0.0) does not satisfy that requirement.
    - darkaonline/l5-swagger 8.0.2 requires php ^7.2 -> your PHP version (8.0.0) does not satisfy that requirement.
    - Installation request for darkaonline/l5-swagger ^8.0 -> satisfiable by darkaonline/l5-swagger[8.0.0, 8.0.1, 8.0.2].

**Comment by avenCN** [comment]
![image](https://user-images.githubusercontent.com/14192055/100594506-bb61d900-3334-11eb-8e26-a093751804b3.png)

**Comment by BenOvermyer** [comment]
The actual issue here is that L5-Swagger doesn't yet support PHP 8. Perhaps the issue title should be changed to reflect that.

**Comment by DarkaOnLine** [comment]
@BenOvermyer - it is now: https://github.com/DarkaOnLine/L5-Swagger/releases/tag/8.0.3
