### ISSUE TITLE
Multi api documentaion

### ISSUE THREAD

**Issue by abdosaeedelhassan** [DarkaOnLine/L5-Swagger#357]
- L5-Swagger Version: 8.0.4
- PHP Version (`php -v`): 7.4.13
- OS: Ubuntu 20.10

### Description:

my config is
`
 'default' => 'examiner_v1',
    'documentations' => [

        'client_v1' => [
            'api' => [
                'title' => 'Client apis',
            ],
            'routes' => [
                'api' => 'admin/apis/client/v1',
            ],
            'paths' => [
                'docs_json' => 'client_v1.json',
                'docs_yaml' => 'client_v1.yaml',
                'format_to_use_for_docs' => env('L5_FORMAT_TO_USE_FOR_DOCS', 'json'),
                'annotations' => [
                    base_path('app/Http/Api/Client/V1'),
                ],

            ],
        ],
        'examiner_v1' => [
            'api' => ['title' => 'Examiner apis'],
            'routes' => [
                'api' => 'admin/apis/examiner/v1'
            ],
            'paths' => [
                'docs_json' => 'examiner_v1.json',
                'docs_yaml' => 'examiner_v1.yaml',
                'format_to_use_for_docs' => env('L5_FORMAT_TO_USE_FOR_DOCS', 'json'),
                'annotations' => [
                    base_path('app/Http/Api/Examiner/V1')
                ],
            ],
        ],

    ],
`

### Steps To Reproduce:

after i did
php artisan l5-swagger:generate --all

i received 

Route [l5-swagger.client_v1.docs] not defined.

**Comment by nietopablo19** [comment]
+1

**Comment by WanHsuan** [comment]
You need to add 'docs' and 'oauth2_callback' value in routes. Like this:
`'client_v1' => [
        'api' => [
            'title' => 'Client apis',
        ],
        'routes' => [
            'api' => 'admin/apis/client/v1',
            'docs' => 'docs/client/v1',
            'oauth2_callback' => 'api/client/v1/oauth2_callback',
        ],
        'paths' => [
            'docs_json' => 'client_v1.json',
            'docs_yaml' => 'client_v1.yaml',
            'format_to_use_for_docs' => env('L5_FORMAT_TO_USE_FOR_DOCS', 'json'),
            'annotations' => [
                base_path('app/Http/Api/Client/V1'),
            ],

        ],
    ],`

**Comment by abdosaeedelhassan** [comment]
> You need to add 'docs' and 'oauth2_callback' value in routes. Like this:
> 
> ```
> 'client_v1' => [
>         'api' => [
>             'title' => 'Client apis',
>         ],
>         'routes' => [
>             'api' => 'admin/apis/client/v1',
>             'docs' => 'docs/client/v1',
>             'oauth2_callback' => 'api/client/v1/oauth2_callback',
>         ],
>         'paths' => [
>             'docs_json' => 'client_v1.json',
>             'docs_yaml' => 'client_v1.yaml',
>             'format_to_use_for_docs' => env('L5_FORMAT_TO_USE_FOR_DOCS', 'json'),
>             'annotations' => [
>                 base_path('app/Http/Api/Client/V1'),
>             ],
> 
>         ],
>     ],
> ```

Now it worked for me, thank you @wanhsuan612
