### ISSUE TITLE
Generate command fails with message "Undefined offset: 0"

### ISSUE THREAD

**Issue by ACTINEO-Ben** [DarkaOnLine/L5-Swagger#363]
- L5-Swagger Version: 8.0.4
- PHP Version 7.4.15 

### Description:
I created a feature branch in my current branch and played around with this library a little. It went great so far, but sadly I didn't have time to continue with it for a while. So I added a few annotations to some routes and models and left it at that for a while.
That was on the 9th of February.
Now I wanted to return to this project and some update apparently broke it.

It worked flawlessly when I only checked out my feature branch and ran "composer install".
After I ran "composer update" it stopped working.
Now every time I try to run `php artisan l5-swagger:generate` it will fail with the not very helpful message `Undefined offset: 0`.

What I could find out so far:
It will fail as soon as I add the first `@OA\Response`, no matter the content.

The relevant part of the stack trace:
`#2 [internal function]: OpenApi\\Logger->OpenApi\\{closure}('Undefined offse...', 512)  
#3 /var/www/html/vendor/zircote/swagger-php/src/Logger.php(62): call_user_func(Object(Closure), Object(ErrorException), 512)  
#4 /var/www/html/vendor/zircote/swagger-php/src/Analyser.php(143): OpenApi\\Logger::warning(Object(ErrorException))  
#5 /var/www/html/vendor/zircote/swagger-php/src/StaticAnalyser.php(411): OpenApi\\Analyser->fromComment('/**\
     * @OA\\\\...', Object(OpenApi\\Context))  
#6 /var/www/html/vendor/zircote/swagger-php/src/StaticAnalyser.php(308): OpenApi\\StaticAnalyser->analyseComment(Object(OpenApi\\Analysis), Object(OpenApi\\Analyser), '/**\
     * @OA\\\\...', Object(OpenApi\\Context))  
#7 /var/www/html/vendor/zircote/swagger-php/src/StaticAnalyser.php(45): OpenApi\\StaticAnalyser->fromTokens(Array, Object(OpenApi\\Context))  
#8 /var/www/html/vendor/zircote/swagger-php/src/functions.php(54): OpenApi\\StaticAnalyser->fromFile('/var/www/html/a...')  
#9 /var/www/html/vendor/darkaonline/l5-swagger/src/Generator.php(152): OpenApi\\scan(Array, Array)  
#10 /var/www/html/vendor/darkaonline/l5-swagger/src/Generator.php(97): L5Swagger\\Generator->scanFilesForDocumentation()`

The first DocBlock where it fails:
` 
   /**  
     * @OA\Get(  
     *  path="/api/v1/auth/permissions",  
     *  summary="List permissions",  
     *  description="List permissions available for currently logged in user",  
     *  tags={"Auth"},  
     *  security={  
     *     {"passport": {}},  
     *   },  
     *  @OA\Response(  
     *      response=401,  
     *      description="Error: Unauthorized",  
     *      @OA\JsonContent(  
     *          @OA\Property(  
     *              property="error",  
     *              type="string",  
     *              example="Unauthenticated"  
     *          )  
     *      )  
     *  ),  
     *  @OA\Response(  
     *      response=200,  
     *      description="Success",  
     *      @OA\JsonContent(  
     *          @OA\Property(  
     *              property="data",  
     *              type="array",  
     *              example={"permission-1", "permission-2", "permission-3"},  
     *              @OA\Items(type="string")  
     *          )  
     *      )  
     *  )  
     * )  
     */  
`
Sorry, I can't get the formatting to work properly, but I guess it's pretty basic anyway.
When I remove both `@OA\Response` blocks it works, but of course that doesn't really help
Just adding a `@OA\Response(response=200)` will result in the `Undefined offset` again.

What I saw that changed in that update according to composer.lock:
doctrine/annotations
1.11.1 => 1.12.0
laravel/framework
v8.26.1 => v8.28.1
nyholm/psr7
1.3.2 => 1.4.0

I tried to locate the exact variable where it doesn't find the searched offset, but I couldn't narrow it down yet.

## Update
I traced the actual error to line [1451 of the DocParser belonging to doctrine/annotations](https://github.com/doctrine/annotations/compare/1.11.2...1.12.0#diff-e5d2e0837a5b53f6d38f5a1f6d4f154c757e2cba3eb3259751ed19944339a6edR1447). Since this is a fairly new addition, I guess that this is the reason it failed now.
So I guess it is a bug with the latest updates to the doctrine library, but I still don't know if I also did something wrong to provoke this or if this is a general issue. Can someone reproduce the error by just updating his composer dependencies?

I now set `"doctrine/annotations": "1.11.*"` in my composer.json and after running `composer update` everything is working again for now.

**Comment by addlabdevelopment** [comment]
Thank you , this was helpful ,

**Comment by ACTINEO-Ben** [comment]
I directly reported this to [in doctrine/annotations](https://github.com/doctrine/annotations/issues/405) as well and they already released a hotfix. So with 1.12.1 it's all good again :)
