### ISSUE TITLE
Request Headers for Oauth2 authorisation code flow

### ISSUE THREAD

**Issue by rrs-james** [DarkaOnLine/L5-Swagger#364]
- L5-Swagger Version: 8.0.4
- PHP Version: 7.4.8
- OS: Windows 10

### Description:
This is more of a question than an error. I am using oauth2 security and the authorisation code flow. I am stuck on a problem with the "try it out" authorise function. I am getting a CORS problem as the Origin header is not being sent in the authorise request for swagger. The authorisation with FusionAuth seems to work correctly and then I get the Fetch type error on chrome to do with CORS
[l5-swagger.txt](https://github.com/DarkaOnLine/L5-Swagger/files/6027434/l5-swagger.txt)

 (all working fine when using the API normally).
My question is simply, how/where/can I set the request headers for the authorise request in the l5-swagger config file?

### Steps To Reproduce:
Followed the install instructions.
My l5-swagger config file is as follows:

[l5-swagger.txt](https://github.com/DarkaOnLine/L5-Swagger/files/6027442/l5-swagger.txt)

**Comment by setuk** [comment]
Did you solve this - I am facing a similar issue on setting Origin header in a get request
