### ISSUE TITLE
File Upload Using Multipart Form Data

### ISSUE THREAD

**Issue by Raja-Omer-Mustafa** [DarkaOnLine/L5-Swagger#365]
- L5-Swagger Version: 8.0.4 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.4.9
- OS: Windows 10

### Description:
-  I just tried to upload file using form data but this package always send request in "application/json"
- I also try to pass "Content-Type: multipart/form-data" still no success 
can you tell what i am doing wrong

### Current Curl: (Swagger Open Api)

```curl -X POST "http://127.0.0.1:8000/api/store-file" -H  "accept: application/json" -H  "Content-Type: application/json" -H  "X-CSRF-TOKEN: " -H  "Accept: application/json" -H  "content-type: application/json" -d {"file":{"name":"338918379.png","type":"image/png"}}```

### Expected Curl: (Postman)

curl -X POST \
  http://127.0.0.1:8000/api/store-file \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Postman-Token: 80fa7218-8893-44c1-9885-ac8f081fbcac' \
  -H 'cache-control: no-cache'

Open Api Annotation
```
    * @OA\Info(
    *      version="1.0.0",
    *      title="Project Name",
    *      description="Project Description",
    *      @OA\Contact(
    *          name="Contact Name",
    *          url="<contact-url>",
    *          email="contact email address"
    *      )
    * )
    *
    * @OA\Post(
    *     path="/api/store-file",
    *     tags={"store-file"},
    *     summary="Save a file",
    *     description="Save a file",
    *     operationId="storeFile",
    *     @OA\MediaType(mediaType="multipart/form-data"),
    *     @OA\Response(
    *         response=200,
    *         description="successful operation",
    *         @OA\MediaType(mediaType="multipart/form-data")
    *     ),
    *     @OA\Response(
    *         response=400,
    *         description="Invalid Credentials",
    *         @OA\MediaType(mediaType="multipart/form-data")
    *     ),
    *     @OA\Response(
    *         response=401,
    *         description="Unauthorized User",
    *         @OA\MediaType(mediaType="multipart/form-data")
    *     ),
    *     @OA\Parameter(
    *         name="accept",
    *         in="header",
    *         description="test",
    *         @OA\Schema(
    *             type="string",
    *             default="multipart/form-data" 
    *         )
    *     ),
    *     @OA\RequestBody(
    *       @OA\MediaType(
    *           mediaType="multipart/form-data",
    *           @OA\Schema(
    *               type="object", 
    *               @OA\Property(
    *                  property="file",
    *                  type="file",
    *                  @OA\Items(
    *                       type="string",
    *                       format="binary",
    *                  ),
    *               ),
    *           ),
    *       )
    *     ),
    * )
    *
    * @OA\Server(
    *      url=L5_SWAGGER_CONST_HOST,
    *      description="Login Server"
    * ),
    *
```

### Images:

![Capture332](https://user-images.githubusercontent.com/53174353/109765725-11396c00-7c17-11eb-864a-f9293942ad27.PNG)

![Capture333](https://user-images.githubusercontent.com/53174353/109765729-13032f80-7c17-11eb-8fe1-e132fa927fec.PNG)

### Steps To Reproduce:
Always get file required error

**Comment by diones-souza** [comment]
segue o exemplo de uma forma alternativa.

/**
     * @OA\Post(
     *      tags={"Files"},
     *      description="Envia os arquivos especificados para o servidor.",
     *      path="/files/upload",
     *      security={{"bearerAuth":{}}},
     *      @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="multipart/form-data",
     *             @OA\Schema(
     *                 type="object",
     *                 @OA\Property(
     *                     description="file to upload",
     *                     property="files[]",
     *                     type="array",
     *                     @OA\Items(
     *                       type="string",
     *                       format="binary",
     *                     ),
     *                 )
     *             )
     *         )
     *     ),
     *      @OA\Response(
     *          response=200,
     *          description="Successful operation",
     *       ),
     *      @OA\Response(
     *          response=401,
     *          description="Unauthenticated",
     *      ),
     *      @OA\Response(
     *          response=403,
     *          description="Forbidden"
     *      )
     * )
     * @param  \Illuminate\Http\Request $request
     * @return \Symfony\Component\HttpFoundation\BinaryFileResponse
     */
