### ISSUE TITLE
api/documentation does not render due to "ArgumentCountError Too few arguments to function l5_swagger_asset()"

### ISSUE THREAD

**Issue by MariosTheof** [DarkaOnLine/L5-Swagger#366]
- L5-Swagger Version: 8.0.4 
- PHP Version : 7.4.3
- OS: Linux Ubuntu Pop_OS! 20.04

### Description:
I try to open 127.0.0.1:8000/api/documentation and I get 
```
ArgumentCountError
Too few arguments to function l5_swagger_asset(), 1 passed in home/XXX/a2a8cebbc638ff6117d35fc16d5ddbd32cb1e0a2.php on line 70 and exactly 2 expected (View: /home/XXX/PhpstormProjects/XXX/resources/views/vendor/l5-swagger/index.blade.php) 
```
This basically points to  vendor/l5-swagger/index.blade.php. I did not edit the file whatsover. I used l5-swagger with laravel 6.20 previously, without any issues. 

The problem is that the page cannot even render due to the error.
### Steps To Reproduce:
Followed install instructions. 
1. vendor/l5-swagger/index.blade.php
2.  php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"

**Comment by diabelek** [comment]
Run 

`php artisan l5-swagger:generate`

**Comment by evolvoltd** [comment]
Also encountered same one, happened after updating to  package version 8.0.4
Fixed by
Deleting existing `resources/views/vendor/l5-swagger` dir first and then republish assets using `php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"`

**Comment by MariosTheof** [comment]
Thank you for your replies.

Deleting existing vendor worked. Also, by deleting project and re-cloning anew. 

Seems to be some conflict with configuration.
