### ISSUE TITLE
Exclude some enpoints from compilation

### ISSUE THREAD

**Issue by fabrizioanichini** [DarkaOnLine/L5-Swagger#369]
- L5-Swagger Version: 8.* (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.4
- OS: MacOs Big Sur

### Description:
Hi, when I run the command
`php artisan l5-swagger:generate --all`
I generate the docs for the default documentation and another one called 'open' . I would like to find a way to exclude some enpoints from the open documentation. The @OA\Info is the same for both of the documentations.
Is there any way to accomplish this?

Thanks.

**Comment by tsimohan** [comment]
change @OA to @@OA to ignore a particular endpoint in swagger ui

Example:
```
/**
     * Get all Resources
     *
     * @param   Request $request
     * @return  \Illuminate\Http\JsonResponse
     * @@OA\Get(
```
