### ISSUE TITLE
Clarification about "default" configuration parameter

### ISSUE THREAD

**Issue by illambo** [DarkaOnLine/L5-Swagger#374]
Hi all, I don't understand the functionality of the _default_ config parameter, can someone give me information about it?

https://github.com/DarkaOnLine/L5-Swagger/blob/7ccee68d7d870baa43642a6b94b8afcfe8dbe9b7/config/l5-swagger.php#L4

I thought it was used to change the default documentation but it doesn't work for me.
Thanks

**Comment by ms-zlab** [comment]
clear config cache in /bootstrap/cache helps on our side

**Comment by illambo** [comment]
Hi, thanks for the answer but it doesn't work for me, what version do you use?

Example:
```php
return [
    'default' => 'foo',
    'documentations' => [
        'default' => [
            'api' => [
                'title' => 'L5 Swagger UI',
            ],
            //[...]
    	],
    	'foo' => [
            'api' => [
                'title' => 'Foo Swagger UI',
            ],
            //[...]
    	]    
    ],
    //[...]
];    	 
```

Check title page in /api/documentation, for me remain "L5 Swagger UI"

**Comment by ms-zlab** [comment]
We switched from version 7.0.1  to 8.0.4
Also we did the deletion & creation described in the migration guide.

**Comment by illambo** [comment]
I'm using 8.0.4 too without any previous version, but (sorry if I ask you) does the above example work for you?

**Comment by ms-zlab** [comment]
Yes, i checked the generated api-docs.json for using the right `default` value.
For you i did an additional test, i changed title and the path `docs_json` (in the user defined config that you called "foo") and the new path is applied when i run `php artisan l5-swagger:generate` (json will be generated in new path).

The cache issue is also gone, i realized that i was in production mode - but this was a local issue for preparing dockers etc.

**Comment by ms-zlab** [comment]
The only difference what I realized now, is that I don't deleted the defaults in the root of the config (I just left them as they were).

**Comment by illambo** [comment]
Thanks for the support, I retry later. 
I'm going to close the question as I think it's just my local problem.
