### ISSUE TITLE
Web Assets are not created and searched for in the root folder of Laravel Project

### ISSUE THREAD

**Issue by fakharak** [DarkaOnLine/L5-Swagger#379]
- L5-Swagger Version: 3.48.0 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.3.27
- Laravel Framework 7.30.4
- OS: Docker's bash
  -- Distributor ID:	Debian
 --  Description:	Debian GNU/Linux 10 (buster)
 -- Release:	10
 -- Codename:	buster

### Description:
After everything passed during installation and generation of document, the screen showed blank.

The web assets (css and JS files) did not exist on the location where they were expected.

Second the expected location of Web Assets is docs/asset/ in the root "public" folder. I suggest that they should be located (and be pointed by) in a space local to the package both for assuring Maintainability and Security.

Can you please fix the above ?

Thanks in anticipation.

Kind Regards,

Fakhar Anwar

### Steps To Reproduce:
We used the link below to integrate this Swagger Package within Laravel Project.
https://blog.quickadminpanel.com/laravel-api-documentation-with-openapiswagger/

**Comment by AubreyHewes** [comment]
@fakharak I had this same problem (also using docker). I was getting an nginx 404 on the swagger-ui assets (i.e. blank screen). It came down to the used nginx image serving static assets (things like extension css/js/etc) directly, instead of passing them through the index.php.

I had to tweak the image's nginx config to ensure everything is passed through index.php.

Hope this helps!

**Comment by noyidoit** [comment]
> 

You should add this line to nginx's conf:
```nginx
error_page 404 /index.php;
```
Check Laravel'docs [here](https://laravel.com/docs/8.x/deployment#nginx)

**Comment by noyidoit** [comment]
> @fakharak I had this same problem (also using docker). I was getting an nginx 404 on the swagger-ui assets (i.e. blank screen). It came down to the used nginx image serving static assets (things like extension css/js/etc) directly, instead of passing them through the index.php where the correct asset route can be discovered.
> 
> I had to tweak the image's nginx config to ensure everything is passed through index.php.
> 
> Hope this helps!

You should add this line to nginx's conf:
```nginx
error_page 404 /index.php;
```

Check Laravel'docs here
