### ISSUE TITLE
optimize command this error

### ISSUE THREAD

**Issue by mohammadgh1370** [DarkaOnLine/L5-Swagger#380]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):7.4
- OS:ubuntu

php artisan optimize
```
Configuration cache cleared!

   LogicException 

  Your configuration files are not serializable.

  at vendor/laravel/framework/src/Illuminate/Foundation/Console/ConfigCacheCommand.php:71
     67▕             require $configPath;
     68▕         } catch (Throwable $e) {
     69▕             $this->files->delete($configPath);
     70▕ 
  ➜  71▕             throw new LogicException('Your configuration files are not serializable.', 0, $e);
     72▕         }
     73▕ 
     74▕         $this->info('Configuration cached successfully!');
     75▕     }

  1   bootstrap/cache/config.php:535
      Error::("Call to undefined method OpenApi\Processors\MergeIntoOpenApi::__set_state()")

      +25 vendor frames 
  27  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
> this error when optimize command

**Comment by DarkaOnLine** [comment]
So the problem is this call: https://github.com/DarkaOnLine/L5-Swagger/commit/8afb0f4559825c2027829f95a298e8aabc05eece#diff-0ae1564e6e748dbcccd1c1bcdbc3aecc0aa625774841639b0a2f952e3f877fb8R120 if yes we can move it back to `getScanOptions()`

**Comment by mohammadgh1370** [comment]
thanks for the reply 

I do not know what this part does
```
scanOptions => []
```
But by commenting on this part

```
'processors' => array_merge(
                \OpenApi\Analysis::processors(),
                [
                    // new \App\SwaggerProcessors\SchemaQueryParameter(),
                ]
            ),
```
, the optimize command works properly

**Comment by DarkaOnLine** [comment]
Can you check if it works with this change - https://github.com/DarkaOnLine/L5-Swagger/pull/383

**Comment by mohammadgh1370** [comment]
yes it worked for me

**Comment by DarkaOnLine** [comment]
Thanks, 🏷 new release: https://github.com/DarkaOnLine/L5-Swagger/releases/tag/8.0.6

**Comment by peter-at-bpt** [comment]
Thanks so much for the quick turnaround @DarkaOnLine , gotta love waking up to a fix for a blocking change!! ☕
