### ISSUE TITLE
How can i order api tags ?

### ISSUE THREAD

**Issue by codewithgok** [DarkaOnLine/L5-Swagger#381]
- L5-Swagger Version: ^8.0
- PHP Version PHP 8.0.3 
- OS: Linux

### Description:

Hi i want to reorder my tags at documentation but i havent found a solution. I have tried to add x={"order":1} but it didnt work.

### Steps To Reproduce:

Create multiple tags. 
Connect endpoints to tags.
Try to reorder tags.

**Comment by DarkaOnLine** [comment]
You can define `tagsSorter` callback: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md
