### ISSUE TITLE
How to use multiple paths inswagger for api?

### ISSUE THREAD

**Issue by creativedevs** [DarkaOnLine/L5-Swagger#384]
- L5-Swagger Version: ^8.0
- PHP Version (`php -v`): 7.3
- OS: debian

### Description:

I have different paths for apis

exa,
http://host/test/data/{route}

http://host/v1/m1/data/{route}

How can I use two path as base path ?

**Comment by raviroshanmehta** [comment]
i am exactly looking for the same solution.  any work around for this problem ?

**Comment by vibonacci** [comment]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 8.3
- OS: N.A.

### Description:
OpenApi 3.x, swagger-php and swagger-ui support multiple servers / base URLs to be defined.

However, l5-swagger.php config file will not accept an array - or anything else for that matter - to have multiple servers end up in the servers array in the open-api-docs.json.

I've tried in l5-swagger.php:

1.
```
           /*
             * Edit to set the api's base path
            */
            'base' => env('L5_SWAGGER_BASE_PATH', [
                ['url' => env('API_URL')],
                ['url' => env('APP_URL')],
            ]),

```
2.
```
            /*
             * Edit to set the api's base path
            */
            'base' => env('L5_SWAGGER_BASE_PATH', [
                env('API_URL'),
                env('APP_URL'),
            ]),
```
Both do not result in the proper structure:

1.
```
    "servers": [
        {
            "url": [
                "http://localhost/api",
                "http://localhost"
            ]
        }
    ],
```

![afbeelding](https://github.com/DarkaOnLine/L5-Swagger/assets/9674553/bd337334-4e60-4482-a8e5-780d5e12cacb)


2.
```
    "servers": [
        {
            "url": [
                {
                    "url": "http://localhost/api"
                },
                {
                    "url": "http://localhost"
                }
            ]
        }
    ],
```


Could support for this be added? It is quite useful.
Or this there another way to hook into the open-api-docs.json generation to add it manually in the meantime?

**Comment by BorisWild** [comment]
https://github.com/DarkaOnLine/L5-Swagger/issues/601#issuecomment-2118981787
