### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by stromox** [DarkaOnLine/L5-Swagger#39]
Hi,

i'm using laravel 5.3 with passport apis, when I tried this command php artisan l5-swagger:generate 
i found error down blow "l5-swagger:publis" runed
[ErrorException]                
Required @SWG\Info() not found

**Comment by DarkaOnLine** [comment]
You are missing annotations. See example: https://github.com/DarkaOnLine/L5-Swagger/blob/master/tests/storage/annotations/ApiAnotationsExample.php

**Comment by stromox** [comment]
How can i add it?
create into storage manually?

**Comment by DarkaOnLine** [comment]
You can create file in directory which you are scanning for annotations and put this and other shared information in it.
