### ISSUE TITLE
Bearer Token Auto set in header modal (question)

### ISSUE THREAD

**Issue by kvinay3** [DarkaOnLine/L5-Swagger#392]
L5-Swagger Version: ^8.0
PHP Version PHP 8.0.3
OS: Linux
Description:
Hi i want set my Bearer token Directly to auth modal after user has successfully logged in using credentials provided.

Steps To Reproduce:
Provide the Username / Password to auth api then hit submit.
Once we get success response from api the token we get token in response.
The Token we got from response should automatically set to Authorisation Header . Instead of copy pasting it in modal.

![image](https://user-images.githubusercontent.com/23552349/122059510-58381f80-ce0a-11eb-9578-624a863c441f.png)

**Comment by DarkaOnLine** [comment]
`L5_SWAGGER_UI_PERSIST_AUTHORIZATION ` flag should help: https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php#L283
