### ISSUE TITLE
Basic.Auth does not work with l5-swagger

### ISSUE THREAD

**Issue by MartinWeidner** [DarkaOnLine/L5-Swagger#396]
- L5-Swagger Version: 8.0.4
- PHP Version: 7.4.3
- OS: Linux DevLaptop 5.4.0-77-generic # 86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Description:
I would like to prevent access to the api documentation with basic auth. I've created a table api_users and a guard: 

```
        'api_docs' => [
            'driver' => 'session',
            'provider' => 'api_users',
        ],
```

provider api_users also exists:

```
        'api_users' => [
            'driver' => 'eloquent',
            'model' => App\Model\ApiUser::class,
        ],
```

I've added the middleware to l5-swagger.php:

```
            /*
             * Middleware allows to prevent unexpected access to API documentation
            */
            'middleware' => [
                'api' => [],
                'asset' => [],
                'docs' => [
					'auth.basic:api_docs,name'
				],
                'oauth2_callback' => [],
            ],
```
All I get is this error message:

![Screenshot_2021-07-07_13-13-01](https://user-images.githubusercontent.com/7785873/124749906-1c820880-df25-11eb-88ce-df9f50e5accb.png)

To test, if the basic auth is working, i create a test route and attach the middleware:

```
Route::get('/test', function () {
	dd("Auth successfully");
})->middleware('auth.basic:api_docs,name');
```
This working: I get the login prompt, enter the correct data and see "Auth successfully".

How do I get this middleware working in laravel swagger?

Thanks in advance

best regards 
Martin

**Comment by YaoMiss** [comment]
You can try this
```
 * @OA\SecurityScheme(
 *     type="apiKey",
 *     in="header",
 *     securityScheme="api_key",
 *     name="Authorization",
 * )
```
```
* @OA\Post(
     *     path="/api/subscription/bind",
     *     tags={"subscription"},
     *     security = {{"api_key": {}}},
```

**Comment by jcmcclorey** [comment]
@MartinWeidner see Issue #122
