### ISSUE TITLE
Only 1 of 2 API documentations described in l5-swagger.php loads successfully

### ISSUE THREAD

**Issue by sanderalvin** [DarkaOnLine/L5-Swagger#398]
### Environment:
- L5-Swagger Version: 8.0.7     
- PHP Version (`php -v`): 7.3.27-1
- OS: MacOS (using docker container to run the application)

### Description:
I am trying to create 2 API documentation pages - internal and partner API. For that I have blocks 'internal' and and 'partner' inside l5-swagger.php file.

**l5-swagger.php**
```
return [
    'default' => 'default',
    'documentations' => [
      'internal' => [
            'api' => [
                'title' => "Internal API",
            ],

            'routes' => [
                /*
                 * Route for accessing api documentation interface
                */
                'api' => 'api/documentation-new', 
                'docs' => 'docs',
                'oauth2_callback' => 'api/oauth2-callback',
            ],
            'paths' => [
                /*
                 * File name of the generated json documentation file
                */
                'docs_json' => 'api-docs.json',

                /*
                 * File name of the generated YAML documentation file
                */
                'docs_yaml' => 'api-docs.yaml',

                /*
                * Set this to `json` or `yaml` to determine which documentation file to use in UI
                */
                'format_to_use_for_docs' => env('L5_FORMAT_TO_USE_FOR_DOCS', 'json'),

                /*
                 * Absolute paths to directory containing the swagger annotations are stored.
                */
                'annotations' => [
                    base_path('app'),
                ],
            ],
        ],
      'partner' => [
        'api' => [
          'title' => "Partner API",
        ],

        'routes' => [
          /*
           * Route for accessing api documentation interface
          */
          'api' => 'partner-api/documentation-new',
          'docs' => 'docs',
          'oauth2_callback' => 'api/oauth2-callback',
        ],
        'paths' => [
          /*
           * File name of the generated json documentation file
          */
          'docs_json' => 'lo-api-docs.json',

          /*
           * File name of the generated YAML documentation file
          */
          'docs_yaml' => 'lo-api-docs.yaml',

          /*
          * Set this to `json` or `yaml` to determine which documentation file to use in UI
          */
          'format_to_use_for_docs' => env('L5_FORMAT_TO_USE_FOR_DOCS', 'json'),

          /*
           * Absolute paths to directory containing the swagger annotations are stored.
          */
          'annotations' => [
            base_path('app'),
          ],
        ],
      ],
    ],
    'defaults' => [
        'routes' => [
            /*
             * Route for accessing parsed swagger annotations.
            */
            'docs' => 'docs',

            /*
             * Route for Oauth2 authentication callback.
            */
            'oauth2_callback' => 'api/oauth2-callback',

            /*
             * Middleware allows to prevent unexpected access to API documentation
            */
            'middleware' => [
                'api' => [],
                'asset' => [],
                'docs' => [],
                'oauth2_callback' => [],
            ],
          
          

            /*
             * Route Group options
            */
            'group_options' => [],
        ],

        'paths' => [
            /*
             * Absolute path to location where parsed annotations will be stored
            */
            'docs' => storage_path('api-docs'),

            /*
             * Absolute path to directory where to export views
            */
            'views' => base_path('resources/views/vendor/l5-swagger'),

            /*
             * Edit to set the api's base path
            */
            'base' => env('APP_URL' . '/api', null),

            /*
             * Edit to set path where swagger ui assets should be stored
            */
            'swagger_ui_assets_path' => env('L5_SWAGGER_UI_ASSETS_PATH', 'vendor/swagger-api/swagger-ui/dist/'),

            /*
             * Absolute path to directories that should be exclude from scanning
             * @deprecated Please use `scanOptions.exclude`
             * `scanOptions.exclude` overwrites this
            */
            'excludes' => [],
        ],

        'scanOptions' => [
            /**
             * analyser: defaults to \OpenApi\StaticAnalyser .
             * @see \OpenApi\scan
             */
            'analyser' => null,

            /**
             * analysis: defaults to a new \OpenApi\Analysis .
             * @see \OpenApi\scan
             */
            'analysis' => null,

            /**
             * Custom query path processors classes.
             *
             * @link https://github.com/zircote/swagger-php/tree/master/Examples/schema-query-parameter-processor
             * @see \OpenApi\scan
             */
            'processors' => [
                // new \App\SwaggerProcessors\SchemaQueryParameter(),
            ],

            /**
             * pattern: string       $pattern File pattern(s) to scan (default: *.php) .
             * @see \OpenApi\scan
             */
            'pattern' => null,

            /*
             * Absolute path to directories that should be exclude from scanning
             * @note This option overwrites `paths.excludes`
             * @see \OpenApi\scan
            */
            'exclude' => [],
        ],

        /*
         * API security definitions. Will be generated into documentation file.
        */
        'securityDefinitions' => [
            'securitySchemes' => [
              'bearerAuth' => [
                'securityScheme' => "bearerAuth",
                'type' => "http",
                'scheme' => "bearer",
                'bearerFormat' => "JWT",
              ],
                /*
                 * Examples of Security schemes
                */
                /*
                'api_key_security_example' => [ // Unique name of security
                    'type' => 'apiKey', // The type of the security scheme. Valid values are "basic", "apiKey" or "oauth2".
                    'description' => 'A short description for security scheme',
                    'name' => 'api_key', // The name of the header or query parameter to be used.
                    'in' => 'header', // The location of the API key. Valid values are "query" or "header".
                ],
                'oauth2_security_example' => [ // Unique name of security
                    'type' => 'oauth2', // The type of the security scheme. Valid values are "basic", "apiKey" or "oauth2".
                    'description' => 'A short description for oauth2 security scheme.',
                    'flow' => 'implicit', // The flow used by the OAuth2 security scheme. Valid values are "implicit", "password", "application" or "accessCode".
                    'authorizationUrl' => 'http://example.com/auth', // The authorization URL to be used for (implicit/accessCode)
                    //'tokenUrl' => 'http://example.com/auth' // The authorization URL to be used for (password/application/accessCode)
                    'scopes' => [
                        'read:projects' => 'read your projects',
                        'write:projects' => 'modify projects in your account',
                    ]
                ],
                */

                /* Open API 3.0 support
                'passport' => [ // Unique name of security
                    'type' => 'oauth2', // The type of the security scheme. Valid values are "basic", "apiKey" or "oauth2".
                    'description' => 'Laravel passport oauth2 security.',
                    'in' => 'header',
                    'scheme' => 'https',
                    'flows' => [
                        "password" => [
                            "authorizationUrl" => config('app.url') . '/oauth/authorize',
                            "tokenUrl" => config('app.url') . '/oauth/token',
                            "refreshUrl" => config('app.url') . '/token/refresh',
                            "scopes" => []
                        ],
                    ],
                ],
                */
            ],
          'security' => [
            /*
             * Examples of Securities
            */
            [
              'bearerAuth' => []
              /*
              'oauth2_security_example' => [
                  'read',
                  'write'
              ],
    
              'passport' => []
              */
            ],
          ]
        ],

        /*
         * Set this to `true` in development mode so that docs would be regenerated on each request
         * Set this to `false` to disable swagger generation on production
        */
        'generate_always' => env('L5_SWAGGER_GENERATE_ALWAYS', false),

        /*
         * Set this to `true` to generate a copy of documentation in yaml format
        */
        'generate_yaml_copy' => env('L5_SWAGGER_GENERATE_YAML_COPY', false),

        /*
         * Edit to trust the proxy's ip address - needed for AWS Load Balancer
         * string[]
        */
        'proxy' => false,

        /*
         * Configs plugin allows to fetch external configs instead of passing them to SwaggerUIBundle.
         * See more at: https://github.com/swagger-api/swagger-ui#configs-plugin
        */
        'additional_config_url' => null,

        /*
         * Apply a sort to the operation list of each API. It can be 'alpha' (sort by paths alphanumerically),
         * 'method' (sort by HTTP method).
         * Default is the order returned by the server unchanged.
        */
        'operations_sort' => env('L5_SWAGGER_OPERATIONS_SORT', null),

        /*
         * Pass the validatorUrl parameter to SwaggerUi init on the JS side.
         * A null value here disables validation.
        */
        'validator_url' => null,

        /*
         * Persist authorization login after refresh browser
         */
        'persist_authorization' => true,

        /*
         * Uncomment to add constants which can be used in annotations
         */
        'constants' => [
          'L5_SWAGGER_CONST_HOST' => env('APP_URL') . '/api',
        ],
    ],
];
```

Loading  http://localhost:8180/partner-api/documentation-new succeeds nicely. However http://localhost:8180/api/documentation-new does not load and an error is thrown:

> Symfony\Component\Routing\Exception\RouteNotFoundException
> Route [l5-swagger.internal.docs] not defined.

When changing the order of 'internal' and 'partner' like this:
```
return [
    'documentations' => [
      'partner' => [],
      'internal' => [],
    ],
     (etc...)
]
```

then loading  http://localhost:8180/api/documentation-new succeeds nicely. However http://localhost:8180/partner-api/documentation-new does not load and an error is thrown:

> Symfony\Component\Routing\Exception\RouteNotFoundException
> Route [l5-swagger.partner.docs] not defined.

In the picture you can see the \Illuminate\Routing\RouteCollection data. As you see: l5-swagger.partner.docs is missing:
![image](https://user-images.githubusercontent.com/10141791/126359569-d480db54-7060-4d87-9991-bf5b4760c963.png)

Seems that the order of the 'documentation'  elements plays some role in this bug.  I read PR https://github.com/DarkaOnLine/L5-Swagger/pull/270 and issue https://github.com/DarkaOnLine/L5-Swagger/issues/349 but could not find a solution there.

### Steps To Reproduce:
Use the l5-swagger.php contents to reproduce the bug.

**Comment by alexnen** [comment]
same issue

**Comment by lenden31** [comment]
> The problem in route generations. If you don't set params **docs** and **oauth2_callback** to each configuration documentation touter generator create the same routes for each document here [/src/routes.php](https://github.com/DarkaOnLine/L5-Swagger/blob/5e3d9c067797ebc35304d20acd94aeb40cde2825/src/routes.php) lines [43](https://github.com/DarkaOnLine/L5-Swagger/blob/master/src/routes.php#L43), [49](https://github.com/DarkaOnLine/L5-Swagger/blob/master/src/routes.php#L49), [57](https://github.com/DarkaOnLine/L5-Swagger/blob/master/src/routes.php#L57)
> 
> As **bad varianf** for fix we can use next config and view files
> 
> **l5-swagger.php**
> 
> ```
> <?php
> 
> return [
>     'legacy' => false,
>     'default' => "default",
>     'documentations' => [
>         'spa'     => [
>             'api' => [
>                 'title' => 'SPA API',
>             ],
> 
>             'routes' => [
>                 /*
>                  * Route for accessing api documentation interface
>                 */
>                 'api' => 'api/spa/documentation',
>                 'docs' => storage_path('api-docs/spa'),
>                 'oauth2_callback' => 'api/spa/oauth2-callback',
>             ],
>             'paths' => [
>                 /*
>                  * File name of the generated json documentation file
>                 */
>                 'docs_json' => 'spa-docs.json',
> 
>                 /*
>                  * File name of the generated YAML documentation file
>                 */
>                 'docs_yaml' => 'spa-docs.yaml',
> 
>                 /*
>                 * Set this to `json` or `yaml` to determine which documentation file to use in UI
>                 */
>                 'format_to_use_for_docs' => env('L5_FORMAT_TO_USE_FOR_DOCS', 'json'),
> 
>                 /*
>                  * Absolute paths to directory containing the swagger annotations are stored.
>                 */
>                 'annotations' => [
>                     base_path('app'),
>                     base_path('Modules'),
>                 ],
> 
>             ],
>         ],
>         'default' => [
>             'api' => [
>                 'title' => 'L5 Swagger UI',
>             ],
> 
>             'routes' => [
>                 /*
>                  * Route for accessing api documentation interface
>                 */
>                 'api' => 'api/documentation',
> //                'docs' => storage_path('api-docs'),
> //                'oauth2_callback' => 'api/oauth2-callback',
>             ],
>             'paths' => [
>                 /*
>                  * File name of the generated json documentation file
>                 */
>                 'docs_json' => 'api-docs.json',
> 
>                 /*
>                  * File name of the generated YAML documentation file
>                 */
>                 'docs_yaml' => 'api-docs.yaml',
> 
>                 /*
>                 * Set this to `json` or `yaml` to determine which documentation file to use in UI
>                 */
>                 'format_to_use_for_docs' => env('L5_FORMAT_TO_USE_FOR_DOCS', 'json'),
> 
>                 /*
>                  * Absolute paths to directory containing the swagger annotations are stored.
>                 */
>                 'annotations' => [
>                     base_path('app'),
>                     base_path('Modules'),
>                 ],
> 
>             ],
>         ],
>     ],
>     'defaults' => [
>         'routes' => [
>             /*
>              * Route for accessing parsed swagger annotations.
>             */
>             'docs' => 'docs',
> 
>             /*
>              * Route for Oauth2 authentication callback.
>             */
>             'oauth2_callback' => 'api/oauth2-callback',
> 
>             /*
>              * Middleware allows to prevent unexpected access to API documentation
>             */
>             'middleware' => [
>                 'api' => [
>                     \App\Http\Middleware\EncryptCookies::class,
>                     \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
>                     \Illuminate\Session\Middleware\StartSession::class,
>                     \Illuminate\View\Middleware\ShareErrorsFromSession::class,
>                     \App\Http\Middleware\VerifyCsrfToken::class,
>                     \Illuminate\Routing\Middleware\SubstituteBindings::class,
>                     'auth',
>                 ],
>                 'asset' => [],
>                 'docs' => [],
>                 'oauth2_callback' => [],
>             ],
> 
>             /*
>              * Route Group options
>             */
>             'group_options' => [],
>         ],
> 
>         'paths' => [
>             /*
>              * Absolute path to location where parsed annotations will be stored
>             */
>             'docs' => storage_path('api-docs'),
> 
>             /*
>              * Absolute path to directory where to export views
>             */
>             'views' => base_path('resources/views/vendor/l5-swagger'),
> 
>             /*
>              * Edit to set the api's base path
>             */
>             'base' => env('L5_SWAGGER_BASE_PATH', null),
> 
>             /*
>              * Edit to set path where swagger ui assets should be stored
>             */
>             'swagger_ui_assets_path' => env('L5_SWAGGER_UI_ASSETS_PATH', 'vendor/swagger-api/swagger-ui/dist/'),
> 
>             /*
>              * Absolute path to directories that should be exclude from scanning
>              * @deprecated Please use `scanOptions.exclude`
>              * `scanOptions.exclude` overwrites this
>             */
>             'excludes' => [],
>         ],
> 
>         'scanOptions' => [
>             /**
>              * analyser: defaults to \OpenApi\StaticAnalyser .
>              * @see \OpenApi\scan
>              */
>             'analyser' => null,
> 
>             /**
>              * analysis: defaults to a new \OpenApi\Analysis .
>              * @see \OpenApi\scan
>              */
>             'analysis' => null,
> 
>             /**
>              * Custom query path processors classes.
>              *
>              * @link https://github.com/zircote/swagger-php/tree/master/Examples/schema-query-parameter-processor
>              * @see \OpenApi\scan
>              */
>             'processors' => [
>                 // new \App\SwaggerProcessors\SchemaQueryParameter(),
>             ],
> 
>             /**
>              * pattern: string       $pattern File pattern(s) to scan (default: *.php) .
>              * @see \OpenApi\scan
>              */
>             'pattern' => null,
> 
>             /*
>              * Absolute path to directories that should be exclude from scanning
>              * @note This option overwrites `paths.excludes`
>              * @see \OpenApi\scan
>             */
>             'exclude' => [],
>         ],
> 
>         /*
>          * API security definitions. Will be generated into documentation file.
>         */
>         'securityDefinitions' => [
>             'securitySchemes' => [],
>             'security' => [],
>         ],
> 
>         /*
>          * Set this to `true` in development mode so that docs would be regenerated on each request
>          * Set this to `false` to disable swagger generation on production
>         */
>         'generate_always' => env('L5_SWAGGER_GENERATE_ALWAYS', false),
> 
>         /*
>          * Set this to `true` to generate a copy of documentation in yaml format
>         */
>         'generate_yaml_copy' => env('L5_SWAGGER_GENERATE_YAML_COPY', false),
> 
>         /*
>          * Edit to trust the proxy's ip address - needed for AWS Load Balancer
>          * string[]
>         */
>         'proxy' => false,
> 
>         /*
>          * Configs plugin allows to fetch external configs instead of passing them to SwaggerUIBundle.
>          * See more at: https://github.com/swagger-api/swagger-ui#configs-plugin
>         */
>         'additional_config_url' => null,
> 
>         /*
>          * Apply a sort to the operation list of each API. It can be 'alpha' (sort by paths alphanumerically),
>          * 'method' (sort by HTTP method).
>          * Default is the order returned by the server unchanged.
>         */
>         'operations_sort' => env('L5_SWAGGER_OPERATIONS_SORT', null),
> 
>         /*
>          * Pass the validatorUrl parameter to SwaggerUi init on the JS side.
>          * A null value here disables validation.
>         */
>         'validator_url' => null,
> 
>         /*
>          * Persist authorization login after refresh browser
>          */
>         'persist_authorization' => true,
> 
>         /*
>          * Uncomment to add constants which can be used in annotations
>          */
>         // 'constants' => [
>         // 'L5_SWAGGER_CONST_HOST' => env('L5_SWAGGER_CONST_HOST', 'http://my-default-host.com'),
>         // ],
>     ],
> ];
> ```
> 
> **index.blade.php**
> 
> ```
> 
> <!DOCTYPE html>
> <html lang="en">
> <head>
>   <meta charset="UTF-8">
>   <title>{{config('l5-swagger.documentations.'.$documentation.'.api.title')}}</title>
>   <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700" rel="stylesheet">
>   <link rel="stylesheet" type="text/css" href="{{ l5_swagger_asset("default", 'swagger-ui.css') }}" >
>   <link rel="icon" type="image/png" href="{{ l5_swagger_asset("default", 'favicon-32x32.png') }}" sizes="32x32" />
>   <link rel="icon" type="image/png" href="{{ l5_swagger_asset("default", 'favicon-16x16.png') }}" sizes="16x16" />
>   <style>
>     html
>     {
>         box-sizing: border-box;
>         overflow: -moz-scrollbars-vertical;
>         overflow-y: scroll;
>     }
>     *,
>     *:before,
>     *:after
>     {
>         box-sizing: inherit;
>     }
> 
>     body {
>       margin:0;
>       background: #fafafa;
>     }
>   </style>
> </head>
> 
> <body>
> 
> <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="position:absolute;width:0;height:0">
>   <defs>
>     <symbol viewBox="0 0 20 20" id="unlocked">
>           <path d="M15.8 8H14V5.6C14 2.703 12.665 1 10 1 7.334 1 6 2.703 6 5.6V6h2v-.801C8 3.754 8.797 3 10 3c1.203 0 2 .754 2 2.199V8H4c-.553 0-1 .646-1 1.199V17c0 .549.428 1.139.951 1.307l1.197.387C5.672 18.861 6.55 19 7.1 19h5.8c.549 0 1.428-.139 1.951-.307l1.196-.387c.524-.167.953-.757.953-1.306V9.199C17 8.646 16.352 8 15.8 8z"></path>
>     </symbol>
> 
>     <symbol viewBox="0 0 20 20" id="locked">
>       <path d="M15.8 8H14V5.6C14 2.703 12.665 1 10 1 7.334 1 6 2.703 6 5.6V8H4c-.553 0-1 .646-1 1.199V17c0 .549.428 1.139.951 1.307l1.197.387C5.672 18.861 6.55 19 7.1 19h5.8c.549 0 1.428-.139 1.951-.307l1.196-.387c.524-.167.953-.757.953-1.306V9.199C17 8.646 16.352 8 15.8 8zM12 8H8V5.199C8 3.754 8.797 3 10 3c1.203 0 2 .754 2 2.199V8z"/>
>     </symbol>
> 
>     <symbol viewBox="0 0 20 20" id="close">
>       <path d="M14.348 14.849c-.469.469-1.229.469-1.697 0L10 11.819l-2.651 3.029c-.469.469-1.229.469-1.697 0-.469-.469-.469-1.229 0-1.697l2.758-3.15-2.759-3.152c-.469-.469-.469-1.228 0-1.697.469-.469 1.228-.469 1.697 0L10 8.183l2.651-3.031c.469-.469 1.228-.469 1.697 0 .469.469.469 1.229 0 1.697l-2.758 3.152 2.758 3.15c.469.469.469 1.229 0 1.698z"/>
>     </symbol>
> 
>     <symbol viewBox="0 0 20 20" id="large-arrow">
>       <path d="M13.25 10L6.109 2.58c-.268-.27-.268-.707 0-.979.268-.27.701-.27.969 0l7.83 7.908c.268.271.268.709 0 .979l-7.83 7.908c-.268.271-.701.27-.969 0-.268-.269-.268-.707 0-.979L13.25 10z"/>
>     </symbol>
> 
>     <symbol viewBox="0 0 20 20" id="large-arrow-down">
>       <path d="M17.418 6.109c.272-.268.709-.268.979 0s.271.701 0 .969l-7.908 7.83c-.27.268-.707.268-.979 0l-7.908-7.83c-.27-.268-.27-.701 0-.969.271-.268.709-.268.979 0L10 13.25l7.418-7.141z"/>
>     </symbol>
> 
> 
>     <symbol viewBox="0 0 24 24" id="jump-to">
>       <path d="M19 7v4H5.83l3.58-3.59L8 6l-6 6 6 6 1.41-1.41L5.83 13H21V7z"/>
>     </symbol>
> 
>     <symbol viewBox="0 0 24 24" id="expand">
>       <path d="M10 18h4v-2h-4v2zM3 6v2h18V6H3zm3 7h12v-2H6v2z"/>
>     </symbol>
> 
>   </defs>
> </svg>
> 
> <div id="swagger-ui"></div>
> 
> <script src="{{ l5_swagger_asset("default", 'swagger-ui-bundle.js') }}"> </script>
> <script src="{{ l5_swagger_asset("default", 'swagger-ui-standalone-preset.js') }}"> </script>
> {{ config("l5-swagger.$documentation.paths.docs_json") }}
> <script>
> window.onload = function() {
>   // Build a system
>   const ui = SwaggerUIBundle({
>     dom_id: '#swagger-ui',
> 
>     url: "{{ route('l5-swagger.default.docs', config("l5-swagger.documentations.$documentation.paths.docs_json")) }}",
>     operationsSorter: {!! isset($operationsSorter) ? '"' . $operationsSorter . '"' : 'null' !!},
>     configUrl: {!! isset($configUrl) ? '"' . $configUrl . '"' : 'null' !!},
>     validatorUrl: {!! isset($validatorUrl) ? '"' . $validatorUrl . '"' : 'null' !!},
>     oauth2RedirectUrl: "{{ route('l5-swagger.default.oauth2_callback') }}",
> 
>     requestInterceptor: function(request) {
>       {{--request.headers['X-CSRF-TOKEN'] = '{{ csrf_token() }}';--}}
>       return request;
>     },
> 
>     presets: [
>       SwaggerUIBundle.presets.apis,
>       SwaggerUIStandalonePreset
>     ],
> 
>     plugins: [
>       SwaggerUIBundle.plugins.DownloadUrl
>     ],
> 
>     layout: "StandaloneLayout",
> 
>     persistAuthorization: {!! config('l5-swagger.defaults.persist_authorization') ? 'true' : 'false' !!},
>   })
> 
>   window.ui = ui
> }
> </script>
> </body>
> 
> </html>
> ```

It's greate advice! Now it works, thank you
