### ISSUE TITLE
Examples tag

### ISSUE THREAD

**Issue by luizeduard0** [DarkaOnLine/L5-Swagger#40]
I can't seem to get examples tag working, or maybe I'm doing something wrong.

/**
   * @SWG\Response(
   *      response=200,
   *      description="Success",
   *      examples={"application/json": {"id": "1"}}
   * 
   */

**Comment by DarkaOnLine** [comment]
@luizeduard0 did you solved this ?

**Comment by luizeduard0** [comment]
@DarkaOnLine I didn't... any solution?

**Comment by sergio-apithy** [comment]
Tags works, but you need set the tags after the path, if you don't do that on this way tags does not work.

/**
     *
     * @SWG\Get(
     *   path="/users",
     *   operationId="api.users.index",
     *   produces={"application/json"},
     *   tags={"users"},
     *   security={
     *     {"passport": {}},
     *   },
     *   summary="Return a List of Users",
     *   @SWG\Response(response=200, description="successful operation")
     * )
     *
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
