### ISSUE TITLE
It crash when having no token

### ISSUE THREAD

**Issue by falahatiali** [DarkaOnLine/L5-Swagger#401]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):
- OS:

### Description:

When we dont put token on Authorize section webpage crash and we have to close and open another tab. What would we do for preventing crash current page if we get 500 error?

**Comment by DarkaOnLine** [comment]
looks like your are getting 500 from your code, or please provide more information
