### ISSUE TITLE
route:cache

### ISSUE THREAD

**Issue by tibi00** [DarkaOnLine/L5-Swagger#41]
Hi,
The `route:cache` artisan command does not work, looks like the reason is the `docs` route.

**Comment by DarkaOnLine** [comment]
Can you give me more information ?

**Comment by tibi00** [comment]
sure,
after running the `php artisan route:cache` command, I get the following error:
` Unable to prepare route [docs/{page?}] for serialization. Uses Closure.`

**Comment by DarkaOnLine** [comment]
According to this: https://github.com/laravel/framework/issues/7319#issuecomment-73362932 you can't use caching if you have one or more closure routes :(

But from the 3.1 version package is using controllers instead of closures.  Please update package to the latest version.

**Comment by tibi00** [comment]
I did not see the newer version, my bad. After the update works properly! :)
Thanks,
Tibor

**Comment by DarkaOnLine** [comment]
Glad to help ;)

**Comment by saber13812002** [comment]
open in incognito in chrome or as a private tab in firefix
