### ISSUE TITLE
Bug with analyser & analysis config parameters

### ISSUE THREAD

**Issue by jlouche** [DarkaOnLine/L5-Swagger#414]
- L5-Swagger Version: 8.0.9
- PHP Version: 7.4.22

### Description:
Hello,

I try to implement a custom analysis but it's impossible due to the way Laravel caches the configuration.
I solved the problem but I do not have the rights to create a new branch to do a pull request.

The problem is also present with the analyzer option.

I describe below how to reproduce the problem and fix it.

Thank you

### Steps To Reproduce:
If I try to indicate the custom class to use :
```php
        // ...
        'scanOptions' => [
            // ....   

            /**
             * analysis: defaults to a new \OpenApi\Analysis .
             *
             * @see \OpenApi\scan
             */
            'analysis' => CustomAnalysis::class,
            //...
        ]
        //...
```
When I use the command ```php artisan l5-swagger:generate```, I have a PHP TypeError :  ```Argument 2 passed to OpenApi\Generator::generate() must be an instance of OpenApi\Analysis or null, string given,```

And if I try to indicate a new instance of the custom class :
```php
        // ...
        'scanOptions' => [
            // ....   

            /**
             * analysis: defaults to a new \OpenApi\Analysis .
             *
             * @see \OpenApi\scan
             */
            'analysis' => new CustomAnalysis
            //...
        ]
        //...
```
When I use the command ```php artisan config:cache```, I have a PHP LogicException :  ```Your configuration files are not serializable.```

### Correction of the problem:

In class ```\L5Swagger\Generator```, in function ```protected function getScanOptions``` line 223, I add these lines :
```php
        if (isset($options[self::SCAN_OPTION_ANALYSER]) && is_string($options[self::SCAN_OPTION_ANALYSER])) {
            $options[self::SCAN_OPTION_ANALYSER] = new $options[self::SCAN_OPTION_ANALYSER];
        }

        if (isset($options[self::SCAN_OPTION_ANALYSIS]) && is_string($options[self::SCAN_OPTION_ANALYSIS])) {
            $options[self::SCAN_OPTION_ANALYSIS] = new $options[self::SCAN_OPTION_ANALYSIS];
        }
```

**Comment by AlexandreBellas** [comment]
I just figured out another fancier way to solve it.
Just add in your `boot` method of `AppServiceProvider`

```php
class AppServiceProvider extends ServiceProvider
{
    // ...

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        // ...

        $analyser_class = config('l5-swagger.defaults.scanOptions.analyser');
        config(['l5-swagger.defaults.scanOptions.analyser' => new $analyser_class]);
    }

    // ...
}
```
