### ISSUE TITLE
Documentation showing how to use the comments?

### ISSUE THREAD

**Issue by Messhias** [DarkaOnLine/L5-Swagger#418]
It's quite been hard to find out content on the web how this package works and even the other packages.

It's possible one we have documentation with _**all possibles**_ examples of annotations to generate documentation?

Another thing is @DarkaOnLine when we'll have more maintainer in packages?  We see a lot of issues being raised, some PR's without conclusion for over a year too.

**Comment by DarkaOnLine** [comment]
How about at first trying to answer those raised issues/questions, putting answers to the wiki so we could collect answers to common questions?

**Comment by Messhias** [comment]
I'l try to do that when I have some time. Thanks.
