### ISSUE TITLE
Support middlware for routes

### ISSUE THREAD

**Issue by tantam** [DarkaOnLine/L5-Swagger#42]
Currently I don't want to public the api/document so I want to add a middleware to that API.
I can redefine another route and add middleware, but it will be great if L5-Swagger supports it naturally.
Do you have any plan on this one, or may be I can help you add this feature.

This is what I think it will be:
* Add one more configuration value call "middleware"
* In routes file, we will add middleware from configuration file.

How do you think ?

Thanks and sorry for any typos.

**Comment by DarkaOnLine** [comment]
Hi, @tantam 

Great idea! It would be awesome if you make a pull request for this.

Maby by default we could use Laravels BasicAuth middleware or provide our own ?

**Comment by tantam** [comment]
We should put "web" middleware only, it is the default from Laravel, if developers want to add more they can do by changing configuration file.

Anyway, I will do it and make a PR.

Thanks

**Comment by DarkaOnLine** [comment]
@tantam thanks for your contribution !

Implemented in #43
