### ISSUE TITLE
Limit to debug mode only

### ISSUE THREAD

**Issue by fahamjv** [DarkaOnLine/L5-Swagger#421]
- L5-Swagger Version: 5.8.5
- PHP Version (`php -v`):7.3.31
- OS:Ubuntu

### Description:
I tried to enable this packge only when debug mode is on by adding:

```
if (config('app.debug')) {
            $this->app->register(\L5Swagger\L5SwaggerServiceProvider::class);
}
```

in register function in AppServiceProvider.php. but it won't work and `/api/documentation` will be available publicly.

### Steps To Reproduce:

1. Change `APP_DEBUG` to true
2. Put the condition in register function in AppServiceProvider.php
3. run `php artisan optimize`
4. `/api/documentation` is still available publicly.

**Comment by DarkaOnLine** [comment]
You can use middleware’s to restrict access to endpoints
