### ISSUE TITLE
Customizing the UI

### ISSUE THREAD

**Issue by faudaux** [DarkaOnLine/L5-Swagger#422]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):
- OS:
I've been looking for ways to customize the UI without success, I would be content with changing the logo and some colors, but potentially changing the style of the page would be great. Is there a way to do that?

**Comment by DarkaOnLine** [comment]
Yes you can publish `index.blade.php` by running `php artisan l5-swagger:publish-views` and modify it to your needs
