### ISSUE TITLE
Reference external file

### ISSUE THREAD

**Issue by renatocosta** [DarkaOnLine/L5-Swagger#424]
Hello,

Reference file does not work at all as known as below.

Error:

![Screenshot from 2021-12-17 20-22-43](https://user-images.githubusercontent.com/638176/146618821-89855f04-4cbc-4727-aa5d-888a88966598.png)

Settings:
![Screenshot from 2021-12-17 20-23-05](https://user-images.githubusercontent.com/638176/146618851-4684f06e-9364-4292-82dd-1cf41f6c77f1.png)

api-docs.yaml
![Screenshot from 2021-12-17 20-28-31](https://user-images.githubusercontent.com/638176/146619073-8452985d-b660-4692-baf4-5f6955f862ef.png)

endpoint.yaml
![Screenshot from 2021-12-17 20-29-09](https://user-images.githubusercontent.com/638176/146619128-48972bb8-6adb-4389-9a4c-324ea3c6fee5.png)

Do you know if I am missing something?

**Comment by DarkaOnLine** [comment]
Have you solved this? I think `./endpoint.yaml` will not work as this system path and not the URL path. Something like `endpoint.yaml`  or `/endpoint.yaml` should work
