### ISSUE TITLE
Issue with optional parameter

### ISSUE THREAD

**Issue by yungts97** [DarkaOnLine/L5-Swagger#425]
- L5-Swagger Version: 8.0.7
- PHP Version: 8.0.12
- OS: Ubuntu 

I would like to add an optional parameter to my GET API and I'm able to disable the required field, but when I passed an empty value to {item_per_page}, the URL is didn't remove {item_per_page} from the URL.
![image](https://user-images.githubusercontent.com/48639619/147116952-c6db58cf-7cd7-4ba4-bae9-3e73807612cf.png)
This is my CURL and request URL.
![image](https://user-images.githubusercontent.com/48639619/147117019-2d824e97-235a-4036-bfee-acc3e676409e.png)
This is my Swagger Annotation
```
     /**
     * @OA\Get(
     *  path="/api/product-categories/{id}/products/{item_per_page}",
     *  summary="Retrieve products based on product category",
     *  description="Retrieve products",
     *  tags={"Product Categories [Public]"},
     *  @OA\Parameter(
     *      name="id",
     *      description="Product Category ID",
     *      example=1,
     *      required=true,
     *      in="path",
     *      @OA\Schema(
     *          type="integer"
     *      )
     *  ),
     *  @OA\Parameter(
     *      name="item_per_page",
     *      description="Number of item per page",
     *      example=15,
     *      in="path",
     *           @OA\Schema(
     *          type="integer"
     *      )
     *  ),
     *  @OA\Response(
     *      response=200,
     *      description="Success response",
     *      @OA\JsonContent(
     *          @OA\Property(
     *              property="status",
     *              type="string",
     *              example="success"
     *          ),
     *          @OA\Property(
     *              property="message",
     *              type="string",
     *              example=""
     *          ),
     *          @OA\Property(
     *              property="data",
     *              type="string",
     *              ref="#/components/schemas/ProductCategory"
     *          )
     *      )
     *  ),
     * )
     */
```
Do you guys have to meet this problem before? I need some helps with it.

**Comment by DerManoMann** [comment]
Wouldn't that be a question for [swagger-ui](https://github.com/swagger-api/swagger-ui)?

**Comment by shahdix** [comment]
hi
you should use location in query for your optional parameters.

 *  @OA\Parameter(
     *      name="id",
     *      description="Product Category ID",
     *      example=1,
     *      required=true,
     *      in="path",    =>>>>>>>>>>>>>>>>>>>>>> in="query"
     *      @OA\Schema(
     *          type="integer"
     *      )
     *  ),
