### ISSUE TITLE
Doesn't work with Nginx cache-control

### ISSUE THREAD

**Issue by guluguru** [DarkaOnLine/L5-Swagger#427]
- L5-Swagger Version: 8.0.9
- PHP Version :7.3.27
- OS: Centos 6.9

### Description:
After adding this to nginx conf, it's won't work, remove this, it work again:
```nginx
       location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|data|js|css|html|htm)$
       {
               expires      365d;
       }
```

### Steps To Reproduce:
It's simple, just see description

**Comment by noyidoit** [comment]
It seems an Swagger-ui's bug

**Comment by noyidoit** [comment]
Sorry I checked it again, maybe you should have a look for this

**Comment by liaoshengping** [comment]
i am seem also ! Is there any way to fix it？

**Comment by noyidoit** [comment]
> i am seem also ! Is there any way to fix it？

As far as I known, for workaround, remove `expires` in nginx's conf
