### ISSUE TITLE
Adding Stringfied Json as example

### ISSUE THREAD

**Issue by mshukurlu** [DarkaOnLine/L5-Swagger#430]
- L5-Swagger Version: #.#.# arkaonline/l5-swagger               8.0.9
- PHP Version PHP 7.4.13:
- OS:

### Description:
Hi friends,

I am creating an API with multiple/form-data content type,

There I have added "stringfied json" object as string,

Everything working good when I test it on postman,

But I want to add an example in my swagger documentation there I can not set JSON as example,
 
### Steps To Reproduce:
Creating json object

  /**
    *
     *
     * @OA\Property (
     *     type="object",
     *     @OA\Property (
     *      type="array",
     *        @OA\Items(
     *      @OA\Property (
     *          property="name",
     *          example="test"
     * )
     * )
     * )

     * )
     *)

     */

Gives me : 

{
  "driver_lisences": [
    {
      "name": "test"
    },
{"name":"test 2"}
  ]
}

I need just object example like this : 
 [
    {
      "name": "test"
    },
{"name":"test 2"}
  ]

**Comment by DarkaOnLine** [comment]
I think this is what you are looking for: https://github.com/zircote/swagger-php/blob/master/Examples/example-object/example-object.php#L63

If not please dig more into swagger-php examples
