### ISSUE TITLE
Update zircote/php-swagger to version 4.*

### ISSUE THREAD

**Issue by shortcodes** [DarkaOnLine/L5-Swagger#432]
Is it possible to inlcude newest version of `zircote/php-swagger` to this package?

Regards

**Comment by DarkaOnLine** [comment]
Yes, I have this in my plans, but you are welcome to create a PR for this.

Also, you can require this version in your `composer.json`

**Comment by caugner** [comment]
@DarkaOnLine L5-Swagger's `composer.json` requires `3.*`, so unfortunately it does not seem possible to simply require that version in a project's `composer.json`, but I will propose a PR to fix that.
