### ISSUE TITLE
Simple upload and download csv file examples

### ISSUE THREAD

**Issue by erickneverson** [DarkaOnLine/L5-Swagger#433]
- L5-Swagger Version: 8.0.6 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.4.3
- OS: Ubuntu 20.04

### Description:
Looking for simple examples to upload a single csv file and download a single csv file.

### Steps To Reproduce:
Tried looking at official swagger docs and converting the yaml there to json but no luck.

```
/**
     * @OA\Get(
     *      path="/download/{id}/{name}",
     *      operationId="getCSVFile",
     *      tags={"Download"},
     *      summary="Download csv for job and name specified",
     *      description="Returns csv file. name = original|success|errors",
     *      produces=("application/csv"),
     *      @OA\Response(
     *          response=200,
     *          description="successful operation",
     *          @OA\Schema(
     *              type="file"
     *          )
     *       ),
     *      security={
     *         {"BearerToken": {}}
     *      },
     * )
     */
```

Sorry if this is the wrong area for such questions.

**Comment by DarkaOnLine** [comment]
Yeah, you should try finding the answer for this or raising an issue in [swagger-php](https://github.com/zircote/swagger-php) repo, as this package is responsible for parsing annotations
