### ISSUE TITLE
Reuse OA annotations from parent controller in child one?

### ISSUE THREAD

**Issue by kolinko-ant** [DarkaOnLine/L5-Swagger#434]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`) 
darkaonline/l5-swagger                8.0.6               OpenApi or Swagger integration to Laravel
- PHP Version (`php -v`):
PHP 7.4.25 
- OS:
Ubuntu

### Description:
Hey guys. Thanks for such cool product, it really helps us a lot! I want to ask a question about how we can work with documentation when you already have multiple API versions. In our setup we have 2 folders API/V1/Controllers and API/V2/Controllers. Let's say we have V2UserController that extends V1UserController. In V1UserController for each method we have api annotations 
/**
     * @OA\Post(
....

V2UserController (because it extends V1) has the same logic so I don't want to override any methods there. I just want to keep V2 controller empty, but at the same time I want to see those methods also in V2 documentation. Apparently because V2 controller empty, there is no such methods in v2 documentation. Is there way they can appear there because of class extension? Are there any ways?

**Comment by DarkaOnLine** [comment]
Have you checked [refs](https://github.com/zircote/swagger-php/tree/master/Examples/using-refs)? Maybe this can work

**Comment by DerManoMann** [comment]
This might be more a question for [zircote/swagger-php](https://github.com/zircote/swagger-php) which is used under the hood.

However, class hierachies are currently only supported for `@OA\Schema` (models).
