### ISSUE TITLE
Some Requests are not shown after upgrading from 8.0.1 -> 8.0.2 or 8.0.3

### ISSUE THREAD

**Issue by hadjistasi** [DarkaOnLine/L5-Swagger#448]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): PHP 7.4.13 (cli) (built: Nov 30 2020 22:47:16) ( NTS )
- OS: OS X

### Description:

Assume that I move the definition (bellow) from App\Http\Controllers\MyController to App\Http\Controllers\MyNewController it does not show the request in the documentation. The weird part that drives me crazy is that moving (not copying) the bellow definition to some controllers it shows it in the documentation, in some other controllers it does not. 
Namespaces etc all checked. No issues with those. 

From the 50 requests that were used to show in the documentation (using 8.0.1), after updating (8.0.2) i can only see 4 of them. I currently downgraded to 8.0.1 so it works. 

/**
     *
     * @OA\Post(
     *    path="/api/v1/login",
     *    summary="Auth Login",
     *    description="Login a User",
     *    operationId="authLogin",
     *    tags={"Auth"},
     *    @OA\RequestBody(
     *       required=true,
     *       description="Pass user information",
     *       @OA\JsonContent(
     *          required={"email"},
     *          @OA\Property(property="email", type="string", example="foo@foo.com"),
     *          @OA\Property(property="password", type="string", example="test4321"),
     *       ),
     *    ),
     *    @OA\Response(
     *       response=401,
     *       description="Wrong credentials response",
     *       @OA\JsonContent(
     *          @OA\Property(property="status", type="string", example="nok"),
     *          @OA\Property(property="message", type="string", example="Unauthenticated")
     *       )
     *    )
     * )
     *
     */

### Steps To Reproduce:

After upgrading from 8.0.1 -> 8.0.2 
OR 
from 8.0.1. -> 8.0.3

**Comment by DarkaOnLine** [comment]
I think this is related to `swagger-php:4` :

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/1171698/154239424-5d36bcdc-4e08-4277-b722-eaff086665a5.png">


https://github.com/zircote/swagger-php/blob/master/docs/guide/migrating-to-v4.md
