### ISSUE TITLE
Problem to update laravel 8 to 9

### ISSUE THREAD

**Issue by Messhias** [DarkaOnLine/L5-Swagger#449]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 8.1
- OS: OSX

### Description:
If we try to upgrade laravel/framework to ^9.0 we having issues

### Steps To Reproduce:

Go to your composer.json and put laravel/framework to ^9.0

You get this:

```
 Problem 1
    - Conclusion: don't install darkaonline/l5-swagger 8.3.0 (conflict analysis result)
    - darkaonline/l5-swagger[8.0.0, ..., 8.0.2] require php ^7.2 -> your php version (8.1.2) does not satisfy that requirement.
    - darkaonline/l5-swagger[8.0.3, ..., 8.0.4] require laravel/framework ^8.0 || ^7.0 -> found laravel/framework[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).
    - darkaonline/l5-swagger[8.0.5, ..., 8.1.0] require zircote/swagger-php 3.* -> found zircote/swagger-php[3.0.0, ..., 3.x-dev] but it conflicts with your root composer.json require (^4.2).
    - Root composer.json requires darkaonline/l5-swagger ^8.0 -> satisfiable by darkaonline/l5-swagger[8.0.0, ..., 8.3.0].
```

**Comment by DarkaOnLine** [comment]
Can you please provide your `composer.json` file?

**Comment by Ferikl** [comment]
just install it for L9, but now I have old issue with:
```
 ErrorException 

  Required @OA\Info() not found

```

**Comment by Messhias** [comment]
> Can you please provide your `composer.json` file?

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "ext-json": "*",
        "ext-pdo": "*",
        "aws/aws-sdk-php-laravel": "~3.0",
        "darkaonline/l5-swagger": "^8.0",
        "doctrine/dbal": "^3.1",
        "facade/ignition": "^2.3.6",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "goetas-webservices/xsd-reader": "^0.3.6",
        "guzzlehttp/guzzle": "^7.0.1",
        "illuminate/console": "^8.42",
        "intervention/image": "^2.5",
        "laravel/framework": "^8.54",
        "laravel/telescope": "^4.7",
        "laravel/tinker": "^2.5",
        "league/flysystem-aws-s3-v3": "^1.0",
        "maatwebsite/excel": "^3.1",
        "monarobase/country-list": "^3.2",
        "owen-it/laravel-auditing": "^12.0",
        "php-open-source-saver/jwt-auth": "^1",
        "predis/predis": "^1.1",
        "pusher/pusher-php-server": "^7.0",
        "s-ichikawa/laravel-sendgrid-driver": "^3.0",
        "scotteh/php-goose": "^1.1",
        "thedoctor0/laravel-mailjet-driver": "^1.0",
        "twilio/sdk": "^6.34",
        "vlucas/phpdotenv": "^5.2",
        "voku/portable-utf8": "^6.0",
        "voku/simple_html_dom": "^4.7",
        "zircote/swagger-php": "^4.2"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.9",
        "fakerphp/faker": "^1.13",
        "kitloong/laravel-migrations-generator": "^5.0",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^5.3",
        "phpunit/phpunit": "^9.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeds"
        },
        "classmap": [
            "database/seeds"
        ],
        "files": [
            "app/helpers.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

```

**Comment by DarkaOnLine** [comment]
> just install it for L9, but now I have old issue with:
> 
> ```
>  ErrorException 
> 
>   Required @OA\Info() not found
> ```
> 
> PS I have my swagger files separated from controllers

@Ferikl can you check this please: https://github.com/DarkaOnLine/L5-Swagger/issues/443

**Comment by DarkaOnLine** [comment]
@Messhias your composer shows that you are using Laravel 8, can you show the composer where you tried to update to L9?

**Comment by hosseinko** [comment]
I just upgraded to Laravel 9 and I am facing the exact same problem, here is my composer.json file

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "darkaonline/l5-swagger": "^8.3",
        "doctrine/dbal": "^3.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^9.0",
        "laravel/sanctum": "^2.11",
        "laravel/tinker": "^2.5"
    },
    "require-dev": {
        "spatie/laravel-ignition": "^1.0",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by Messhias** [comment]
> I just upgraded to Laravel 9 and I am facing the exact same problem, here is my composer.json file
> 
> ```
> {
>     "name": "laravel/laravel",
>     "type": "project",
>     "description": "The Laravel Framework.",
>     "keywords": ["framework", "laravel"],
>     "license": "MIT",
>     "require": {
>         "php": "^8.1",
>         "darkaonline/l5-swagger": "^8.3",
>         "doctrine/dbal": "^3.2",
>         "fruitcake/laravel-cors": "^2.0",
>         "guzzlehttp/guzzle": "^7.0.1",
>         "laravel/framework": "^9.0",
>         "laravel/sanctum": "^2.11",
>         "laravel/tinker": "^2.5"
>     },
>     "require-dev": {
>         "spatie/laravel-ignition": "^1.0",
>         "fakerphp/faker": "^1.9.1",
>         "laravel/sail": "^1.0.1",
>         "mockery/mockery": "^1.4.4",
>         "nunomaduro/collision": "^6.1",
>         "phpunit/phpunit": "^9.5.10"
>     },
>     "autoload": {
>         "psr-4": {
>             "App\\": "app/",
>             "Database\\Factories\\": "database/factories/",
>             "Database\\Seeders\\": "database/seeders/"
>         }
>     },
>     "autoload-dev": {
>         "psr-4": {
>             "Tests\\": "tests/"
>         }
>     },
>     "scripts": {
>         "post-autoload-dump": [
>             "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
>             "@php artisan package:discover --ansi"
>         ],
>         "post-update-cmd": [
>             "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
>         ],
>         "post-root-package-install": [
>             "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
>         ],
>         "post-create-project-cmd": [
>             "@php artisan key:generate --ansi"
>         ]
>     },
>     "extra": {
>         "laravel": {
>             "dont-discover": []
>         }
>     },
>     "config": {
>         "optimize-autoloader": true,
>         "preferred-install": "dist",
>         "sort-packages": true
>     },
>     "minimum-stability": "dev",
>     "prefer-stable": true
> }
> ```

@DarkaOnLine you can use his composer as example.

**Comment by shortcodes** [comment]
I also face this issue

``` 
ErrorException 

Required @OA\Info() not found
```

**Comment by DerManoMann** [comment]
Sounds like the same issue as #443. If you are using swagger-php v4 then your annotations must be associated with a class/interface/trait/enum or method.

swagger-php v4 uses reflection and **will not find stand-alone annotations any more**.

The simplest way around is either to stick with v3 or add dummy classes to your annotations.

**Comment by louis222220** [comment]
I face a similar problem like yours. 
The package version of symfony/yaml in my new project was conflicted.

And I fixed the problem with the following command to install L5-Swagger:
```bash
composer require darkaonline/l5-swagger --with-all-dependencies
```

I hope this will help.
