### ISSUE TITLE
I don't use yaml in Laravel 5.1 

### ISSUE THREAD

**Issue by rainying** [DarkaOnLine/L5-Swagger#45]
I use the YAML .Happen "Can't read from server. It may not have the appropriate access-control-origin settings."

![image](https://cloud.githubusercontent.com/assets/8848198/21345775/6ef5a970-c6dc-11e6-929d-26ac40561af5.png)

I would like to ask how the changes?

**Comment by DarkaOnLine** [comment]
This is related to the SwaggerUI, please see this: https://github.com/swagger-api/swagger-ui/issues/146
