### ISSUE TITLE
Annotations included in the section "use" are not worked

### ISSUE THREAD

**Issue by Vasiliy-Makogon** [DarkaOnLine/L5-Swagger#450]
- L5-Swagger Version: 8.2.0
- PHP Version (`php -v`): 8.0.8 
- OS: ubuntu 18.04

### Description:

Hello. After updating the swagger from version 8.0.9 to version 8.2.0, the documentation stopped generating. Here is the error:

```
[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got '(' at position 4752.
```

The problem is that the annotations declared in use, as 

```
use OpenApi\Annotations\Info;
use OpenApi\Annotations\SecurityScheme;
use OpenApi\Annotations\Schema;
use OpenApi\Annotations\Property;
use OpenApi\Annotations\Items;
use OpenApi\Annotations\RequestBody;
use OpenApi\Annotations\Post;
use OpenApi\Annotations\Get;
use OpenApi\Annotations\JsonContent;

/**
     * @Post(
     *     path="/api/v1/auth/login",
     *     tags={"Авторизация"},
     *     summary="Аутентификация и получение токена",
     *     @RequestBody(
     *         required=true,
     *         @JsonContent()
     *     ),
     *  ....
```

are simply not accepted!!! Works only with OA alias: @OA\Post, OA\RequestBody, OA\JsonContent
Why??

**Comment by DarkaOnLine** [comment]
This question should go to [Swagger-php](https://github.com/zircote/swagger-php) but I think this is by design
