### ISSUE TITLE
Can no longer generate documentation - laravel 8

### ISSUE THREAD

**Issue by haidyelnahass** [DarkaOnLine/L5-Swagger#452]
- L5-Swagger Version: ^8.3
- PHP Version : 8 
- OS: Windows 10

### Description:
For some reason, i can no longer generate documentation anymore, some random errors that don't make any sense keep popping up and i do not know what the reason is or how to fix it! 

### Steps To Reproduce:
-- php artisan l5-swagger:generate
error1:
![image](https://user-images.githubusercontent.com/74070220/155853138-bfb68725-c86b-44fd-92ad-bb821fc7a0f1.png)
error 2 that appears states that required OA\Info() not found, knowing that it is added in the base controller and the documentation was generated a lot of times before with no issues at all. 
And the unknown \changepasswordrequest he is stating was already there before too. I do not know what to do.

**Comment by marionfromfrance** [comment]
Hi,
did you try to git bisect from a working past commit?

**Comment by DerManoMann** [comment]
This is related to changes in the swagger-php library used: https://zircote.github.io/swagger-php/guide/faq

**Comment by DarkaOnLine** [comment]
Also related to this #443
