### ISSUE TITLE
Response model not found in swagger 3.0

### ISSUE THREAD

**Issue by bhattaxay** [DarkaOnLine/L5-Swagger#454]
Hello i am trying to create a response model of Api using swagger 3.0 Open api. But whenever i add below code

```
/**
    * @OA\Post(
    *      path="/authentication/signin",
    *      tags={"Authentication"},
    *      summary="Login User",
    *      operationId="signIn",
    *      @OA\RequestBody(
    *         @OA\MediaType(
    *             mediaType="application/x-www-form-urlencoded",
    *             @OA\Schema(
    *                 required={"isd_code", "phonenumber", "user_type"},
    *                 @OA\Property(property="isd_code", type="string"),
    *                 @OA\Property(property="phonenumber", type="string"),
    *                 @OA\Property(property="user_type", type="integer", format="int32", default="1",enum={1,2},description="1 = User Login, 3 = Driver Login")
    *             )
    *         )
    *      ),
    *      @OA\Response(
    *         response=200,
    *         description="success",
    *         @OA\JsonContent(ref="#/components/schemas/UserResponse"),
    *      ),
    *      @OA\Response(
    *         response=400,
    *         description="Error",
    *         @OA\JsonContent(ref="#/components/schemas/CommonFields")
    *      )
    * )

 */
```
It throws below error:
"$ref "#/components/schemas/UserResponse" not found for @OA\JsonContent() 

I have already mentioned above UserResponse model in my Laravel resource file still it's not able to scan that response model.

Below is the code for UserResponse model:

  ```
   /**
       * @OA\Schema(
       *   schema="UserResponse",
       *   type="object",
       *   @OA\Property(
       *        property="responseCode", 
       *        type="integer",
       *        format="int32"
       *   ),
       *   @OA\Property(
       *        property="responseMessage", 
       *        type="string"
       *      ),
       *   @OA\Property(
       *       property="responseData", 
       *       type="object",
       *       ref="#/components/schemas/UserResponseFields"
       *     )
       * )
       */
```
I would like to know why swagger is not able to scan UserResponse model.
If i comment the line below line, than it is working fine 
``` 
*         @OA\JsonContent(ref="#/components/schemas/UserResponse"), 
``` 

Laravel Version : 7.29
Darkaonline verion:  "darkaonline/l5-swagger": "8.0.7",

**Comment by DerManoMann** [comment]
Are you using swagger-php v4.2.x? If so this might be related to not having a class associated with your `UserResponse` annotation? 
The FAQ has more on these issues: https://zircote.github.io/swagger-php/guide/faq

**Comment by bhattaxay** [comment]
@DerManoMann I am using swagger-php v3.0. I resolved above issue by downgrading darkaonline/l5-swagger to 8.0.7. Now i am facing the issue of 
`Undefined variable $useAbsolutePath (View: D:\\xampp\\htdocs\\xoolu\\resources\\views\\vendor\\l5-swagger\\index.blade.php`

Not getting exactely what's wrong with it?

**Comment by DerManoMann** [comment]
Oh, that is outside of my expertise.

Could be the temple needs to be downgraded too?
Definitely a bundle issue, unrelated to swagger-php.

**Comment by bhattaxay** [comment]
@DerManoMann Finally i found the solution for UI as well. Due to old l5-swagger folder in resources/view/vendor path. It was throwing this error ==> `Undefined variable $useAbsolutePath (View: D:\\xampp\\htdocs\\xoolu\\resources\\views\\vendor\\l5-swagger\\index.blade.php`

I have delete the old l5-swagger folder from this path ==> resources/view/vendor  and again publish the l5-swagger and it's resolve my issue.
