### ISSUE TITLE
Error messages often do NOT make sense and are NOT helping.

### ISSUE THREAD

**Issue by khessels** [DarkaOnLine/L5-Swagger#455]
- L5-Swagger Version: all versions
- PHP Version 7, 8
- OS: Any

### Description:
Error returned to the user does not make any sense. 
for example:  [Semantical Error] Couldn't find constant c.

  at vendor/zircote/swagger-php/src/Logger.php:40
     36▕         $this->log = function ($entry, $type) {
     37▕             if ($entry instanceof Exception) {
     38▕                 $entry = $entry->getMessage();
     39▕             }
  ➜  40▕             trigger_error($entry, $type);
     41▕         };
     42▕     }
     43▕ 
     44▕     public static function getInstance(): Logger

      +29 vendor frames 
  30  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

How in the world does this help me or anyone narrow down a problem in documenting (if that is even the cause of the problem)
Usefull info would be the model or controller that generates the error, or a piece of the document it is parsing which generates the error...  this just well.... a bit on the easy side ?

**Comment by DarkaOnLine** [comment]
If you look closer you'll see that this error comes not from this package but from `vendor/zircote/swagger-php`so you should raise your complaints and unsatisfactory to swagger-php maintainers, but better would not just be angry but try to figure out the issue and suggest the solutions or make a PR  how to fix it.  I doubt if anyone in the community would even read this kind of message...

**Comment by khessels** [comment]
hmm, so if someone is a bit annoyed, you call him angry... ok... whatever... a bit of a presumptions statement
