### ISSUE TITLE
'Documentation config not found' on generating

### ISSUE THREAD

**Issue by rcompier** [DarkaOnLine/L5-Swagger#456]
### Versions:
- L5-Swagger Version: 8.3.0
- PHP Version: 7.4.24
- Laravel Version: 8.83.4
- OS: Windows 10 21H2 Build 19044.1566

### Description:
I've already set up my swagger environment so that's working, but I wanted to change some things so I ran the command to generate the files to see if it would still work and to my surprise, it does not.

`php artisan l5-swagger:generate`

It now gives an error saying:

`Documentation config not found`

Going into the file where this error comes from, `ConfigFactory.php`, from what I could tell. It's looking with the laravel config helper for a folder called `l5-swagger` and files `default` and `documentations`.

I never had these folders/files so I'm rather confused where this came from.

### Steps To Reproduce:
Of course our configs and setups are gonna be different, but the fact that the current swagger pages work, I don't not what to tell you.

[Config file](https://pastebin.com/dag5ZkrE)

![image](https://user-images.githubusercontent.com/21107109/157874200-31e91063-1075-4c39-a5b2-5d2a4cdd5fb8.png)
Terminal error

![image](https://user-images.githubusercontent.com/21107109/157874310-a1a54ea2-a381-49c7-9ecf-ba87ea853a86.png)
Config searching for files

### Extra info:
I have an old project where everything worked fine the last time I commited and tested, however this now also has the same problem.

**Comment by DarkaOnLine** [comment]
Looks like you always used the default config. And it also seems like you now upgraded from older version with one API support to the newest version. You can publish the config to your project or just copy it to `config/l5-swagger.php` and do all required adjustments and hopefully, everything should be good

**Comment by rcompier** [comment]
I have from the start used "^8.1".  and never updated it, but it still doesn't work. so I guess I'll just have to convert the config to the new one

**Comment by jamer0077** [comment]
i'm facing the same problem but my both versions laravel and php are fine. but still showing the same error

**Comment by jamer0077** [comment]
Hello Dear Sir,

**Comment by zeeshantanveer** [comment]
I am also facing the same problem.

**Comment by malisoft** [comment]
in the path `config/l5-swagger.php` in the line 4, maybe you have the next:
`<?php

return [
    'default' => 'defaults',
    'documentations' => [
    ....`
so the error `Documentation config not found` is because the value defaults in default can't be found in documentation array, change default by a documentation key value and will works but only that document only

**Comment by ekodrive** [comment]
don't run command php artisan l5-swagger:generate
run
php artisan l5:generate

**Comment by fradiegege** [comment]
the solution is the next change:  'default' => 'default',

file config: l5-swagger
