### ISSUE TITLE
Skipping unknown \Controller

### ISSUE THREAD

**Issue by tahasethwala** [DarkaOnLine/L5-Swagger#457]
- L5-Swagger Version: 8.3.0 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.4.13
- OS: Windows 10

### Description: After installing as per this post: https://blog.quickadminpanel.com/laravel-api-documentation-with-openapiswagger/ I created a Controller name Controller.php at path: app/Http/Controller/Api/Controller.php. And this file contains as below

<```
?php

class Controller
{
    /**
     * @OA\Info(
     *      version="1.0.0",
     *      title="Laravel OpenApi Demo Documentation",
     *      description="L5 Swagger OpenApi description",
     *      @OA\Contact(
     *          email="admin@admin.com"
     *      ),
     *      @OA\License(
     *          name="Apache 2.0",
     *          url="http://www.apache.org/licenses/LICENSE-2.0.html"
     *      )
     * )

     *
     * @OA\Tag(
     *     name="Projects",
     *     description="API Endpoints of Projects"
     * )
    */
}
```



### Steps To Reproduce:

After that I did php artisan l5-swagger:generate

![image](https://user-images.githubusercontent.com/85347409/158325876-edb1d73d-b71d-4b77-b673-820604560cc0.png)

-->

**Comment by DarkaOnLine** [comment]
Your annotations should go before `class Controller`:

```php
<?php

/**
     * @OA\Info(
     *      version="1.0.0",
     *      title="Laravel OpenApi Demo Documentation",
     *      description="L5 Swagger OpenApi description",
     *      @OA\Contact(
     *          email="admin@admin.com"
     *      ),
     *      @OA\License(
     *          name="Apache 2.0",
     *          url="http://www.apache.org/licenses/LICENSE-2.0.html"
     *      )
     * )

     *
     * @OA\Tag(
     *     name="Projects",
     *     description="API Endpoints of Projects"
     * )
    */
class Controller
{
    
}
```

**Comment by tahasethwala** [comment]
I did as mentioned by you

File: app/Http/Controllers/Api/Controller.php

<?php

/**
     * @OA\Info(
     *      version="1.0.0",
     *      title="Laravel OpenApi Demo Documentation",
     *      description="L5 Swagger OpenApi description",
     *      @OA\Contact(
     *          email="admin@admin.com"
     *      ),
     *      @OA\License(
     *          name="Apache 2.0",
     *          url="http://www.apache.org/licenses/LICENSE-2.0.html"
     *      )
     * )

     *
     * @OA\Tag(
     *     name="Projects",
     *     description="API Endpoints of Projects"
     * )
    */

class Controller
{

}

But getting same error.

**Comment by DarkaOnLine** [comment]
Not sure if it's just copy/paste, but can you try to remove the blank line between class and annotations? Not sure if this could help though

**Comment by DerManoMann** [comment]
The reason is that `swagger-php` cannot load the class `\Controller`.

The library relies on autoloading in order to use PHP reflections. Unless you have custom autoload rules in your `composer.json` I would think the file needs to be in the proper namespace. Have you actually tried the endpoint itself? I'd be surprised if Laravel can find it...

```
namespace App/Http/Controller/Api;
```

**Comment by tahasethwala** [comment]
Yes I tried this too:
`<?php

namespace App\Http\Controller\Api;

 /**
 * @OA\Info(
 *      version="1.0.0",
 *      title="Laravel OpenApi Demo Documentation",
 *      description="L5 Swagger OpenApi description",
 *      @OA\Contact(
 *          email="admin@admin.com"
 *      ),
 *      @OA\License(
 *          name="Apache 2.0",
 *          url="http://www.apache.org/licenses/LICENSE-2.0.html"
 *      )
 * )
 *
 * @OA\Server(
 *      url=L5_SWAGGER_CONST_HOST,
 *      description="Demo API Server"
 * )
 *
 * @OA\Tag(
 *     name="Projects",
 *     description="API Endpoints of Projects"
 * )
 */
class Controller
{

}
`

**Comment by DerManoMann** [comment]
It definitel comes down to autoloading. Does your controller implement an actual endpoint that works (via Laravel)?

**Comment by KellsWorks** [comment]
After adding in your base controller (Or any controller without Request calls):

/**
 * @OA\Info(
 *      version="1.0.0",
 *      title="Laravel OpenApi Demo Documentation"
 * /
 
Make sure you add the proper annotations on top of every method in API Controllers. It worked for me.

For example:

/**
     * @OA\Get(
     *      path="/projects",
     *      operationId="getProjectsList",
     *      tags={"Projects"},
     *      summary="Get list of projects",
     *      description="Returns list of projects",
     *      @OA\Response(
     *          response=200,
     *          description="Successful operation",
     *          @OA\JsonContent(ref="#/components/schemas/ProjectResource")
     *       ),
     *      @OA\Response(
     *          response=401,
     *          description="Unauthenticated",
     *      ),
     *      @OA\Response(
     *          response=403,
     *          description="Forbidden"
     *      )
     *     )
     */

**Comment by A-Khranovsky** [comment]
Have got simmilar problem. I had error message "Skipping unknown \Category" Before I created classe in files: app\Virtual\Models\Category.php and app\Virtual\Resoures\CategoryResource.php. And when I wrote:
namespace App\Virtual\Models; (in Category.php) and namespace App\Virtual\Resources; (in CategoryResource.php), problem has gone
