### ISSUE TITLE
Skipping unknown \InvalidClient

### ISSUE THREAD

**Issue by NaxiD** [DarkaOnLine/L5-Swagger#461]
- L5-Swagger Version: 8.3.0 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 8.1.2
- OS: Windows

Hello, I'm developing a Laravel project that a working partner started and I'm having an issue generating a new doc for L5-Swagger. I get an error '_Skipping unknown \InvalidClient_'.

I re-installed L5-Swagger, deleted config files, used the '_vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider_"' command, deleted all comments in all files, but I always get the same message:

<img src="https://i.ibb.co/bR4GY4X/Captura.png" alt="Captura" border="0">

What can I do? Thank you.

**Comment by DerManoMann** [comment]
Have you looked at #457?

**Comment by NaxiD** [comment]
Yes, I've checked it and I still have the same issue.

**Comment by DarkaOnLine** [comment]
Can you check this:https://github.com/zircote/swagger-php/issues/1136 and this comment: https://github.com/zircote/swagger-php/issues/1136#issuecomment-1048238037
