### ISSUE TITLE
Symfony YAML v6 Support

### ISSUE THREAD

**Issue by vaawebdev** [DarkaOnLine/L5-Swagger#465]
- L5-Swagger Version: 8.3.1
- PHP Version: 8.1.4
- OS: Linux b5cc9c2f4250 5.10.104-linuxkit

### Description:

Add Support to symfony/yaml (^6)

### Steps To Reproduce:

Run `composer outdated` - see `symfony/yaml v5.4.3 v6.0.3 Loads and dumps YAML files`
Run `composer why-not symfony/yaml 6.0.3` - see `darkaonline/l5-swagger  8.3.1  requires  symfony/yaml (^5.0)`

**Comment by pclineup** [comment]
+1 Same problem
