### ISSUE TITLE
Component/Schema not found

### ISSUE THREAD

**Issue by kevinpallado** [DarkaOnLine/L5-Swagger#466]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`) : 8.3.1
- PHP Version (`php -v`): 8.0.17
- OS: Ubuntu 20.04.3 LTS

### Description:

As I am following the steps how it is done [here](https://blog.quickadminpanel.com/laravel-api-documentation-with-openapiswagger/) I got this error says 

![image](https://user-images.githubusercontent.com/31546211/164182403-f717cfc9-fe62-4616-8139-6f70f26b8628.png)

### Steps To Reproduce:

Add this to your controller

```
/**
  * @OA\Get(
  *     path="/accounts",
  *     tags={"Account"},
  *     summary="Get list of accounts",
  *     @OA\Response(
  *          response=200,
  *          description="Successful operation",
  *          @OA\JsonContent(ref="#/components/schemas/AccountsResource")
  *     )
  * )
  */
```
  
  Run `php artisan l5-swagger:generate`

**Comment by DerManoMann** [comment]
Looks like the schema for `AccountsResource` is not found.

So either you do not have annotated that resource at all or for some reason the annotations for it is in a place where PHP reflection cannot find it. Typically this happens for annotations that are not associated with a class/method or similar.
The swagger-php [FAQ](https://zircote.github.io/swagger-php/guide/faq) has some more details.

**Comment by kevinpallado** [comment]
@DerManoMann I tried to use my own resource replacing

`@OA\JsonContent(ref="#/components/schemas/AccountsResource")` into

`@OA\JsonContent(ref="App\Http\Resources\AccountsResource")` and then I run generate all good.

But then have this error
![image](https://user-images.githubusercontent.com/31546211/164374461-f7d577a3-e95b-4e7a-8383-a59673151b67.png)


How do I reference my own json resource response?

**Comment by DerManoMann** [comment]
Using `"#/components/schemas/AccountsResource"` is the correct way. 

My guess as to why this is not working is that the `AccountsResource` annotation is not found.

One way to prove this would be to take out that reference at all from your controller, so you get a working spec. Then you can inspect the generated JSON/YAML and I would expect that `AccountsResource` is missing in there.

If that is the case then it would be good if we could see the annotation for that and also if that annotation has a class or other structural element associated. What I mean with that is something like:

```php
/**
 * @OA\Schema()
 */
class AccountsResource { /* .... */}
```

Without the `class AccountsResource { /* .... */}` the code will ignore the annotation and therefore it cannot be referenced.

**Comment by rickysut** [comment]
where to put #/components/schemas/AccountsResource actually when I am using Laravel??

**Comment by bhattaxay** [comment]
Hii,

@DerManoMann, @DarkaOnLine  Can you please show this with some code reference?

**Comment by DerManoMann** [comment]
All files/classes must be autoloadable and all direcories in the list of scanned directories (which should be the case using L5)


`Controller.php`
```php
<?php

namespace App\Http\Controllers;

use OpenApi\Annotations as OA;

/**
 * @OA\Get(
 *     path="/accounts",
 *     tags={"Account"},
 *     summary="Get list of accounts",
 *     @OA\Response(
 *          response=200,
 *          description="Successful operation",
 *          @OA\JsonContent(ref="#/components/schemas/AccountsResource")
 *     )
 * )
 */
class Controller {}
```

`AccountsResource.php`
```php
<?php

namespace App\Http\Resources;

use OpenApi\Annotations as OA;

/**
 * @OA\Schema()
 */
class AccountsResource {}
```

`Api.php` (this is for shared annotations, etc)
```php
<?php

namespace App;

use OpenApi\Annotations as OA;

/**
 * @OA\Info(title="Components", version="0.1")
 */
class Api {}
```

spec
```
openapi: 3.0.0
info:
  title: Components
  version: '0.1'
paths:
  /accounts:
    get:
      tags:
        - Account
      summary: 'Get list of accounts'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountsResource'
components:
  schemas:
    AccountsResource: {  }

```

**Comment by illummina** [comment]
Solved by changing:

```php
/**
*     @OA\RequestBody(
*         required=true,
*         @OA\MediaType(
*             mediaType="application/json",
*             @OA\Schema(ref="#/components/schemas/ClientCreateRequest")
*         )
*     ),
*     @OA\Response(
*         response=201,
*         description="Client created successfully",
*         @OA\Items(ref="#/components/schemas/ClientResource")
*     ),
* /
``` 

to 

```php
/**
*     @OA\RequestBody(
*         required=true,
*         @OA\JsonContent(ref="app\Http\Resources\ClientCreateRequest")
*     ),
*     @OA\Response(
*         response=201,
*         description="Client created successfully",
*         @OA\JsonContent(ref="app\Http\Resources\ClientResource")
*     ),
* /
```

**Comment by illummina** [comment]
in config/l5-swagger.php add all folders you need to annotations:

'annotations' => [
                    base_path('app/Http'),
                    base_path('app/Models'),
                ],
