### ISSUE TITLE
 Required @OA\Info() not found in Laravel 9 and want to use it outside controller

### ISSUE THREAD

**Issue by mayutheandev** [DarkaOnLine/L5-Swagger#468]
Regenerating docs default

   ErrorException 

  Required @OA\Info() not found

  at vendor/zircote/swagger-php/src/Loggers/DefaultLogger.php:31
     27▕         } else {
     28▕             $error_level = E_USER_WARNING;
     29▕         }
     30▕ 
  ➜  31▕         trigger_error($message, $error_level);
     32▕     }
     33▕ }
     34▕ 

      +23 vendor frames 
  24  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by DerManoMann** [comment]
Pretty sure this is related to https://zircote.github.io/swagger-php/guide/faq#warning-required-oa-info-not-found

Also, have a look at #443
