### ISSUE TITLE
Fetch error response status is 404 https://xxx.yyy.zzz/docs/api-docs.json

### ISSUE THREAD

**Issue by charlie-nguyen-goldenowl-zz** [DarkaOnLine/L5-Swagger#469]
- L5-Swagger Version:  8.3.0 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 8.0
- OS: ubuntu
- Laravel Codepipeline and Elasticbeanstalk
### Description:
Errors:
Fetch error
response status is 404 https://xxx.yyy.zzz/docs/api-docs.json

### Steps To Reproduce:
```
php artisan l5-swagger:generate
php artisan route:cache
```

**Comment by ceresaconsultoria** [comment]
I am receved same error

after execute php artisan l5-swagger:generate return Regenerating docs default but not generate files

in page 

Errors
Hide
 
Fetch error
Not Found http://XXXXXXXXX:8000/docs/api-docs.json

**Comment by 360hexor** [comment]
I'm getting exactly the same

**Comment by ceresaconsultoria** [comment]
Hi

The problem is memory_limit, I increased the limit and generated the documentation.

increase in php.ini memory_limit to 1G
