### ISSUE TITLE
Laravel Vapor Failed to load API definition error

### ISSUE THREAD

**Issue by DataMarq** [DarkaOnLine/L5-Swagger#473]
- L5-Swagger Version: 8.3.2
- PHP Version: 8.1.2
- OS: AWS Lamda/Laravel Vapor

### Description:
Swagger-UI html/css loads without issue but getting "Failed to load API definition" error.  Looking at network tab in my browser and the api-docs.json file is red and showing this error... "Unable to locate documentation file at: "/tmp/storage/api-docs/api-docs.json".  Everything works locally and the api-docs.json file is generated locally and in the Laravel storage folder locally.

How do we deploy this in Laravel Vapor? 

### Steps To Reproduce:

1) Added separate-vendor: true to vapor.yaml
2) modified env files to have L5_SWAGGER_UI_ASSETS_PATH=../../tmp/vendor/swagger-api/swagger-ui/dist/
3) run vapor deploy
4) https://<my-domain>/api/docs loads and shows the Swagger logo and html/css
5) get Failed to load API definition error and response status is 404 https://<my-domain>/docs/api-docs.json fetch error

**Comment by elliottpost** [comment]
FWIW I wasn't able to get this to work with Vapor since Vapor has ephemeral storage. You could probably make it work by mounting a persistent storage unit to your instance. See https://docs.vapor.build/1.0/resources/storage.html#mounting-a-persistent-file-system

**Comment by DataMarq** [comment]
Storage is set up in Vapor but the Swagger UI is looking in the tmp/ directory. Is there a way to have the api-docs.json file can be saved to the public folder and change Swagger UI to look for it there?

**Comment by elliottpost** [comment]
In the `l5-swagger.php` config file there is a section that looks like this:

```php
        'paths' => [
            /*
             * Absolute path to location where parsed annotations will be stored
            */
            'docs' => base_path('storage/api-docs'),
```

You might be able to just do an absolute path like
```php
        'paths' => [
            /*
             * Absolute path to location where parsed annotations will be stored
            */
            'docs' => "/tmp/storage/api-docs"
```

Or something. Not tested. Curious if you get it to work as we need to make it work on ours yet!

**Comment by DataMarq** [comment]
I had followed this link to get the UI files to load without issue...
https://github.com/DarkaOnLine/L5-Swagger/issues/277

Based on your suggestion of changing the l5-swagger.php file 'paths' section, I modified the docs path to be this...

`'paths' => [
            /*
             * Absolute path to location where parsed annotations will be stored
            */
            'docs' => base_path('resources/views/vendor/l5-swagger'),`

Vapor loads the Swagger file without issue now!

**Comment by sandromedina** [comment]
- L5-Swagger Version: 8.3.2
- PHP Version: 8.1.6
- Laravel 9.9.0
- OS: AWS Lamda/Laravel Vapor

Changing the l5-swagger.php docs path config was enogh for me. `'docs' => base_path('resources/views/vendor/l5-swagger')`

It was not necessary for me to add pertistent storage nor separate-vendor: true to vapor.yaml

**Comment by Gustaf-Hard** [comment]
This worked perfectly for me also. 
But I also had to set an env variable `L5_SWAGGER_USE_ABSOLUTE_PATH=false`

**Comment by mmenacer** [comment]
> This worked perfectly for me also. But I also had to set an env variable `L5_SWAGGER_USE_ABSOLUTE_PATH=false`

Hello this solution didn't work for me. 
I'm using vapor with laravel. 
L5_SWAGGER_USE_ABSOLUTE_PATH=false
'docs' => base_path('resources/views/vendor/l5-swagger')

**Comment by mmenacer** [comment]
> ```
> /tmp/storage/api-docs
> ```

I found the solution. You must do this change then generate the new Swagger and lastly deploy it
