### ISSUE TITLE
Upgraded from Laravel 8 to 9 Error

### ISSUE THREAD

**Issue by yusufalper** [DarkaOnLine/L5-Swagger#477]
- L5-Swagger Version: 8.3.2 
- PHP Version: 8.1.2
- OS: macOS

### Description: 
Upgraded from Laravel 8 to 9 and I received this message on swagger docs.

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/17886290/172331757-8d736b4c-9cc4-4a2f-886d-f148c60d67e0.png">

And if I go to "api-docs.json" file and remove -"openapi": "3.0.0"- line and then add the same line again, it works...? Is this a glitch?
Any thoughts?

**Comment by DarkaOnLine** [comment]
Have you solved this? This is very odd issue :)

**Comment by yusufalper** [comment]
Yes, but i didnt solve it solve itself without any change 😹
