### ISSUE TITLE
Is it possible for a team to generate only part of the documentation?

### ISSUE THREAD

**Issue by Vasiliy-Makogon** [DarkaOnLine/L5-Swagger#480]
Hello. Is it possible for a team to generate only a part of the documentation, according to some criteria, for example, the presence of a certain tag in annotations? For example:

```
php artisan l5-swagger:generate --tags=client
```

**Comment by DarkaOnLine** [comment]
I see you already got answer on how to achieve this with using processors. And for `--tags=client` part of this package at least I had no plans to implement this. If you are wiling to contribute please submit a PR
