### ISSUE TITLE
l5-swagger:generate not generate files

### ISSUE THREAD

**Issue by ceresaconsultoria** [DarkaOnLine/L5-Swagger#481]
- L5-Swagger Version: 8.3.2 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 8.1.7
- OS: Windows 11

### Description:
After execute command $ php artisan l5-swagger:generate return Regenerating docs default but files not generate and page show
Failed to load API definition.
 
Fetch error
Not Found http://192.168.5.170:8000/docs/api-docs.json

### Steps To Reproduce:
execute command: php artisan l5-swagger:generate

**Comment by murilolivorato** [comment]
the same to me .
it is gerating this -

```
{
    "openapi": "3.0.0",
    "info": {
        "title": "L5 OpenApi",
        "description": "L5 Swagger OpenApi description",
        "contact": {
            "email": "darius@matulionis.lt"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0.0"
    },
    "paths": {
        "/": {
            "get": {
                "description": "Home page",
                "responses": {
                    "default": {
                        "description": "Welcome page"
                    }
                }
            }
        }
    }
}

```

**Comment by ceresaconsultoria** [comment]
Hi

The problem of not generating documentation was related with memory limit configured on php.ini

I increased configuration and documentation was generate sucessful

Thanks
