### ISSUE TITLE
Authorization Code Grant with PKCE - how to?

### ISSUE THREAD

**Issue by DriverCat** [DarkaOnLine/L5-Swagger#485]
- L5-Swagger Version: 8.3.2
- PHP Version 8.1.8:
- OS: Ubuntu 20.04.4 LTS

### Description:
Does this package has support for Laravel Passport Authorization Code Grant with PKCE flow? I tried ```authorizationCode with PKCE```, but it doesnt work.

### Steps To Reproduce:

Click Authorize button, Client ID field not exists. Also tried accessCode, but seems like it is some other flow, because it doesnt generate ```code_challenge``` param needed for Authorization Code Grant with PKCE.

My current config:

```
'passport' => [ // Unique name of security
                    'type' => 'oauth2', // The type of the security scheme. Valid values are "basic", "apiKey" or "oauth2".
                    'description' => 'Laravel passport oauth2 security.',
                    'in' => 'header',
                    'scheme' => 'https',
                    'flows' => [
                        "authorizationCode with PKCE" => [
                            "authorizationUrl" => config('app.url') . '/oauth/authorize',
                            "tokenUrl" => config('app.url') . '/oauth/token',
                            "refreshUrl" => config('app.url') . '/token/refresh',
                            "scopes" => []
                        ],
                    ],
                ],
```

**Comment by DarkaOnLine** [comment]
Fixed with #486
