### ISSUE TITLE
[Feature Request] Support for OpenAPI 3.1

### ISSUE THREAD

**Issue by ThaDaVos** [DarkaOnLine/L5-Swagger#488]
- L5-Swagger Version: 8.3.3 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 8.0.21
- OS: Ubuntu 20.04.4 LTS

### Description:
According to this page, the latest spec supported seems to be OpenAPI 3.0: https://github.com/DarkaOnLine/L5-Swagger/wiki/Installation-&-Configuration
Will there also be support for OpenAPI 3.1? It allows for some usefull extra features regarding $refs and other things

### Steps To Reproduce:
No steps as it's a feature request

**Comment by ThaDaVos** [comment]
See: https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0

**Comment by DarkaOnLine** [comment]
We use https://github.com/zircote/swagger-php under the hood to parse annotations to OpenApi. So this question/suggestion should got to SwaggerPHP.

**Comment by ThaDaVos** [comment]
I saw that https://github.com/zircote/swagger-php already supports 3.1, but i don't see any way to pass the version to the generator of swagger-php

**Comment by DarkaOnLine** [comment]
Oh I missed this. Hmm but they only allow to use this with the `--version` or `Generator::setVersion()`
So we could have new config key and set version here: https://github.com/DarkaOnLine/L5-Swagger/blob/master/src/Generator.php#L207 - this should do the trick.

Would you be wiling to contribute and submit PR for this?

**Comment by ThaDaVos** [comment]
Yeah something like that would fix it, i know it works as I extended and overrided somethings to test it  and it's doable to pass it through

**Comment by DarkaOnLine** [comment]
Would you be wiling to contribute and submit PR for this? Or should I add this to my todo list :)

**Comment by dietergeerts** [comment]
Sadly using 3.1 isn't an option as the used swagger-ui doesn't support it yet. Is there a way to use something else than swagger-ui? I know there are others out there that already support 3.1.
