### ISSUE TITLE
Undefined constant OpenApi\Annotations\OpenApi::DEFAULT_VERSION

### ISSUE THREAD

**Issue by RileyGB** [DarkaOnLine/L5-Swagger#492]
- L5-Swagger Version: 8.4.0
- PHP Version: 8.0.3
- OS: Linux

### Description:

It looks like an undefined constant made its way into the 8.4.0 release.

Error
Undefined constant OpenApi\Annotations\OpenApi::DEFAULT_VERSION
Error 
…/vendor/darkaonline/l5-swagger/config/l5-swagger.php148

It looks like this was added in:
https://github.com/DarkaOnLine/L5-Swagger/commit/7285dce2bf5eb9010d7826b52624311684a555cf

### Steps To Reproduce:
Update to 8.4.0, run any php command.

**Comment by DerManoMann** [comment]
The code in queston is part of the [swagger-php](https://github.com/zircote/swagger-php) library and this bit got introduced in 4.2.0. You might need to update your dependencies although these should be set by L5-Swagger already...

**Comment by DarkaOnLine** [comment]
Hmm, maybe I need to change the code and use local constant instead :(

**Comment by DerManoMann** [comment]
ouch!

**Comment by DarkaOnLine** [comment]
8.4.1 should be good now: https://github.com/DarkaOnLine/L5-Swagger/releases/tag/8.4.1
