### ISSUE TITLE
Can't open endpoint with anchor.

### ISSUE THREAD

**Issue by musqdp** [DarkaOnLine/L5-Swagger#496]
- L5-Swagger Version: 8.0.9 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.4.9
- OS: Windows

### Description:
Can't open endpoint with anchor.

### Steps To Reproduce:
1. Copy id from h3 element
2. Open new tab put url to swagger with #h3-id

**Comment by DarkaOnLine** [comment]
If it's not working, but it should,  you should report this to `swagger-ui`, this package just uses it to display docs
