### ISSUE TITLE
Required @OA\Info() not found

### ISSUE THREAD

**Issue by SuperStarDeveloper** [DarkaOnLine/L5-Swagger#498]
- L5-Swagger Version: 8.4(`composer show | grep l5-swagger`)
- PHP Version (`php -v`):8.1.6
- OS: windows 10

### Description:

![image](https://user-images.githubusercontent.com/58889694/194592663-15fc15c3-6b0a-4ff0-b305-bd5ec1a7aa1d.png)

### Steps To Reproduce:
composer require "darkaonline/l5-swagger"
php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"
php artisan l5-swagger:generate

  ErrorException 

  Required @OA\PathItem() not found

  at C:\xampp\htdocs\simpleflex-api\vendor\zircote\swagger-php\src\Loggers\DefaultLogger.php:31
     27▕         } else {
     28▕             $error_level = E_USER_WARNING;
     32▕     }
     33▕ }
     34▕

  1   C:\xampp\htdocs\simpleflex-api\vendor\zircote\swagger-php\src\Loggers\DefaultLogger.php:31
      trigger_error("Required @OA\PathItem() not found")

  2   C:\xampp\htdocs\simpleflex-api\vendor\psr\log\src\LoggerTrait.php:86
      OpenApi\Loggers\DefaultLogger::log("warning", "Required @OA\PathItem() not found", [])

<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

/**
 * @OA\Info(title="My First API", version="0.1")
 */
class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

**Comment by jgrandar** [comment]
Same here, it happens after adding @OA\Info() and @OA\Server() in Controller.php to avoid "Required @OA\Info() not found" problem.

**Comment by stebogit** [comment]
Got the same issue when using PHP Attributes; however it works using regular annotations (☹️ I was hoping I could avoid the horrible annotations...) 

```
darkaonline/l5-swagger  v8.4.1
laravel/framework       v9.31.0
PHP                     v8.0.23 (on Homestead)
```

**Comment by DerManoMann** [comment]
This message comes from swagger-php. As of version 4 annotations and attributes must be associated with structural elements (class, method, etc.). If not, reflection annot find them.
https://zircote.github.io/swagger-php/guide/faq.html#warning-required-oa-info-not-found

**Comment by stebogit** [comment]
@DerManoMann as I said using annotations works, but not with attributes.
Anyway I put my metadata inside a controller. Am I still doing something wrong? This is the first time I use swagger at all.

#### Works
```php
use App\Http\Controllers\Controller;

/**
 * @OA\Info(
 *     title="My First API",
 *     version="0.1"
 * )
 */
class ApiController extends Controller
{
    /**
     * @OA\Get(
     *     path="/api/data.json",
     *     @OA\Response(
     *         response="200",
     *         description="The data"
     *     )
     * )
     */
    public function status()
    {}
}
```

#### Does not
```php
use App\Http\Controllers\Controller;
use OpenApi\Attributes as OA;

#[OA\Info(title: "My First API", version: "0.1")]
class ApiController extends Controller
{
    #[OA\Get(path: '/api/data.json')]
    #[OA\Response(response: '200', description: 'The data')]
    public function status()
    {}
}
```

```bash
$ art l5-swagger:generate --verbose
Regenerating docs default

   ErrorException 

  Required @OA\Info() not found

  at vendor/zircote/swagger-php/src/Loggers/DefaultLogger.php:31
     27▕         } else {
     28▕             $error_level = E_USER_WARNING;
     29▕         }
     30▕ 
  ➜  31▕         trigger_error($message, $error_level);
     32▕     }
     33▕ }
     34▕ 

      +23 vendor frames 
  24  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by DerManoMann** [comment]
Hmm, classic case of `works for me` :shrug: 

What version of swagger-php do you have installed?

**Comment by stebogit** [comment]
this is what got installed by requiring `darkaonline/l5-swagger`:
```
swagger-api/swagger-ui    v4.14.3
zircote/swagger-php       v4.4.9   
```

**Comment by DerManoMann** [comment]
> ```
> swagger-api/swagger-ui    v4.14.3
> zircote/swagger-php       v4.4.9   
> ```

And you are on PHP 8.1? (Sorry, I should have asked earlier...)

**Comment by stebogit** [comment]
@DerManoMann I'm on [PHP 8.0](https://github.com/DarkaOnLine/L5-Swagger/issues/498#issuecomment-1275258336)

**Comment by DerManoMann** [comment]
> @DerManoMann I'm on [PHP 8.0](https://github.com/DarkaOnLine/L5-Swagger/issues/498#issuecomment-1275258336)

That's it then. Attributes are a PH 8.0 thing, but nested attributes require 8.1 and swagger-php will check for that as the code does use 8.1 features.

**Comment by Nex-Otaku** [comment]
![image](https://user-images.githubusercontent.com/2260071/196763472-718d5750-c8e8-4633-b8c7-6eb4df3d9796.png)

PHP 8.1
Laravel 9.3.8

**Comment by Chris1234567899** [comment]
I'm on PHP 8.1.4 (xampp) and get the same error.

**Comment by DerManoMann** [comment]
https://zircote.github.io/swagger-php/guide/faq.html#warning-required-oa-info-not-found

**Comment by Marvelch** [comment]
Maybe you can try this :

1. Add this in Controller : 

 /**
 * @OA\Info(
 *    title="APIs For Thrift Store",
 *    version="1.0.0",
 * ),
 *   @OA\SecurityScheme(
 *       securityScheme="bearerAuth",
 *       in="header",
 *       name="bearerAuth",
 *       type="http",
 *       scheme="bearer",
 *       bearerFormat="JWT",
 *    ),
 */


2. Add this in Api/HomeContoller or controller you make :
 /**
 * @OA\Get(
 *      path="/api/home",
 *      operationId="getProjectsList",
 *      tags={"Projects"},
 *      summary="Get list of projects",
 *      description="Returns list of projects",
 *      @OA\Response(
 *          response=200,
 *          description="Successful operation",
 *       ),
 *      @OA\Response(
 *          response=401,
 *          description="Unauthenticated",
 *      ),
 *      @OA\Response(
 *          response=403,
 *          description="Forbidden"
 *      )
 *     )
 */

**Comment by Joelfo** [comment]
This can be useful:
I had the same problem with swagger-php, which this package use, and came here searching for help. In the end i found a solution myself:
The swagger-php, at least using a php script to generate de openapi file, needs not only a @OA/Info somewhere in your code but also at least one @OA/Get. The problem was that I had a @OA/Get but the problem persisted, i tried changing the annotation based on the [documentation](https://zircote.github.io/swagger-php/guide/attributes.html#nesting) and then i found that i was writing the annotation wrongly:
Incorrect:
```
#[OA\Get(path: '/api/data.json', response: new OA\Response(response: '200', description: 'The data'))]
    public function show(int $patientId){
        return $this->controllerHelper->show($patientId);
    }
```
    
Correct:
```
#[OA\Get(path: '/api/data.json', responses: [new OA\Response(response: '200', description: 'The data')])]
    public function show(int $patientId){
        return $this->controllerHelper->show($patientId);
    }
```

You guys can be facing a similar problem, so compare your attributes with the examples from the [docs](https://zircote.github.io/swagger-php/guide/attributes.html#nesting) and check if there isn't any syntax problem

**Comment by Fideltodayy** [comment]
What was the solution to this issue?
Having the same thing but I cant find the solution

**Comment by dennis-hash** [comment]
Place @OA\Info outside the class.

```
namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Bus\DispatchesJobs;
/**
 * @OA\Info(
 *    title="Your super  ApplicationAPI",
 *    version="1.0.0",
 * )
 */
class Controller extends BaseController
{

    use AuthorizesRequests,DispatchesJobs, ValidatesRequests;

```}

**Comment by pjonaszik** [comment]
It works for me like this:
```php
use OpenApi\Annotations as OA;

/**
 * @OA\Info(
 *      version="1.0.0",
 *      title="Company - Service",
 *      description="Service documentation",
 *
 *      @OA\Contact(
 *          email="admin@admin.com"
 *      ),
 *
 *      @OA\License(
 *          name="Apache 2.0",
 *          url="https://www.apache.org/licenses/LICENSE-2.0.html"
 *      )
 * )
 */
class Controller extends BaseController
{
    /**
     * @OA\Server(
     *      url=L5_SWAGGER_CONST_HOST,
     *      description="Demo API Server"
     * )
     */
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

**Comment by paulido** [comment]
I encountered this problem. Here's the context: I've created a Controllers/API folder in which my controllers are located. I put this in Controllers/API/UserController:
```
use OpenApi\Annotations as OA;

/**
 * @OA\OpenApi(
 * @OA\Info(
 * version=“1.0”,
 * title=“Platform Event API”,
 * description=“Event Platform API”,
 * )
 * )
 */
```
This produces **Required @OA\Info() not found**

**Solution**: I moved the code to the App\Http\Controllers ( base controller ) and the problem disappeared.

**Comment by carteagaapplaudo** [comment]
Im getting this issue, but I want to have the annotations outside the Controller. Is that even possible at this point??

**Comment by DerManoMann** [comment]
Yes it is as long as the annotations are attached to a class-like.

https://zircote.github.io/swagger-php/guide/faq#warning-required-oa-info-not-found
