### ISSUE TITLE
Properties in traits loaded in parent class are not generated

### ISSUE THREAD

**Issue by rickgoemans** [DarkaOnLine/L5-Swagger#499]
- L5-Swagger Version: 8.4.1 (`composer show | grep l5-swagger`)
- Laravel version: 9.34.0
- PHP Version (`php -v`): 8.1.10
- OS: Mac OS

### Description:
I have a small setup for models that prevent me from writing duplicate properties, but when I add properties via a trait to the parent (abstract) model class, they are not generated in the children models.

### Steps To Reproduce:
Make the following 3 files (of course correct the namespace to your situation);

```php
<?php

namespace App\Http\Swagger\Models;

use OpenApi\Annotations as OA;

trait HasId
{
    /**
     * @OA\Property(
     *     format="int64",
     *     readOnly=true,
     * )
     *
     * @var int
     */
    public int $id;
}
```

```php
<?php

namespace App\Http\Swagger\Models;

use OpenApi\Annotations as OA;

abstract class Model
{
    use HasId;
}
```

```php
<?php

namespace App\Http\Swagger\Models;

use OpenApi\Annotations as OA;

/**
 * @OA\Schema(
 *     required={"street",},
 *     @OA\Xml(
 *         name="Address"
 *     )
 * )
 */
class Address extends Model
{
    /** @OA\Property */
    public string $street;
}
```

Here's the result of the JSON file:

```json
"Address": {
    "required": [
        "street"
    ],
    "properties": {
        "street": {
            "type": "string"
        }
    },
    "type": "object",
    "xml": {
        "name": "Address"
    }
},
```

Here's the result of Swagger UI:
![Screenshot 2022-10-12 at 13 10 50](https://user-images.githubusercontent.com/7813679/195328110-c5700165-875a-4bf2-93ad-00c553688aa2.png)

If you then include the `HasId` trait within the `Address` model, it will be shown correctly.

Of course I can move the `id` property to the `Model` class, but the general thought is that I have some properties that cannot be placed within just one file.
Anybody else experiencing similar issues and/or maybe know a good solution?
I can make a very complex class extending structure but that is not a realistic solution.

**Comment by rickgoemans** [comment]
For additional informatie, it does not matter wether the parent class is `abstract` or a normal class and wether the child models have properties (or other traits) or not.

**Comment by DerManoMann** [comment]
This is an issue with swagger-php.
Its an edge case since neither `Model` nor `HasId` have a `/** @OA\Schema() */` annotation. That means swagger-pph will try to merge annotations rather than inheritance, where you end up with something like
```yaml
allOf:
        -
          $ref: '#/components/schemas/Model'
``
Looks like the merge code does not lookup properties recursively through used traits in the (not schema) parent class.

Looks like there is also a bug involved because even if you annotate both `HasId` and `Model` with `/** @OA\Schema() */` the `Model` class is missing a `allOf` ref to `HasId`.

**Comment by rickgoemans** [comment]
> This is an issue with swagger-php. Its an edge case since neither `Model` nor `HasId` have a `/** @OA\Schema() */` annotation. That means swagger-pph will try to merge annotations rather than inheritance, where you end up with something like
> 
> ```yaml
> allOf:
>         -
>           $ref: '#/components/schemas/Model'
> ``
> Looks like the merge code does not lookup properties recursively through used traits in the (not schema) parent class.
> 
> Looks like there is also a bug involved because even if you annotate both `HasId` and `Model` with `/** @OA\Schema() */` the `Model` class is missing a `allOf` ref to `HasId`.
> ```

Thanks for the clarification and opening an issue at the source repo! Let's see what they're suggesting or coming up with related to a fix.

**Comment by rickgoemans** [comment]
It is fixed, thanks for the update and the fix!

**Comment by rickgoemans** [comment]
I just noticed that if you use a trait in both the parent (in my example the `abstract Model`) and the children (in my example `Address`), the properties in the traits of **ONLY** the parent class are loaded.

**Comment by rickgoemans** [comment]
Since the title of this issue does not fully cover the new situation, should I create a new issue?

My new setup would include another trait called `HasTimestamps` which contains two properties (`created_at` and `updated_at`) and is used in the `Address` model/schema.

Here's the trait:

```php
<?php

namespace ...

use Carbon\Carbon;
use OpenApi\Annotations as OA;

trait HasTimestamps
{
    /**
     * @OA\Property(
     *     format="date-time",
     *     type="string",
     *     readOnly=true,
     * )
     */
    public Carbon $created_at;

    /**
     * @OA\Property(
     *     format="date-time",
     *     type="string",
     *     readOnly=true,
     * )
     */
    public Carbon $updated_at;
}

Looking forward to your answer.

**Comment by DerManoMann** [comment]
Not a new issue, but since this is purely swagger-php related we should move this over to https://github.com/zircote/swagger-php/issues/1325 and close this one.
