### ISSUE TITLE
php artisan l5-swagger:generate

### ISSUE THREAD

**Issue by radiart** [DarkaOnLine/L5-Swagger#5]
Hi I run all comands from readme, but I have problem with last one:

when I use ``php artisan l5-swagger:generate`` I see error:

 `` [ErrorException]
  Required @SWG\Info() not found``

After 4 commands my folder structure looks like: 

![This](http://s1.postimg.org/psnn69rfj/vendor.jpg)

In console.log on page: o2c.html I see: 
``Uncaught TypeError: Cannot read property 'swaggerUi' of null`` o2c.html:14

P.S You have also typo in readme should be /vendor not /vendos

**Comment by DarkaOnLine** [comment]
If you read the swagger-php documentation you will see that one ot the classes or file has to have this and other general api description tags. Now I am on mobile and can't drop you a link.

Thanks for a miss tipe notice,  will fix it.

**Comment by DarkaOnLine** [comment]
@radiart this is the example I mentioned before: 

[https://github.com/zircote/swagger-php/blob/master/Examples/petstore.swagger.io/swagger-v2.php](https://github.com/zircote/swagger-php/blob/master/Examples/petstore.swagger.io/swagger-v2.php)

**Comment by Pe-Fahimi** [comment]
Hi 
in file resources/views/index.blade.php at line 74,
window.authorizations.add("api_key", new ApiKeyAuthorization("api_key", key, "query"));
"api_key" is hard coded.
I wish it was variable that could be set in config.
my api uses "access_token" instead.

thanks a lot man.

**Comment by ratanakpek** [comment]
How can we fixed this? Could you tell me a bit? Thanks!

**Comment by DarkaOnLine** [comment]
You must include ` @SWG\Info()` in your annotations. Please read swagger documentation

**Comment by rbarrientos182** [comment]
@DarkaOnLine  In what  annotations? Are you referring to controllers?
