### ISSUE TITLE
Make "filer by tag" case insensitive

### ISSUE THREAD

**Issue by EdgarsJoja** [DarkaOnLine/L5-Swagger#508]
- L5-Swagger Version: 8.4.1
- PHP Version: 8.1
- OS: -

### Description:
Currently "filter by tag" functionality doesn't find tags that are not matching the keyword **exactly**. In my opinion, it would be beneficial if it would find and filter the tags regardless of the word case.

For example: when searching with keyword "test", it should find all these tagged sections - "Test", "test", "TEST", etc. 

### Steps To Reproduce:
(I think it's clear)
![image](https://user-images.githubusercontent.com/8993227/201350943-3d33949f-4463-4699-9246-b950085be483.png)

**Comment by DarkaOnLine** [comment]
This is swagger-ui functionality, and it only allows case sensitive filtering: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md

![image](https://user-images.githubusercontent.com/1171698/211999379-48e50940-e196-45eb-b3c5-aba7f313665f.png)

If you want custom behaviour you would need to write a custom plugin for swagger-ui or contribute and add this possibility
