### ISSUE TITLE
Required @SWG\Info() not found

### ISSUE THREAD

**Issue by arslan** [DarkaOnLine/L5-Swagger#51]
when i set L5_SWAGGER_GENERATE_ALWAYS=true in .env file i am getting error 

Required @SWG\Info() not found

it looks like i have to give this comment, but not sure where i have to give it

**Comment by DarkaOnLine** [comment]
Please look at Swagger documentation. You Must provide general information. You can create separate file for it ant put it in your scan directory ;)

**Comment by DarkaOnLine** [comment]
I referenced the same issue #87 with the answer for your question. Plus this problem is not related to the package it is Swagger annotations error.
