### ISSUE TITLE
adding built in web auth to the docs pages

### ISSUE THREAD

**Issue by isaiahfisher** [DarkaOnLine/L5-Swagger#510]
- L5-Swagger Version:  8.4.1
- PHP Version (`php -v`): 7.4.32
- OS: macOS Monterey 12.6.1

### Description:
It appears that users are not required to be authenticated to access documentation. I would like to force users to authenticate using the normal web guard.

### Steps To Reproduce:
Set up an application with default laravel authentication using Eloquent user model as a provider.
Try to add the 'web' and 'auth' middleware to api and docs for l5-swagger configs.
#### Expected:
user should not be allowed to access page unless they are already logged into the application.
#### Actual:
anyone is able to access the documentation without needing to authenticate.

### Further questions:
Am I doing something wrong? I see that there is a security section, but I just want to use the existing application authentication. The documentation is designed to expose api endpoints to application end users for automating common business to business operations that are normally performed in the web UI of this application. Unauthenticated users should not be able to access the documentation.

**Comment by ronaldwanink** [comment]
@isaiahfisher Same here, did you manage to get this to work?
