### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Chris1234567899** [DarkaOnLine/L5-Swagger#511]
- L5-Swagger Version: 8.4.1
- PHP Version (`php -v`): PHP 8.1.4
- OS: Windows 10

### Description:
For one certain request, I get an error:
`😱 Could not render _t, see the console.`

And looking in the console:
`Maximum call stack size exceeded`

The same request is working fine for another item, so I assume it's hard to track. But the error seems to be not uncommon with swagger UI
https://github.com/swagger-api/swagger-ui/issues/4411

EDIT: Apparently it happens because of a very large response in my case and this causes issues with swagger UI.
People suggest to turn off syntax highlighting. Is there the option to configure this behavior in the config l5-swagger.php or something?

**Comment by DarkaOnLine** [comment]
We do not have setting to turn syntax highlighting off, but you can always overwrite https://github.com/DarkaOnLine/L5-Swagger/blob/master/resources/views/index.blade.php and configure swagger-ui as you like
