### ISSUE TITLE
Swagger For Windows 10, not working while referencing schemas from other files.

### ISSUE THREAD

**Issue by iciani** [DarkaOnLine/L5-Swagger#512]
- L5-Swagger Version: 8.4.1
- PHP Version: 8.1.0
- OS: Windows 10

### Description:
Whenever we run "php artisan l5-swagger:generate default", and the swagger executes, we encounter an error with the following description.

   ErrorException 

  Multiple @OA\Schema() with the same schema="[schema name]":
  C:\...\www\[PROJECT NAME]\app\Http\Requests\Admin\V1\[FILE WHERE THE SCHEMA IS DEFINED].php on line 10

This is happening whenever we define a schema in a separated file, and we reference it as an object, and a path to the original schema. As we show example in the photos.

[https://i.imgur.com/xI8Kv3A.png](url)
[https://i.imgur.com/0FzBCoD.png](url)
[https://i.imgur.com/TuCVwfC.png](url)

SCHEMA IN A REQUEST FILE.
REFERENCE AS OBJECT TO THAT SCHEMA IN A CONTROLLER.

### Steps To Reproduce:
As explained above, we define a schema in a request file, and reference it with:

     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/x-www-form-urlencoded",
     *             @OA\Schema(
     *                 type="object",
     *                 ref="**#/components/schemas/MKTGCampaignEntryRequest**",
     *             )
     *         )
     *     ),

while executing the swagger generator command, we found the error describe above.

Multiple @OA\Schema() with the same schema="MKTGCampaignEntryRequest":
  C:\...\www\[PROJECT NAME]\app\Http\Requests\Admin\V1\MKTGCampaignEntryRequest.php on line 10
  C:\...\www\[PROJECT NAME]\app\Http\Requests\Admin\V1\MKTGCampaignEntryRequest.php on line 10

Thanks in advance for all the help!
Warm Regards, 
Ignacio.

**Comment by DarkaOnLine** [comment]
This is not an issue with the package but with the annotations, not much I can help here, sorry
