### ISSUE TITLE
Attributes PHP 8.1

### ISSUE THREAD

**Issue by jubagg93** [DarkaOnLine/L5-Swagger#514]
- L5-Swagger Version: 8.4.1
- PHP Version 8.1:
- OS: ubuntu

Description:
It's possible use new attributes notation?

**Comment by DarkaOnLine** [comment]
Yes: https://github.com/zircote/swagger-php/blob/ee8147745c92dd4404adb531751ce32676b888d4/docs/guide/attributes.md
