### ISSUE TITLE
How pass array in swagger package

### ISSUE THREAD

**Issue by shilpatipl** [DarkaOnLine/L5-Swagger#523]
save_deals_data[0][room_id]=101512
save_deals_data[0][start_date]=06/27/2022
save_deals_data[0][end_date]=08/23/2022
save_deals_data[0][number_of_guests]=2
save_deals_data[0][pets]= yes or no

https://prnt.sc/pRR_vF_BTaIJ

**Comment by DarkaOnLine** [comment]
Please provide more information and explanation about issue
