### ISSUE TITLE
middleware doesn't work

### ISSUE THREAD

**Issue by Broutard** [DarkaOnLine/L5-Swagger#53]
In your routes.php you have :
config('l5-swagger.middleware.api', [])

But it is :
config('l5-swagger.routes.middleware.api', [])

PR here : https://github.com/DarkaOnLine/L5-Swagger/pull/54

**Comment by DarkaOnLine** [comment]
Fixed it in:

https://github.com/DarkaOnLine/L5-Swagger/releases/tag/3.2.2
https://github.com/DarkaOnLine/L5-Swagger/releases/tag/4.0.1
