### ISSUE TITLE
How to add textarea input type

### ISSUE THREAD

**Issue by jocartboy2** [DarkaOnLine/L5-Swagger#538]
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 8
- OS: windows 10

### Description:

I tried to use the format="textarea" but it doesn't work is there any way that we can use a textarea as input ? thank you.

### Steps To Reproduce:
here is our swagger parameter with schema.
     *     @OA\Parameter(
     *         name="bio",
     *         description="bio",
     *         in="query",
     *         @OA\Schema( 
     *             type="string",     
     *             format="textarea",
     *             example=""
     *         ),
     *     ),
     we expected that the input will change to textarea for large string that we need to input please let us know how to handle this thanks.

**Comment by DerManoMann** [comment]
According to the [spec](https://spec.openapis.org/oas/v3.0.3#dataTypeFormat) the only format values allowed are `byte` and `binary`. Not sure what tools like `swagger-ui` will make of it but it might be worth a try.

Keep in mind that the purpose of `type` and `format` is to document the data type returned  by your API, not how a tool like `swagger-ui` is supposed to render it. If at all, there might be vendor extensions to tell the UI to use a different form type but that is a question better asked in the `swagger-ui` project.

**Comment by jocartboy2** [comment]
HI @DerManoMann I think swagger-ui was a different implementation from l5-swagger. the solution there is not compatible to l5-swagger
