### ISSUE TITLE
CSRF token mismatch error

### ISSUE THREAD

**Issue by guigralho** [DarkaOnLine/L5-Swagger#543]
- L5-Swagger Version: 8.5.0
- PHP Version (`php -v`): 8.2.6
- OS: ubuntu 22

When I make requests via the swagger documentation, the X-CSRF-TOKEN on header is null all the times and I get the SRF token mismatch error

![Captura de tela de 2023-05-26 13-43-26](https://github.com/DarkaOnLine/L5-Swagger/assets/4997341/1dabd491-f2aa-4691-a583-7c45f5b2905b)

**Comment by dean26** [comment]
> Looks like documentation routes need middleware "web" php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider" and in config/l5-swagger.php: defaults-> middleware[ 'api' => ['web'], 'asset' => [], 'docs' => [], 'oauth2_callback' => [], ]

It didn't help... Any ideas?
I'm using php 8.2, Laravael 10. 

It works on editor.swagger.io but not in laravel..

**Comment by OsamaAlmamri** [comment]
in kernel file section api 
commit  this middleare       \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,

        'api' => [
            \App\Http\Middleware\ForceJsonResponse::class,

//            \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
            \Illuminate\Routing\Middleware\ThrottleRequests::class.':api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

**Comment by quanghuybest2k2** [comment]
Fixed this issue by updating file `app/Http/Middleware/VerifyCsrfToken.php`

Add `/api/*` item to `$except` array:
```php
protected $except = [
  "/api/*"
];
```

**Comment by vibonacci** [comment]
@quanghuybest2k2 
You're disabling the CRSF checks for all API routes. That is NOT recommended. CSRF tokens are important if API calls are made from browser/web.

**Comment by JacksonPorter7478** [comment]
- L5-Swagger Version: 8.5.0
-PHP Version (php -v): 8.2.12
-OS: windows
-laravel/framework: 9.52.16

I have same errors.
I try to fix that error according to your tips but I can't fix that error and I have same so.

![Uploading Screenshot 2024-01-14 153950.png…]()

**Comment by JacksonPorter7478** [comment]
- L5-Swagger Version: 8.5.0
-PHP Version (php -v): 8.2.12
-OS: windows
-laravel/framework: 9.52.16

I have same errors.
I try to fix that error according to your tips but I can't fix that error and I have same so.

![Screenshot 2024-01-14 153950](https://github.com/DarkaOnLine/L5-Swagger/assets/153564932/5e17f6e8-35ff-4351-96a8-9180c5151184)

**Comment by marcelodmdo** [comment]
> Looks like documentation routes need middleware "web" php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider" and in config/l5-swagger.php: defaults-> middleware[ 'api' => ['web'], 'asset' => [], 'docs' => [], 'oauth2_callback' => [], ]

This works like charm. Looks the right and safe way. That's right?
