### ISSUE TITLE
Error: `Required @OA\Info() not found` when trying to generate the docs on the first run

### ISSUE THREAD

**Issue by nexxai** [DarkaOnLine/L5-Swagger#553]
- L5-Swagger Version: 8.5.1
- PHP Version (`php -v`): 8.2.8
- OS: macOS

### Description:
On a fresh install of the package, I try to run `php artisan l5-swagger:generate` and I get the error: `Required @OA\Info() not found`

### Steps To Reproduce:

1. Install package
2. Run the generate command

**Comment by nexxai** [comment]
According to https://zircote.github.io/swagger-php/guide/faq.html#warning-required-oa-info-not-found this is known problem, but I don't understand the solution (add a dummy class somewhere?) they provide to solve the problem.

**Comment by DerManoMann** [comment]
The example annotation in the FAQ contains the empty `OpenApiSpec` class. That is the dummy class.

The most minimal example would be something like
```php
/**
 * OA\Info()
 */
class SomeClass{}
```

The point is that the docblock cannot exist on its own but must be associated with some code (types are listed in the FAQ)

**Comment by leidison** [comment]
I have some problem.

```
namespace App\Http\Controllers;

...

/**
 * @OA\Info(
 *      version="1.0.0",
 *      title="My OpenApi Documentation",
 *      description="My OpenApi description",
 *      @OA\Contact(
 *          email="support@mysite.com"
 *      ),
 *      @OA\License(
 *          name="Proprietary",
 *          url=""
 *      )
 * )
 *
 * @OA\Server(
 *      url=L5_SWAGGER_CONST_HOST,
 *      description="My API Server"
 * )
 */
class Controller extends BaseController
```

When i run **php artisan l5-swagger:generate**:

```
Regenerating docs default

   ErrorException 

  Required @OA\Info() not found

  at vendor/zircote/swagger-php/src/Loggers/DefaultLogger.php:31
     27▕         } else {
     28▕             $error_level = E_USER_WARNING;
     29▕         }
     30▕ 
  ➜  31▕         trigger_error($message, $error_level);
     32▕     }
     33▕ }
     34▕ 

      +22 vendor frames 

  23  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

My package.json:

```
"require": {
        "php": "^8.2",
        "ext-pdo": "*",
        "ext-zip": "*",
        "darkaonline/l5-swagger": "^8.5",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "robsontenorio/laravel-keycloak-guard": "^1.4"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    }
 ```

**Comment by robson83** [comment]
Just started having the same problem after an update few hours ago. Anybody?

**Comment by DerManoMann** [comment]
As of 4.8 doctrine annotations are optional. You might notice them being uninstalled as part of the update.
```
composer require doctrine/annotations 
```
should do the trick.
I'll see that I update the docs soon.

**Comment by DarkaOnLine** [comment]
Updating to `8.5.2` should be good now: https://github.com/DarkaOnLine/L5-Swagger/releases/tag/8.5.2
