### ISSUE TITLE
RequiredSWG@Info not found

### ISSUE THREAD

**Issue by ihsanberahim** [DarkaOnLine/L5-Swagger#56]
i try run 
`php artisan l5-swagger:generate`

then got error

```
[ErrorException]
Required @SWG\Info() not found
```

**Comment by DarkaOnLine** [comment]
You need to provide `@SWG\Info`. See example: https://github.com/DarkaOnLine/L5-Swagger/blob/master/tests/storage/annotations/ApiAnotationsExample.php

**Comment by jvihrial** [comment]
One thing to note here , if you set @SWG\Info in your api.php or alike, it won't work. So put it into some controller. I tend to put it to my basecontroller, then it works for sure :)

**Comment by IgnacioYanjari** [comment]
I have the same issue but change the `base_path('app')` of annotations inside l5-swagger.php
![screen shot 2018-08-22 at 5 13 25 pm](https://user-images.githubusercontent.com/18061260/44488350-e970f280-a62e-11e8-816c-a51205a80b81.png)
