### ISSUE TITLE
Add Button to toggle a preview of html returned in a response Or Preview page when content-type is html

### ISSUE THREAD

**Issue by bahubaliSITH** [DarkaOnLine/L5-Swagger#561]
Screenshots are below. Notice the Show/Hide preview button in the bottom left corner.

![show preview](https://github.com/DarkaOnLine/L5-Swagger/assets/87180510/ba77d0ea-1bf0-411c-ae5f-17f0b8bff966)

![hide preview](https://github.com/DarkaOnLine/L5-Swagger/assets/87180510/ac63adb2-be60-450b-b559-998f811cf27e)

Or Preview page when content-type is html

error page render as html, but swagger show as html code.

<img width="1315" alt="html response swagger" src="https://github.com/DarkaOnLine/L5-Swagger/assets/87180510/0cdd6819-c053-4ef7-8c97-3827c0bf61dd">

it 's very difficult to get error info, postman has a preview mode.

![html response postman](https://github.com/DarkaOnLine/L5-Swagger/assets/87180510/e890681b-5e09-47f4-a4a4-56d75bd6588c)

**Comment by DarkaOnLine** [comment]
This is feature request for `swagger-ui`, not this package
