### ISSUE TITLE
 No publishable resources for tag [].

### ISSUE THREAD

**Issue by Traineratwot** [DarkaOnLine/L5-Swagger#565]
The component installation cannot be completed
```bash
php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"

INFO  No publishable resources for tag [].  
```
Versions:

- Laravel Framework: 10.35.0
- PHP: 8.2.10
- Composer version: 2.6.5 2023-10-06 10:11:52
- OS: Linux (in Docker)
- darkaonline/l5-swagger: 2.1.3

**Comment by shankhadevpadam** [comment]
Install Laravel Swagger using

```
composer require darkaonline/l5-swagger "^8.5.1" -W 
```

**Comment by Traineratwot** [comment]
Yes, it`s worked

**Comment by abdellahak** [comment]
For those who still have the same problem, try running the following command:
```
composer dump-autoload
```
before executing:
```
php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"
```
