### ISSUE TITLE
Compatible issues with zircote/swagger-php

### ISSUE THREAD

**Issue by WartVader** [DarkaOnLine/L5-Swagger#566]
- L5-Swagger Version: 8.5.0
- PHP Version: 8.1
- OS: mac OS (used with laravel sail, and on the dev server is using docker with ubuntu)

### Description:
In one day on our dev server stopped working our l5-swagger:generate command and always drop an error of @OA\PathItem was not found, so we go to check what was an issue and after some research we discovered, that l5-swagger is incompatible (might be) with package zircote/swagger-php with version 4.8.1 (on local machine we got 4.7.10 and generating on local machine was fine)

### Steps To Reproduce:
Set zircote/swagger-php in your require field in composer to version 4.8.1, and l5-swagger to 8.5.0 and you might get the same error on generating docs. Error that we got: 
![telegram-cloud-photo-size-2-5456173853106624610-y](https://github.com/DarkaOnLine/L5-Swagger/assets/28671703/1bda60f7-7145-472b-a929-a529a94f8f4f)

**Comment by DarkaOnLine** [comment]
They removed `doctrine/annotations` https://github.com/zircote/swagger-php/pull/1516/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R8 and now it needs to be installed optionally :( 

We might need to add them as requirement for this package
