### ISSUE TITLE
 model example not showing 

### ISSUE THREAD

**Issue by Bicotprojects** [DarkaOnLine/L5-Swagger#587]
— L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)  8.5.2
![image](https://github.com/DarkaOnLine/L5-Swagger/assets/147033360/85ea067a-e774-4571-903f-449e21c968ea)

— PHP Version (`php -v`): php8.1
![image](https://github.com/DarkaOnLine/L5-Swagger/assets/147033360/7d44826a-d811-4fc5-9008-30f19bd2f9be)

— OS: Ubuntu 20.04.6 LTS

### Description:
Model working fine but model example not showing  check below URL 
![image](https://github.com/DarkaOnLine/L5-Swagger/assets/147033360/20e3991c-d915-497e-8531-e514795cd209)

**Comment by ByronBoh** [comment]
I also have this issue. It was caused by the `swagger-api/swagger-ui` library getting updated recently. Using `composer require swagger-api/swagger-ui:v5.11.7` to revert to the previous version can temporarily fix it.

**Comment by Bicotprojects** [comment]
Thanks, @ByronBoh working fine.
