### ISSUE TITLE
404 Not Found for Swagger UI assets

### ISSUE THREAD

**Issue by marcuschristiansen** [DarkaOnLine/L5-Swagger#588]
- L5-Swagger Version: 8.5.2
- PHP Version: 8.1.27
- OS: Mac OS

### Description:
When accessing `/api/documentation` I get a blank page. The console shows 404 errors for the assets. Application is inside a subfolder in repo at `/folder/sub-folder/subfolder/laravel-app`

![Screenshot 2024-02-28 at 09 03 02](https://github.com/DarkaOnLine/L5-Swagger/assets/8204622/218ee3fe-48f3-4388-aecb-029420e497a4)

### Steps To Reproduce:

- Followed installation instructions
`$ php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"`
`$ php artisan l5-swagger:generate`

**Comment by marcuschristiansen** [comment]
Solved by setting `L5_SWAGGER_USE_ABSOLUTE_PATH` to `false`.

**Comment by utpal21** [comment]
I was facing same issue and finally its solved. Thank you so much @marcuschristiansen . You saved my day. 
> Supported.
