### ISSUE TITLE
Add Swagger 3.0 support

### ISSUE THREAD

**Issue by miroshnik** [DarkaOnLine/L5-Swagger#59]

**Comment by DarkaOnLine** [comment]
We depending on zircote/swagger-php for parsing documentation. And for now [it is not supporting it](https://github.com/zircote/swagger-php/issues/384), so are we.

Or you can suggest other library which can parse 3.0 documentation and contribute on implementation.

**Comment by N3m1s** [comment]
I think @miroshnik was having Swagger UI 3.0 and not the documentation it self. The OpenAPI spec is 2.0.

**Comment by bfanger** [comment]
Check out the swagger-php [3.x branch](https://github.com/zircote/swagger-php/tree/3.x)
and try to update L5-Swagger, if you find any issues [let me know](https://github.com/zircote/swagger-php/issues/new).

**Comment by DarkaOnLine** [comment]
OpenApi 3.0 is now supported https://github.com/DarkaOnLine/L5-Swagger/commit/99ec1c855577fe4cc4cd987f4625ae35ee39a297

How to - https://github.com/DarkaOnLine/L5-Swagger#using-openapi-30-specification

Thank @bfanger for a great job!!!

**Comment by barkamlesh** [comment]
Is there a way to upgrade Swagger UI 3 with Laravel 5.1 ?

**Comment by DarkaOnLine** [comment]
@barkamlesh - you can try manually require `"swagger-api/swagger-ui": "^3.0"` in your composer file and see what will happen. But you also will need to update `index.blade.php` to use the new version. It should be possible but just needs work ;)
