### ISSUE TITLE
unable to pass `operationId.hash=false` config to zircote

### ISSUE THREAD

**Issue by mjpvandenberg** [DarkaOnLine/L5-Swagger#590]
- L5-Swagger Version: 8.5.0
- PHP Version: 8.2.13
- OS: Ubuntu 22.4

We'd like our generated API docs to include plain-text operation IDs instead of hashed ones. This should be configurable: https://zircote.github.io/swagger-php/reference/processors.html#operationid

Is it possible to pass this configuration via L5-swagger?

**Comment by SenSkysh** [comment]
any updates?

**Comment by DarkaOnLine** [comment]
Probably you are looking for custom [processor](https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php#L125) which you need to implement by your self and include it in config

**Comment by DarkaOnLine** [comment]
Or you are looking for ability to configure any processor with the configuration? https://zircote.github.io/swagger-php/reference/processors.html
