### ISSUE TITLE
Swagger-ui Update from 5.15.2 to 5.16.0 results in missing api-docs.json

### ISSUE THREAD

**Issue by Keenora** [DarkaOnLine/L5-Swagger#602]
- L5-Swagger Version: 8.6.0
- PHP Version: 8.1.27
- OS: Ubuntu 20.04.6 LTS

### Description:
Since the latest swagger-ui Update from [5.15.2 to 5.16.0.](https://github.com/swagger-api/swagger-ui/compare/v5.15.2...v5.16.0) the api-docs.json cannot be loaded anymore. The dev-console shows, that it tries to call a "null"-named file, instead of the correct json-file. If you enter the json-file manually, it works like a charm. I figured out, that the issue is the swagger-ui dependency, however that one works properly on it's own.

### Steps To Reproduce:
Current "composer update" updates the swagger-ui to its latest version. Its reproduceable on a fresh install, so there shouldn't be an issue to reproduce that error.

**Comment by koraga** [comment]
already fixed https://github.com/swagger-api/swagger-ui/releases/tag/v5.16.1
