### ISSUE TITLE
File resources/views/index.blade.php completely ignored when generating docs via `l5-swagger:generate`

### ISSUE THREAD

**Issue by alexandrmazur96** [DarkaOnLine/L5-Swagger#604]
- L5-Swagger Version: 8.6.0 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 8.0.22
- OS: Ubuntu 22.04

### Description:
I want to replace favicon in the generated API docs, but the library just generates docs with the default path to favicon `/favicon.ico`. Is there any way to change it?

### Steps To Reproduce:

1. Change favicon if published `/resources/views/vendor/l5-swagger/index.blade.php`
2. Generate docs via `l5-swagger:generate`
3. Notice favicon the same

**Comment by DarkaOnLine** [comment]
If you chnage any HTML in published `/resources/views/vendor/l5-swagger/index.blade.php` file it should just work as it overrides the default view
