### ISSUE TITLE
Required @OA\PathItem() not found error

### ISSUE THREAD

**Issue by maxechendu** [DarkaOnLine/L5-Swagger#608]
- L5-Swagger Version: 8.6.0
- PHP Version: 8.2.19
- OS: Linux (Debian)

### Description:

I've installed `darkaonline/l5-swagger` on my **Laravel 11** project, unlike the tutorials, I'm placing my swagger documentation on the routes an not above Controller methods (keeps Controller files lean).

When I run `php artisan l5-swagger:generate` , I get the following error:

```
Required @OA\PathItem() not found
```

### Steps To Reproduce:

1. After installing, publish the config file `php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"`
2. Add the following above any route in `routes/api.php`:

```
/**
 * @OA\Info(
 *   version="1.0",
 *     
 *   title=" API Documentation",
 *   descrption="API documentation for version 1.0 endpoints.",
 *   
 *   @OA\Contact(
 *     email="test@mail.com"
 *   ),
 * )
 * @OA\Get(
 *   path="/",
 *   summary="Health-check endpoint"
 *   
 *   @OA\Response(response=200, description="OK")
 * )
 */
```
3. Run  `php artisan l5-swagger:generate`

<br>

I wasn't sure if it was because in the config, `documentations.default.annotations` was set to `base_path('app')`, so I tried changing it to `base_path('routes')` instead, but got the same error.

**Comment by maxechendu** [comment]
Works perfectly when placing the annotations in the controller. Not sure why the routes approach doesn't work, but will have to stick with the controller approach. Closing this.

**Comment by DerManoMann** [comment]
Annotations (and Attributes) need to be associated with things like class/interface/trait/method etc. so PHP reflection can be used to access them.

**Comment by maxechendu** [comment]
> Annotations (and Attributes) need to be associated with things like class/interface/trait/method etc. so PHP reflection can be used to access them.

Makes sense. Though I have seen swagger annotations used in routes before at a place I worked at. Not sure how they managed that as it was already set-up when I joined, so I figured it would be possible.

**Comment by DerManoMann** [comment]
This changed in v4, mainly because some of the implementation for attributes requires reflection and the best solution was to use the same for annotations.
