### ISSUE TITLE
PathFilter is not supported

### ISSUE THREAD

**Issue by caixingyue** [DarkaOnLine/L5-Swagger#610]
- L5-Swagger Version: 8.6.0
- PHP Version (`php -v`): 8.3.3
- OS: imac

### Description:
There is no configurable parameter for this feature `https://github.com/zircote/swagger-php/issues/1609`

### Steps To Reproduce:
This is a new feature. I read a lot of code but didn't find any usable configuration.

**Comment by DarkaOnLine** [comment]
This https://github.com/DarkaOnLine/L5-Swagger/pull/620 solve this
