### ISSUE TITLE
Include additional directories to scan

### ISSUE THREAD

**Issue by adam-devapp** [DarkaOnLine/L5-Swagger#63]
I have been separating my API into a separate service provider (module), however your app only scans the base path.

            $swagger = \Swagger\scan($appDir, ['exclude' => $excludeDirs]);

Would be great to add custom paths in the config file too.

**Comment by adam-devapp** [comment]
Can see swagger only has one include and multiple excludes on the function scan.

Alternative solution was to update configuration path to be the whole project, then exclude vendor. Works as expected.

        'annotations' => base_path(),
        'excludes' => ['vendor'],

**Comment by abbluiz** [comment]
What if my module is inside vendor?
