### ISSUE TITLE
Add *.yml support

### ISSUE THREAD

**Issue by kolyabres** [DarkaOnLine/L5-Swagger#69]
Guys, how about add `api-docs.yml` files support?

**Comment by DarkaOnLine** [comment]
[Swagger-php](https://github.com/zircote/swagger-php) does not support generation to `yml` format.

Of course,  we can always do `json` to `yml`, but it does not make sense to me.

Can you tell my more about why you need `yml` format?

**Comment by kolyabres** [comment]
It is easy to edit `yml` files. You do not need put `"` every time

**Comment by DarkaOnLine** [comment]
Would you like to make a PR for this ?

**Comment by kolyabres** [comment]
Yes. I'll do that.

**Comment by moneal** [comment]
Right now I use json2yml to do the conversion and it works great but it would be nice to have native support.

**Comment by DarkaOnLine** [comment]
Closing this because of no progress or PR
