### ISSUE TITLE
i wanna divide admin and service for each 'swagger'

### ISSUE THREAD

**Issue by danielzepp** [DarkaOnLine/L5-Swagger#71]
can i use 2 swagger on a project?
i have routes group
service => /v1
admin => /admin
i have no idea... please help me

**Comment by moneal** [comment]
I have my api broken into services and it would be really nice to have the documentation separated so its not confusing to developers.

**Comment by san4io** [comment]
I also need to have Internal and Public API. Some suggestions?

**Comment by Rivsen** [comment]
@DarkaOnLine I finished a version of multiple separated documentation, is there has any contribution guidelines like how to support multiple laravel version? Thanks.

**Comment by DarkaOnLine** [comment]
Here was my thoughts how to implement this feature - #149

Talking about guidelines - please cover as much code as possible with test and document it. Also include instructions in readme, because it is new feature
