### ISSUE TITLE
Can not view api document

### ISSUE THREAD

**Issue by hunglq** [DarkaOnLine/L5-Swagger#73]
Hi i am on laravel 5.4 

i ran 
l5-swagger:generate 
l5-swagger:publish

when i open browser with link http://xxx.local:8000/api/documentation

i see in console log , not sure what is wrong 

"NetworkError: 500 Internal Server Error - http://xxx.local:8000/docs/asset/swagger-ui-standalone-preset.js"
swagger...eset.js
"NetworkError: 500 Internal Server Error - http://xxx.local:8000/docs/asset/swagger-ui-bundle.js"
swagger...ndle.js
"NetworkError: 500 Internal Server Error - http://xxx.local:8000/docs/asset/swagger-ui-standalone-preset.js"

then i tried to run 

l5-swagger:publish-assets
then got this 

 [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "l5-swagger:publish-assets" is not defined.             
  Did you mean one of these?                                      
      l5-swagger:generate                                         
      l5-swagger:publish                                          
      l5-swagger:publish-config                                   
      l5-swagger:publish-views

**Comment by DarkaOnLine** [comment]
`l5-swagger:publish-assets` was removed since 5.0, so I assume you are migrating from the older version.

Please [follow the steps in the migration guide.](https://github.com/DarkaOnLine/L5-Swagger#migrate-from-3040-to-50) and let me know if you succeed.

**Comment by hunglq** [comment]
@DarkaOnLine i followed all step but it didn't work

**Comment by DarkaOnLine** [comment]
Try to run `php artisan optimize` and check if you correctly registered the package.

**Comment by hunglq** [comment]
Hungs-MacBook-Pro:listqwick hunglq$ php artisan optimize
Generating optimized class loader
The compiled services file has been removed.
@DarkaOnLine

**Comment by DarkaOnLine** [comment]
What are you seeing by visiting this link:  http://xxx.local:8000/docs/asset/swagger-ui-standalone-preset.js

What error does it show? Can you see any errors in log files?

**Comment by hunglq** [comment]
@DarkaOnLine 

(1/1)
                                        FatalErrorException
                                    
                                    syntax error, unexpected '[', expecting ']'
--
in SwaggerAssetController.php (line 16)

**Comment by DarkaOnLine** [comment]
Which PHP version are you using?

**Comment by hunglq** [comment]
@DarkaOnLine  it works now ,

**Comment by DarkaOnLine** [comment]
@hunglq what was wrong? What did you do to fix it?

**Comment by hunglq** [comment]
@DarkaOnLine i have too much php version  and by default it is using php 5.6.10 , after that i switched to php 7 and it worked , thank you for your support @DarkaOnLine

**Comment by Sob03** [comment]
hi

**Comment by Sob03** [comment]
Can`t view api document error 500
