### ISSUE TITLE
Sagger ui asset exceptions

### ISSUE THREAD

**Issue by andrewklau** [DarkaOnLine/L5-Swagger#74]
v5 l5-swagger seems to be throwing off a few asset based exceptions, it's not entirely clear if this is a configuration issue (?) as they don't appear to be explicitly allowed in src/helpers.php

(swagger-ui-bundle.js.map) - this L5 Swagger asset is not allowed
(swagger-ui.css.map) - this L5 Swagger asset is not allowed
(swagger-ui-standalone-preset.js.map) - this L5 Swagger asset is not allowed

**Comment by DarkaOnLine** [comment]
@andrewklau you are right, .map files are included. But why do you need them and where do you see those exceptions?

**Comment by andrewklau** [comment]
I have my laravel app sending me slack notifications whenever an exception is thrown. So l5-swagger sends me a bunch of exceptions every time someone tries to use the swagger-ui

Everything works just the exception is thrown about 3 times every request.
