### ISSUE TITLE
API documentation is not shown (show blank page)

### ISSUE THREAD

**Issue by matriphe** [DarkaOnLine/L5-Swagger#75]
I used fresh Laravel 5.4.28 and fresh L5-Swagger version 5.0.3. I have followed the installation and worked properly (also executed `l5-swagger:publish`). But the documentation page is not shown.

Just read issue #73 and followed the instruction there, and my page is still blank (the background is light grey, so I supposed the CSS was loaded correctly).

I inspected and found errors mentioning all asset files `asset/swagger-ui.css`, `asset/swagger-ui-bundle.js`, and `asset/swagger-ui-standalone-preset.js` are not found (HTTP 404). 

The console showed error:
```
documentation:75 Uncaught ReferenceError: SwaggerUIBundle is not defined at window.onload
window.onload @ documentation:75
```
I visited all asset files URL, all files are found and loaded correctly.

Is there something missing? I check the swagger-ui version is 3.0.19.

**Comment by matriphe** [comment]
Try to downgrade to version 4 and the UI was shown correctly. Will try to figure out in swagger-ui side.

**Comment by DarkaOnLine** [comment]
@matriphe did you managed to solve this?

**Comment by matriphe** [comment]
@DarkaOnLine I'm still working on this. I will update this as soon as possible.

**Comment by DarkaOnLine** [comment]
OK. Good luck. Let me know if I can help.

**Comment by matriphe** [comment]
I checked the Nginx error logs and found that it's failed to find asset files from `public` directory. 

The route seemed to be ignored and Nginx try to locate the file in root directory. 

```
2017/07/17 20:14:25 [error] 39265#0: *3788 open() "/var/www/laravel/public/docs/asset/swagger-ui.css" failed (2: No such file or directory), client: 127.0.0.1, server: laravel.local, request: "GET /docs/asset/swagger-ui.css HTTP/1.1", host: "laravel.local", referrer: "http://laravel.local/api/documentation"
2017/07/17 20:14:25 [error] 39265#0: *3790 open() "/var/www/laravel/public/docs/asset/swagger-ui-bundle.js" failed (2: No such file or directory), client: 127.0.0.1, server: laravel.local, request: "GET /docs/asset/swagger-ui-bundle.js HTTP/1.1", host: "laravel.local", referrer: "http://laravel.local/api/documentation"
2017/07/17 20:14:25 [error] 39265#0: *3792 open() "/var/www/laravel/public/docs/asset/swagger-ui-standalone-preset.js" failed (2: No such file or directory), client: 127.0.0.1, server: laravel.local, request: "GET /docs/asset/swagger-ui-standalone-preset.js HTTP/1.1", host: "laravel.local", referrer: "http://laravel.local/api/documentation"
```
But if I hit the asset's URL directly, the file is shown, even the Nginx said the file is not found.
```
2017/07/17 20:14:29 [error] 39265#0: *3788 open() "/var/www/laravel/public/docs/asset/swagger-ui-standalone-preset.js" failed (2: No such file or directory), client: 127.0.0.1, server: laravel.local, request: "GET /docs/asset/swagger-ui-standalone-preset.js HTTP/1.1", host: "laravel.local", referrer: "http://laravel.local/api/documentation"
```

I checked using `artisan route:list` the routes is correctly configured. The other routes are working correctly. Very strange.

I'm still continuing my investigation on this.

FYI: I'm running on Mac OSX 10.11, PHP 7.0.20, and Nginx 1.12.0.

**Comment by DarkaOnLine** [comment]
Assets are not located in the public directory. Files in your case are located in `/var/www/laravel/vendor/vendor/swagger-api/swagger-ui/dist` directory and served by the [SwaggerAssetController ](https://github.com/DarkaOnLine/L5-Swagger/blob/master/src/Http/Controllers/SwaggerAssetController.php)

My guess would be that your Nginx configuration is wrong.

But the most strange part is that you can see assets content by hitting the url directly (if I understand correctly you can see content by visiting http://laravel.local/docs/asset/swagger-ui-bundle.js), this should not work also.

**Comment by matriphe** [comment]
Yes. I read the code. The loading part from the helpers is right. 

Yes. The strange part is I can see the content by visiting directly.

My Nginx config is fine. My other Laravel application are running correctly. 

The other route in this app are loaded correctly. I try by curling using header only (`curl -I http://laravel.local/docs/asset/swagger-ui-bundle.js`) it throws HTTP 404. But if I'm curling complete request (`curl http://laravel.local/docs/asset/swagger-ui-bundle.js`) the content file can be shown.

**Comment by ivanm** [comment]
I had a similar problem, removing this part from my nginx config solved the issue:
```
location ~ ^/assets/(img|js|css)/(.*)$ {
    try_files $uri $uri/ /wp-content/themes/sitename/assets/$1/$2;
  }
```

nginx was trying the assets before php does.

**Comment by matriphe** [comment]
@ivanm wow! thanks for your help!

confirmed. the problem is in the Nginx config. After removing this block:

````
location ~* .(jpg|jpeg|png|gif|ico|css|js)$ {
	expires 365d;
}
```

in my Nginx, the docs shown correctly.

**Comment by josedsilva** [comment]
@matriphe Adding _**try_files**_ to the block in Nginx config worked for me.

````
location ~* .(jpg|jpeg|png|gif|ico|css|js)$ {
    try_files $uri /index.php;
    access_log off;
    expires 365d;
}
````

**Comment by sadhakbj** [comment]
@josedsilva Many thanks

**Comment by ismailbangee** [comment]
**Unexpected end of input**

this error is coming in console with blank page.

**Comment by huiyonghkw** [comment]
> @ivanm Wow! Thanks for your help!
> 
> It's confirmed, the problem is in the Nginx config. After removing this block in my Nginx, the docs shown correctly.
> 
> ```
> location ~* .(jpg|jpeg|png|gif|ico|css|js)$ {
> 	expires 365d;
> }
> ```

it Works for me

**Comment by ganapatimoger** [comment]
where is that nginx file

**Comment by adiafora** [comment]
None of this helped me. 
But this helped me:

```
    if (!-e $request_filename) {
      rewrite ^.*$ /index.php last;
    }
```

**Comment by eleftrik** [comment]
> None of this helped me. But this helped me:
> 
> ```
>     if (!-e $request_filename) {
>       rewrite ^.*$ /index.php last;
>     }
> ```

Thank you very much! Now it works!

**Comment by crestpointmediaph** [comment]
Where did you put this

    if (!-e $request_filename) {
      rewrite ^.*$ /index.php last;
    }

**Comment by chimobi-justice** [comment]
> if (!-e $request_filename) {
>         rewrite ^.*$ /index.php last;
>     }

it works for me too many thanks
