### ISSUE TITLE
Class web does not exist error

### ISSUE THREAD

**Issue by surajde16** [DarkaOnLine/L5-Swagger#76]
Hello,
I am using Laravel 5.1 and included "darkaonline/l5-swagger": "~3.0" in the composer.json
Now I am facing this error as "Class web does not exist error" when is run swagger UI URL in browser http://service-url/api/documentation.
Able to generate api-docs.json in the storage folder.
I think web class doesn't exist in laravel 5.1. Do you have a workaround for this issue?

Thank you.

**Comment by surajde16** [comment]
To solve the problem have commented the class web from config/l5-swagger.php and was able to see the swagger UI with broken CSS and js link. To which I have given manual path linking to public vendor folder.

Which is the proper solution? Please suggest.

**Comment by DarkaOnLine** [comment]
Correct way is: https://github.com/DarkaOnLine/L5-Swagger/commit/07621aad8aa2c99b327cba10c487dce90a223de4
