### ISSUE TITLE
"api_key" is hard coded

### ISSUE THREAD

**Issue by Pe-Fahimi** [DarkaOnLine/L5-Swagger#8]
Hi 
in file resources/views/index.blade.php at line 74,
window.authorizations.add("api_key", new ApiKeyAuthorization("api_key", key, "query"));
"api_key" is hard coded.
I wish it was variable that could be set in config.
my api uses "access_token" instead.

thanks a lot man.

**Comment by DarkaOnLine** [comment]
you can just publish view:
```
php artisan l5-swagger:publish-views
```
and then make any corrections. 

But I will think about implementing the config file to be more like Laravel way :)

**Comment by Pe-Fahimi** [comment]
this solution works, but it cause some problem in deploying on production server & automation scripting.

manually editing file that should be generated and also be ignored by git doesn't sense good.

**Comment by DarkaOnLine** [comment]
You are right, I even have this in config file, but not implemented in view. :( 

Will do modifications soon.

**Comment by Pe-Fahimi** [comment]
thanks for your consideration. :+1:

**Comment by DarkaOnLine** [comment]
@Pe-Fahimi is this commit is what you needed:  2380fc637c714eeaf4e10f5c6a534ed14d1e4ed9

You have to be careful with this. Because defining api key in config will show it production and will be visible for all, hope you will use it only in development :)

**Comment by Pe-Fahimi** [comment]
@DarkaOnLine  thanks for your commit,

this is very useful, but i wish you add an item in l5-swagger.php to give ability to change "api_key" to what ever else as a variable. some APIs use something else like "access_token" in header of request as authorization key.

but it is still hard coded in file resources/views/index.blade.php at line 74.

thank you man again.

**Comment by DarkaOnLine** [comment]
Oh, now I know  about what you are talking. [Look at this](https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php#L86)

you can configure optional header and they will be [populated here](https://github.com/DarkaOnLine/L5-Swagger/blob/master/resources/views/index.blade.php#L44-L48)

**Comment by Pe-Fahimi** [comment]
that is a good feature and is so useful for fix values, but It can't be used in such a cases that you want to get it's value from the $('#input_apiKey')[0].value in addApiKeyAuthorization function.

thanks.

**Comment by DarkaOnLine** [comment]
@Pe-Fahimi hope this time I understood your request : 868fbaad943a9eec5e25cac8dad931af33d4cf15

**Comment by Pe-Fahimi** [comment]
@DarkaOnLine  Hi, this is exactly what i wanted. 

many thanks.
