### ISSUE TITLE
Not able to access Swagger UI from this link api/documentation

### ISSUE THREAD

**Issue by surajde16** [DarkaOnLine/L5-Swagger#80]
Hello,
I was able to access the swagger UI in my localhost. Once I

 uploaded to my server. Am getting an exception 
Attached is the screenshot for reference.
![swagger-ui](https://user-images.githubusercontent.com/5235055/28980327-0ae3540e-796b-11e7-819d-8ff97759c910.png)

**Comment by DarkaOnLine** [comment]
This is not related to the package. It looks like swagger can't analyse your code.
