### ISSUE TITLE
Call to undefined function l5_swagger_asset() (View: /var/www/.../resources/views/vendor/l5-swagger/index.blade.php)

### ISSUE THREAD

**Issue by renepardon** [DarkaOnLine/L5-Swagger#85]
Hi,
I've upgraded vom **~4** to **5.4.*** and receive the error within the subject. I followed your migration guide from 4 to 5 and removed the assets. Now I'm not able to load the /api/documentation URI because of this error.

I think for some reason the helpers.php from your package is not loaded. Could this be the case or something different? Which information is required for you?

**Comment by renepardon** [comment]
My solution for now is:

replace all the l5_swagger_asset() calls with just asset() and copy the assets from vendor/swagger-ui/dist to my public folder public/vendor/swagger-ui/

I also had to remove the call for oauth within the javascript at the bottom of the index.blade.php

Now it works but I think this is not the correct solution :)

**Comment by DarkaOnLine** [comment]
@renepardon 

Wich laravel version are you using?

Did you deleted `config/l5-swagger.php` and republished view and new config?

Try run `composer dump-autoload` as well.

**Comment by renepardon** [comment]
Hi @DarkaOnLine 

I'm using laravel 5.4 and i deleted the configuration file and republished the new view and configuration. I also ran the composer dump-autoload and artisan optimize command without success.

With my changes above I can use it - but also only on HTTP because for some reason the assets are being loaded through HTTP only which is yet another problem but not that important :)

**Comment by DarkaOnLine** [comment]
what error are you getting then using `l5_swagger_asset()`?

**Comment by renepardon** [comment]
@DarkaOnLine the one from the subject:

> Call to undefined function l5_swagger_asset() (View: /var/www/.../resources/views/vendor/l5-swagger/index.blade.php)

**Comment by renepardon** [comment]
So I think the helpers.php is - for some reason - not automatically loaded?! Are there some steps. missing from the documentation to setup the loading of helpers.php or should this be done by composer automatically (magic voodoo shit?! :) )

**Comment by DarkaOnLine** [comment]
Can you try removing entire vendor directory and then just run composer install?

**Comment by renepardon** [comment]
already tried ;(

**Comment by DarkaOnLine** [comment]
can you check if the function exists from the `tinker`?

![screen shot 2017-09-18 at 08 43 24](https://user-images.githubusercontent.com/1171698/30530210-7d441d62-9c4d-11e7-9a9c-fef7f6ec62ce.png)

**Comment by renepardon** [comment]
I will try today in the evening :)

**Comment by DarkaOnLine** [comment]
and yes - it should be loaded automatically by "magic voodoo shit" called composer :D

**Comment by renepardon** [comment]
>>> function_exists('l5_swagger_asset')
    => true

It is loaded. So it makes no sense to me that I receive this exception.

**Comment by DarkaOnLine** [comment]
now I am confused too :(
what kind of web server are you using?

**Comment by renepardon** [comment]
I'm Using PHP 7.1 FPM with nginx.

I've set up a local environment with Virtualbox and a few boxes which emulates my live environment with nearly the same setup.

**Comment by DarkaOnLine** [comment]
any specific rules of nginx in the project?

Did you try fresh laravel installation just for testing if this issue is related to your current project or not?

**Comment by renepardon** [comment]
@DarkaOnLine sorry that I didn't replied until now. Had no time to investigate in this as the "fix"/hack works for me. ;)

I will try with a fresh project and compare what the difference between new project and mine is. Maybe there is something special in my project or webserver setup.

**Comment by DarkaOnLine** [comment]
Closing this because of no feedback.

**Comment by dottwatson** [comment]
Same problem with Laravel 5.4 , PHP 7.1 FPM and ngnix... the function l5_swagger_asset exists and works, but ALL the assets (favico, js and css) gives me a 404

**Comment by flik** [comment]
I had the same issue. I resolved in this way:
`./vendor/bin/swagger app/Http/ --output storage/api-docs/api-docs.json
`
then access the url:
http://localhost/angular-laravel/public/api/documentation

I have installed in composer json:

 "require": {
        "php": "^7.1.3",
        "barryvdh/laravel-cors": "^0.11.0",
        "darkaonline/l5-swagger": "5.7.*",
        "fideloper/proxy": "^4.0",
        "folklore/graphql": "^1.1",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0",
        "zircote/swagger-php": "2.*"
    },

**Comment by DarkaOnLine** [comment]
@flik - no its bad very bad solution. Stop posting this to all the issues !!!
