### ISSUE TITLE
[ErrorException] Required @SWG\Info() not found

### ISSUE THREAD

**Issue by webassic15** [DarkaOnLine/L5-Swagger#87]
we are using Laravel 5.2 version and swagger 3.0 version, on calling the command "php artisan l5-swagger:generate" generate command, getting a error "[ErrorException] Required @SWG\Info() not found".

please help to resolve this.

Thanks

**Comment by DarkaOnLine** [comment]
You must include `@SWG\Info()` in your annotations. Please read swagger documentation

See: #56, #51, #5
