### ISSUE TITLE
list properties of a fillable

### ISSUE THREAD

**Issue by francis-santos** [DarkaOnLine/L5-Swagger#89]
I can not display the properties of a fillable, eg:

`/**
     * The attributes that are mass assignable.
     * 
     * @SWG\Property(format="array")
     * @var array
     */
    protected $fillable = ['name', 'email', 'image'];`

how to show the fields entered in the array?

**Comment by DarkaOnLine** [comment]
Please read swagger documentation how to write anotations, or see egzamples. Tis is not related to this package.

**Comment by francis-santos** [comment]
I read the documentation and there is nothing related to this, you would have idea how to get the values ​​of an array by the annotation?

**Comment by DarkaOnLine** [comment]
Examples:  https://github.com/zircote/swagger-php/tree/master/Examples
