### ISSUE TITLE
'query' is hard coded

### ISSUE THREAD

**Issue by Pe-Fahimi** [DarkaOnLine/L5-Swagger#9]
Hi again. 

same as last issue which was changing "api_key" to variable in config file, it would be nice to let it be configurable where it should inject in query or in header.

in file resources/views/index.blade.php at line 72,

window.authorizations.add('{{$apiKeyVar}}', new ApiKeyAuthorization('{{$apiKeyVar}}', key, **"query"**));

my api accept access token just in header not in query.

thanks a lot.

**Comment by DarkaOnLine** [comment]
I fought about it. But for that you can use custom header configuration, like I was suggesting earlier  : https://github.com/DarkaOnLine/L5-Swagger/issues/8#issuecomment-143751073

Doesn't this suits ?

**Comment by Pe-Fahimi** [comment]
no because it  should get api_key from input on panel, custom header is good for const values.
i need to get api_key from input on panel and add to request header.

**Comment by DarkaOnLine** [comment]
solved: 1a5416e142b04b80d2263a85625516b08ce315d5

**Comment by Pe-Fahimi** [comment]
Thanks  a lot. :+1:
