### ISSUE TITLE
validatorUrl: null in the JS breaks loading the UI

### ISSUE THREAD

**Issue by acidjazz** [DarkaOnLine/L5-Swagger#95]
Broken until this is released:

https://github.com/swagger-api/swagger-ui/issues/3851

exact error:

![image](https://user-images.githubusercontent.com/967369/32262395-61b6b2ea-bea2-11e7-9c52-ee744ee24706.png)

It was fixed today, and should release friday, this issue is just a reminder to update this package to that release when it happens

**Comment by DarkaOnLine** [comment]
Until Friday change validation url in config to "   "

**Comment by joonkui95** [comment]
same problem at http://learning.nihaocac.com/api/documentation

**Comment by DarkaOnLine** [comment]
Problem is fixed on Swagger-UI side: https://github.com/swagger-api/swagger-ui/releases/tag/v3.4.3

Run composer update.
