### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by andodemirtshyan** [DarkaOnLine/L5-Swagger#96]
- L5-Swagger Version: (`5.5.2`)
- PHP Version (`7.1`):
- OS: Ubuntu 17.10

problem with JavaScript

 please help: swagger worked without problems
 after composer update( maybe ) I have some error in console:
 please see attached screenshot

( sorry for bad english )

![image](https://user-images.githubusercontent.com/12799007/32262696-72f91e4c-beef-11e7-8d1d-bf30256e6977.png)

**Comment by DarkaOnLine** [comment]
https://github.com/swagger-api/swagger-ui/issues/3851

Duplicate #95

**Comment by andodemirtshyan** [comment]
thanks thanks thanks thanks thanks thanks thanks thanks
