### ISSUE TITLE
Very slow loading times

### ISSUE THREAD

**Issue by athiteshkubavat** [DarkaOnLine/L5-Swagger#99]
- L5-Swagger Version: @stable
- PHP Version (`php -v`): 7.0.22
- OS: Ubuntu 16.04

### Description:
It's too slow to load when I am typing anything in it. When I am typing anything it takes approx 5 to 7 sec to show me a text which I have typed.

### Steps To Reproduce:
Just refresh API document and add parameters to it.

Any suggestion to resolve it?

Thanks in advance!

**Comment by DarkaOnLine** [comment]
Sounds like it is not related to the package. It looks like you have some kind of program which is draining all your PC resources.

**Comment by athiteshkubavat** [comment]
My all programs other than swagger working smoothly so, it's not resources issue.

**Comment by DarkaOnLine** [comment]
If you think so, then try looking into [Swagger-UI](https://github.com/swagger-api/swagger-ui) repo/issues. This package is just a wrapper, so all performance issues should be addressed to Swagger-UI.
